### ISSUE TITLE
XDL是否提供线上模型预测的解决方案？

### ISSUE THREAD

**Issue by weberxie** [alibaba/x-deeplearning#1]
相关文档里没有看到线上模型预测相关的文档，是否计划提供配套的解决方案呢？

**Comment by AlexanLee** [comment]
上次听牟娜女神讲的，应该是不包括。xdl只是模型训练的框架，线上架构的部分应该不包括。

**Comment by ydp** [comment]
是xdl不支持推理，还是不打算开源这部分？

**Comment by songyue1104** [comment]
有计划，这部分工作正在筹备中
------------------------------------------------------------------
发件人：Weber Xie <notifications@github.com>
发送时间：2018年12月21日(星期五) 10:24
收件人：alibaba/x-deeplearning <x-deeplearning@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：Re: [alibaba/x-deeplearning] XDL是否提供线上模型预测的解决方案？ (#1)

@AlexanLee 只要打算把XDL应用到生产环境的话，线上部分是避免不了的，既然训练部分开源了，再让各用户自己造轮子做线上部分有点不合适，毕竟都是通用的需求。
