### ISSUE TITLE
对sparse variable 的分片理解

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#100]
你好呀。我看了部分的variable的代码，比如这边uid的特征是hash到64位的空间，也就是我应该用khash的类型吧。那么如果采用anneal_placementer的方式去分配。那么我看到 x.slice_size = Hasher::kTargetRange。其中Hasher::kTargetRange= 65536。那么对于64位的variable是不是分的片有点多，那得起很多server才可以呀。是不是我理解错了。还有第二个问题，我看到在使用的时候，需要调用client.cc 的RegisterVariable函数。其中要指定shape。比如我对uid这个variable，我指定一个向量，也就是每个uid维度是50维。但是总的uid的个数是随着训练增加的，在刚开始RegisterVariable的时候，怎么指定uid的shape呢。

**Comment by yiling-dc** [comment]
1. 请再仔细看下代码
2. hash表在运行的过程中会自动扩容，但是生成variable的时候指定的shape涉及到参数分配的方案，这个需要用户预估一个较为准确的值，如果预估的过小，有可能在训练过程中发生ps内存不够的情况。

**Comment by songziqin** [comment]
> 1. 请再仔细看下代码
> 2. hash表在运行的过程中会自动扩容，但是生成variable的时候指定的shape涉及到参数分配的方案，这个需要用户预估一个较为准确的值，如果预估的过小，有可能在训练过程中发生ps内存不够的情况。

问下如果现在有一个新的hash的userID的key,是如何找到存这个key的server的，请问下具体流程是什么样子的呢。这个需要访问scheduler末。
