### ISSUE TITLE
FailoverTimes过多原因

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#101]
1、通过xdl_submit的提交方式已经运行成功deepctr的样例。
2、生成自己的数据，训练的时候，node worker:2 fail times FailoverTimes [failoverTimes=4]，直到超过20次，run error，想知道是因为config配置的问题还是？

**Comment by yiling-dc** [comment]
具体的原因需要看下container的日志，也就是worker，ps，scheduler的日志。
