### ISSUE TITLE
如何在自己数据上训练ESMM？

### ISSUE THREAD

**Issue by zhiweige** [alibaba/x-deeplearning#102]
大佬，想在自己的数据上训练ESMM，对训练数据有些困惑。 Feature Structure中feature_field_id 0x02 feature_id 0x03 feature_value，这中间的feature_id 是如何生成的呢？看了https://tianchi.aliyun.com/dataset/dataDetail?dataId=408&userId=1中对数据的介绍，不知道这个feature_id代表什么？多谢大佬解答。

**Comment by sui-hs** [comment]
参考[开放数据集格式说明](https://tianchi.aliyun.com/dataset/dataDetail?dataId=408&userId=1)，"feature_id字段是被全局编码后的特征ID值"，以"109_14"(商品类目ID以及用户在该类目上的历史行为累积数量)为例，下属的feature_id可以理解为一个用户在过去一段时间内对某些类目的点击等行为，具体的值可以由用户id和类目id编码生成，feature_value是这种行为的结果，一般是由用户行为日志统计生成的。
