### ISSUE TITLE
TDM的Predict

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#105]
TDM的文档有如下说法：在任意一次训练产出ckpt后即可按需进行评测。

执行了以下脚本
python train.py --run_mode=local --config=config.predict.json

请问评测的结果在哪里输出，已经翻看了tdm.json中配置的目录，没有发现输出

**Comment by githcx** [comment]
另外一处：
tdm_predict_op.cc文件中的以下片段，执行时正常退出没有走到，能否指出是否是最终结果向stdout的输出：
printf("predict result:\n");
printf("\tglobal_sample_num: %d\n", global_sample_num_);
printf("\tglobal_r_num: %d\n", global_r_num_);
printf("\tglobal_gt_num: %d\n", global_gt_num_);
printf("\tglobal_p_num: %d\n", global_p_num_);
printf("\tglobal_r: %f\n", global_r_num_ * 1.0 / global_gt_num_);
printf("\tglobal_p: %f\n", global_r_num_ * 1.0 / global_p_num_);
printf("\tavg_r: %f\n", avg_r_sum_ * 1.0 / global_sample_num_);
printf("\tavg_p: %f\n", avg_p_sum_ * 1.0 / global_sample_num_);

**Comment by jayhejie** [comment]
请 @lovickie  帮忙看一下？

**Comment by lovickie** [comment]
> 另外一个可能的评测结果的位置，在tdm_predict_op.cc，不知道的是不是最终结果，要求child_ids.size==0的时候才会进入下面的代码，并且会导致Run返回false给data_io.cc的调用处。
> 
> printf("predict result:\n");
> printf("\tglobal_sample_num: %d\n", global_sample_num_);
> printf("\tglobal_r_num: %d\n", global_r_num_);
> printf("\tglobal_gt_num: %d\n", global_gt_num_);
> printf("\tglobal_p_num: %d\n", global_p_num_);
> printf("\tglobal_r: %f\n", global_r_num_ * 1.0 / global_gt_num_);
> printf("\tglobal_p: %f\n", global_r_num_ * 1.0 / global_p_num_);
> printf("\tavg_r: %f\n", avg_r_sum_ * 1.0 / global_sample_num_);
> printf("\tavg_p: %f\n", avg_p_sum_ * 1.0 / global_sample_num_);

是的，r代表召回率，p代表准确率

**Comment by mengyiliu22** [comment]
请问predict_result_file在哪里可以配置呢？
