### ISSUE TITLE
ps报错

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#106]
ErrorCode [1]: Sparse Parttioner: ID Should be 2-D, ID Shape should be [?, 2]。为什么传的id需要[?, 2]这个样子呢。
代码如下：
 void hashPullVariable(client::Client& client, const std::string& variable_name) {
  ps::Tensor result;
  std::promise<bool> p;
  ps::Tensor ids(DataType::kInt64, TensorShape({10}), new initializer::ConstantInitializer(1));
  int64_t* tp = ids.Raw<int64_t>();
  for(int index=0;index<10;index++){
    tp[index] = index;
  }
  tp[0]=99999999l;
  
  client.HashPull(variable_name, ids, 1.0,&result,[&](const Status& st) {
    if (!st.IsOk()) {
      std::cout << st.ToString() << std::endl;
    } else {
    }
    p.set_value(true);
  });
  p.get_future().wait();
  float* tensor_data = result.Raw<float>();
  std::cout << "pull result:" << result.Shape().NumElements() << " * " << tensor_data[0] << std::endl;
  for (size_t i = 0; i < result.Shape().NumElements(); i++) {
    std::cout << "ERROR At " << i << " with " << tensor_data[i] << std::endl;
  }
}

**Comment by yiling-dc** [comment]
hash128需要两个int64组成一个hash key
