### ISSUE TITLE
单机din模型在xdl和tf1.12上性能差5倍以上

### ISSUE THREAD

**Issue by xiaobaoding** [alibaba/x-deeplearning#110]
同样的模型参数设置，同样的数据集。单机跑出来的timeline差5倍以上（如下图）

1.xdl版本din的timeline，
![image](https://user-images.githubusercontent.com/4554417/51973590-f08f0d00-24b8-11e9-8dc3-479ff6151932.png)
2.tf版本din的timeline
![image](https://user-images.githubusercontent.com/4554417/51973608-f97fde80-24b8-11e9-8edf-ccbdd62dd773.png)

din模型的时间来看，大部分时间消耗在_PyFunc这个OP上，能解释下为何？
PS：xdl版本跑起来，cpu使用率也上不去，只能到200%+；tf的轻松700%+；

**Comment by xiaobaoding** [comment]
或者是哪里姿势不对？

**Comment by simon1024** [comment]
分布式跑lr模型也碰到性能问题，10个ps，100个worker的集群规模，xdl上训练比tf慢了1倍以上。看timeline发现大部分时间都消耗在unique，达到了200ms，而在tf上该op不到30ms。
batch size：1024， 每个样本200特征
![image](https://user-images.githubusercontent.com/11550277/52022752-499c8680-2535-11e9-8867-2ed3b1b4a275.png)
我看了下实现，由于xdl里的id是由hkey和key组成的，所以unique的实现有些不一样，不知道是不是哪里实现不合理？

**Comment by songyue1104** [comment]
1.如果用的dataio，可以设置UniqueId选项，这样可以隐藏unique时间
2.我们正在优化unique性能





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：simon1024<notifications@github.com>
日　期：2019年01月31日 08:53:39
收件人：alibaba/x-deeplearning<x-deeplearning@noreply.github.com>
抄　送：Subscribed<subscribed@noreply.github.com>
主　题：Re: [alibaba/x-deeplearning] 单机din模型在xdl和tf1.12上性能差5倍以上 (#110)

分布式跑lr模型也碰到性能问题，10个ps，100个worker的集群规模，xdl上训练比tf慢了1倍以上。看timeline发现大部分时间都消耗在unique，达到了200ms，而在tf上该op不到30ms。
 batch size：1024， 每个样本200特征

 我看了下实现，由于xdl里的id是由hkey和key组成的，所以unique的实现有些不一样，不知道是不是哪里实现不合理？

**Comment by songyue1104** [comment]
pyfunc仅用于调试和小规模实验，生产环境尽量使用dataio





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：xiaobaoding<notifications@github.com>
日　期：2019年01月30日 18:03:26
收件人：alibaba/x-deeplearning<x-deeplearning@noreply.github.com>
抄　送：Subscribed<subscribed@noreply.github.com>
主　题：[alibaba/x-deeplearning] 单机din模型在xdl和tf1.12上性能差5倍以上 (#110)

同样的模型参数设置，同样的数据集。单机跑出来的timeline差5倍以上（如下图）
1.xdl版本din的timeline，

 2.tf版本din的timeline

 din模型的时间来看，大部分时间消耗在_PyFunc这个OP上，能解释下为何？

**Comment by simon1024** [comment]
> 1.如果用的dataio，可以设置UniqueId选项，这样可以隐藏unique时间 2.我们正在优化unique性能 来自钉钉专属商务邮箱------------------------------------------------------------------ 发件人：simon1024<notifications@github.com> 日　期：2019年01月31日 08:53:39 收件人：alibaba/x-deeplearning<x-deeplearning@noreply.github.com> 抄　送：Subscribed<subscribed@noreply.github.com> 主　题：Re: [alibaba/x-deeplearning] 单机din模型在xdl和tf1.12上性能差5倍以上 (#110) 分布式跑lr模型也碰到性能问题，10个ps，100个worker的集群规模，xdl上训练比tf慢了1倍以上。看timeline发现大部分时间都消耗在unique，达到了200ms，而在tf上该op不到30ms。 batch size：1024， 每个样本200特征 我看了下实现，由于xdl里的id是由hkey和key组成的，所以unique的实现有些不一样，不知道是不是哪里实现不合理？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

感觉sparsePull的时间也是偏长的，tf里gather的时间一般在1ms左右，即使加上查找id的时间，我认为大概10ms左右应该可以搞定。但是我这边是消耗了40多ms，不知道是不是因为sparsePull做了什么额外的消耗时间的操作，或者是因为我的seastar没有bindcore，所以没有发挥出性能优势。

**Comment by songyue1104** [comment]
ps-plus设计之初主要针对高并发场景，为了提高性能，采用的是one request per thread的，即所有请求都在同一个线程处理，以降低高并发下的线程切换代价。我们最近也在做针对低并发场景的优化，在这种场景会使用多线程进行计算加速

**Comment by guotong1988** [comment]
图很牛！问下TDM有没有类似https://github.com/mouna99/dien 的单独实现？脱离XDL的纯python

**Comment by lisency** [comment]
@xiaobaoding 图很牛！请教图是怎么画的
