### ISSUE TITLE
运行了几个step后, 显示被Killed, 没有提示其他错误，在docker环境下运行

### ISSUE THREAD

**Issue by drfilter** [alibaba/x-deeplearning#112]
loss:0.6928083 acc:0.5136719, auc:0.49937066
loss:0.6925886 acc:0.5263672, auc:0.49959862
loss:0.6932694 acc:0.49609375, auc:0.49959263
loss:0.6933698 acc:0.49902344, auc:0.499618
loss:0.69331044 acc:0.49316406, auc:0.49962384
loss:0.6927252 acc:0.51464844, auc:0.4996632
loss:0.69215226 acc:0.5253906, auc:0.4998721
loss:0.6928943 acc:0.515625, auc:0.49992165
loss:0.6926905 acc:0.5185547, auc:0.49976784
Killed

**Comment by guoxinyang** [comment]
可以检查下docker的内存是不是设置的够大，有可能是因为内存超限被干掉的

**Comment by drfilter** [comment]
@guoxinyang , 运行过程中内存会一直增长？为啥前几次step有输出
