### ISSUE TITLE
TDM跑随机dummy小数据集执行结果？（单机试验）

### ISSUE THREAD

**Issue by ybeforev** [alibaba/x-deeplearning#113]
请问TDM跑随机dummy小数据集，执行predict后标准输出：

> result:
> 	global_sample_num: 10
> 	global_r_num: 0
> 	global_gt_num: 551
> 	global_p_num: 200
> 	global_r: 0.000000
> 	global_p: 0.000000
> 	avg_r: 0.000000
> 	avg_p: 0.000000
> result is None, finished success.

配置的predict_result_file里面只有以下内容：

> 1000194_T:

以上结果没有满足预期，请问可以给出dummy小数据集预期结果吗？

**Comment by TwinbladeX** [comment]
遇到了同样的问题，求问题主解了吗

**Comment by lovickie** [comment]
> 请问TDM跑随机dummy小数据集，执行predict后标准输出：
> 
> > result:
> > global_sample_num: 10
> > global_r_num: 0
> > global_gt_num: 551
> > global_p_num: 200
> > global_r: 0.000000
> > global_p: 0.000000
> > avg_r: 0.000000
> > avg_p: 0.000000
> > result is None, finished success.
> 
> 配置的predict_result_file里面只有以下内容：
> 
> > 1000194_T:
> 
> 以上结果没有满足预期，请问可以给出dummy小数据集预期结果吗？

小数据集只用来快速验证流程（运行成功），不以对齐效果为目标。

**Comment by ZWhangH** [comment]
> 请问TDM跑随机dummy小数据集，执行predict后标准输出：
> 
> > result:
> > global_sample_num: 10
> > global_r_num: 0
> > global_gt_num: 551
> > global_p_num: 200
> > global_r: 0.000000
> > global_p: 0.000000
> > avg_r: 0.000000
> > avg_p: 0.000000
> > result is None, finished success.
> 
> 配置的predict_result_file里面只有以下内容：
> 
> > 1000194_T:
> 
> 以上结果没有满足预期，请问可以给出dummy小数据集预期结果吗？

请问你跑的是GPU版本的吗？

**Comment by ybeforev** [comment]
@ZWhangH 只能输出 string
