### ISSUE TITLE
请问下这里import xdl的xdl是哪个？多谢多谢多谢！

### ISSUE THREAD

**Issue by guotong1988** [alibaba/x-deeplearning#119]
https://github.com/alibaba/x-deeplearning/blob/master/xdl-algorithm-solution/TDM/script/tdm_ub_att_ubuntu/train.py#L17
![image](https://user-images.githubusercontent.com/4702353/52096096-8bdeca00-2600-11e9-8b5a-5d574ecf55d6.png)
我是只把python拿出来学习

**Comment by jingcheng-WU** [comment]
docker 环境里打开python就可以import xdl 了

**Comment by guotong1988** [comment]
THX
