### ISSUE TITLE
请问下tdm_ub_att_ubuntu和tdm_ub_vector_ubuntu有什么区别？多谢多谢！

### ISSUE THREAD

**Issue by guotong1988** [alibaba/x-deeplearning#120]
https://github.com/alibaba/x-deeplearning/tree/master/xdl-algorithm-solution/TDM/script

**Comment by jlinleung** [comment]
> 好像主要区别在`train.py`的`dnn_model_define`方法

前者加了attention机制，后者没加

**Comment by ustcdane** [comment]
@zhuhan1236 @MaButing 请问 xdl-algorithm-solution/TDM/script/tdm_ub_vector_ubuntu 是TDM论文中的 TDM DNN吗？ 看了下代码，tdm_ub_vector_ubuntu 比较像 Youtube product-DNN， 期待解答，谢谢~~

**Comment by zhuhan1236** [comment]
> @zhuhan1236 @MaButing 请问 xdl-algorithm-solution/TDM/script/tdm_ub_vector_ubuntu 是TDM论文中的 TDM DNN吗？ 看了下代码，tdm_ub_vector_ubuntu 比较像 Youtube product-DNN， 期待解答，谢谢~~

xdl-algorithm-solution/TDM/script/tdm_ub_vector_ubuntu是论文里的 Youtube product-DNN
