### ISSUE TITLE
这里没说用哪个脚本？

### ISSUE THREAD

**Issue by guotong1988** [alibaba/x-deeplearning#122]
https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)#%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86%E8%84%9A%E6%9C%AC

这里没说用哪个脚本处理原始数据，多谢！

**Comment by guotong1988** [comment]
貌似是`generator.py`

**Comment by guotong1988** [comment]
python generator.py --train_data_file /home/tong.guo/TDM/start_data_train.txt --test_data_file /home/tong.guo/TDM/start_data_test.txt --tree_pb_file /home/tong.guo/TDM/tree_pb_file --train_sample_file /home/tong.guo/TDM/train_sample_file --test_sample_file /home/tong.guo/TDM/test_sample_file --feature_conf /home/tong.guo/TDM/userbehavoir_fc.json --stat_file /home/tong.guo/TDM/userbehavoir_stat.dat

**Comment by guotong1988** [comment]
8225107,2743616,18005,pv,1550208120
8225107,2743006,41869,pv,1550207820
8225107,195452,40688,pv,1550207640
8225107,1450209,17086,pv,1550207400
8225107,2532871,17057,pv,1550207160

**Comment by guotong1988** [comment]
{
  "features": {
    "item_1": {
      "end": 70, 
      "start": 0, 
      "value": 1
    } 
  }
}

**Comment by jump2** [comment]
@guotong1988 原始数据的测试集和训练集需要用户自己处理，如何采样呢？
--train_data_file /home/tong.guo/TDM/start_data_train.txt --test_data_file /home/tong.guo/TDM/start_data_test.txt 也就是这个两个数据，我用的是他们的公开数据集(UserBehavior)数据，难道要自己去处理下？
