### ISSUE TITLE
TDM跑user behavior数据集的predict结果不符合预期？

### ISSUE THREAD

**Issue by ybeforev** [alibaba/x-deeplearning#129]
predict输出的结果文件如下：
> 176997_T:**4129351**,0.516018;1783293,0.512362;1670458,0.511632;124875,0.510577;3610011,0.509100;3467661,0.508552;408860,0.508467;686241,0.507956;957200,0.506496;167362,0.506446;4255574,0.506142;1458710,0.505082;323790,0.504772;2472257,0.504487;1933464,0.504431;5115704,0.503927;3540632,0.503714;4512646,0.503603;1736623,0.503212;2560262,0.502729;
> 101126_T:**4129351**,0.516022;1783293,0.512667;1670458,0.511618;3612670,0.511488;124875,0.510828;3610011,0.509193;396238,0.508837;3467661,0.508726;408860,0.508601;957200,0.506531;167362,0.506512;4255574,0.505833;1458710,0.504977;323790,0.504837;2472257,0.504506;1933464,0.504290;5115704,0.504017;3540632,0.503655;1736623,0.503377;2560262,0.502944;
> 798897_T:1395258,0.516107;**4129351**,0.516000;1783293,0.512327;1670458,0.511564;3612670,0.511454;124875,0.510572;3610011,0.509085;3467661,0.508539;408860,0.508454;686241,0.507936;957200,0.506487;167362,0.506428;4255574,0.506133;1458710,0.505071;323790,0.504767;2472257,0.504483;1933464,0.504383;5115704,0.503914;4512646,0.503594;1736623,0.503170;
> 97031_T:**4129351**,0.516035;1783293,0.512375;1670458,0.511624;124875,0.510595;3610011,0.509098;3467661,0.508575;408860,0.508490;686241,0.507953;957200,0.506502;167362,0.506480;4255574,0.506175;1458710,0.505081;323790,0.504791;2472257,0.504488;1933464,0.504436;5115704,0.503934;3540632,0.503734;4512646,0.503609;1736623,0.503202;2560262,0.502773;
> 253454_T:**4129351**,0.515753;1395258,0.515534;1783293,0.511868;1670458,0.510932;124875,0.510330;3610011,0.508737;3467661,0.508294;408860,0.508026;686241,0.507705;957200,0.506372;167362,0.505893;4255574,0.505354;1458710,0.504763;323790,0.504648;2472257,0.504457;1933464,0.503846;5115704,0.503730;4512646,0.503542;1736623,0.502612;3542618,0.502328;
> 841103_T:1395258,0.516124;**4129351**,0.516006;1783293,0.512359;1670458,0.511598;3612670,0.511457;124875,0.510568;3610011,0.509081;3467661,0.508550;408860,0.508448;686241,0.507946;957200,0.506492;167362,0.506409;4255574,0.506093;1458710,0.505042;323790,0.504773;2472257,0.504487;1933464,0.504394;5115704,0.503909;4512646,0.503606;1736623,0.503188;
> 539569_T:1395258,0.516161;**4129351**,0.516021;1783293,0.512371;1670458,0.511614;3612670,0.511475;124875,0.510583;3610011,0.509105;3467661,0.508558;408860,0.508474;686241,0.507952;957200,0.506492;167362,0.506448;4255574,0.506157;1458710,0.505080;323790,0.504778;2472257,0.504488;1933464,0.504407;5115704,0.503930;4512646,0.503605;1736623,0.503198;
> 387891_T:**4129351**,0.516044;1783293,0.512389;1670458,0.511625;124875,0.510590;3610011,0.509105;3467661,0.508551;408860,0.508498;686241,0.507964;167362,0.506503;957200,0.506496;4255574,0.506180;1458710,0.505105;323790,0.504780;2472257,0.504488;1933464,0.504427;5115704,0.503925;3540632,0.503724;4512646,0.503606;1736623,0.503225;2560262,0.502732;
> 636431_T:**4129351**,0.516035;1783293,0.512295;1670458,0.511676;3612670,0.511414;124875,0.510588;3610011,0.509074;3467661,0.508548;408860,0.508536;686241,0.507964;167362,0.506624;957200,0.506485;4255574,0.506375;1458710,0.505091;1933464,0.504490;2472257,0.504478;5115704,0.503890;3540632,0.503783;4512646,0.503581;1736623,0.503194;2560262,0.502790;
> 206620_T:1395258,0.516135;**4129351**,0.516095;1783293,0.512370;1670458,0.511581;3612670,0.511449;124875,0.510617;3610011,0.509106;3467661,0.508587;408860,0.508400;957200,0.506533;167362,0.506476;4255574,0.506044;1458710,0.505012;323790,0.504840;2472257,0.504497;1933464,0.504319;5115704,0.503965;4512646,0.503668;1736623,0.503120;2560262,0.502736;
结果不符合预期，例如item：4129351在每个用户下都有。准确来说，每个用户下只是相同的20个item（设置的top20）依不同次序呈现。与预期：“不同用户依据其行为差异产生不同结果”相违背。请问可能的问题在哪里？

**Comment by canglingye** [comment]
从提供的预测结果来看，使用的模型似乎是一个训练不充分甚至接近随机初始化的模型（概率值都接近0.5)。建议检查下预测时是否使用了正确的模型(比如错误的加载了初始化模型或者未加载)。另外，如果模型训练轮数过少，会导致学习不充分，也可能导致此问题。

**Comment by ybeforev** [comment]
@canglingye 谢谢！

**Comment by beercool** [comment]
@ybeforev 我遇到了类似的问题，请问你是如何解决的？

请问TDM跑随机dummy小数据集，执行predict后标准输出：

result:
global_sample_num: 10
global_r_num: 0
global_gt_num: 551
global_p_num: 200
global_r: 0.000000
global_p: 0.000000
avg_r: 0.000000
avg_p: 0.000000
result is None, finished success.

配置的predict_result_file里面只有以下内容：

1000194_T:

**Comment by mengyiliu22** [comment]
> @ybeforev 我遇到了类似的问题，请问你是如何解决的？
> 
> 请问TDM跑随机dummy小数据集，执行predict后标准输出：
> 
> result:
> global_sample_num: 10
> global_r_num: 0
> global_gt_num: 551
> global_p_num: 200
> global_r: 0.000000
> global_p: 0.000000
> avg_r: 0.000000
> avg_p: 0.000000
> result is None, finished success.
> 
> 配置的predict_result_file里面只有以下内容：
> 
> 1000194_T:

请问predict_result_file在哪里配置呢？

**Comment by CyanSong** [comment]
> @ybeforev 我遇到了类似的问题，请问你是如何解决的？
> 
> 请问TDM跑随机dummy小数据集，执行predict后标准输出：
> 
> result:
> global_sample_num: 10
> global_r_num: 0
> global_gt_num: 551
> global_p_num: 200
> global_r: 0.000000
> global_p: 0.000000
> avg_r: 0.000000
> avg_p: 0.000000
> result is None, finished success.
> 
> 配置的predict_result_file里面只有以下内容：
> 
> 1000194_T:
遇到了同样的问题，有解决办法么？
