### ISSUE TITLE
Hadoop版本问题

### ISSUE THREAD

**Issue by wenruij** [alibaba/x-deeplearning#130]
Hadoop 3.1.X官方的稳定版本是3.1.1开始的，x-deeplearning/xdl/distributed/gpu_patch/目录下提供的hadoop-yarn-server-nodemanager-3.1.0.jar 可以   **直接**   用于hadoop 3.1.1等更高版本吗？

**Comment by songyue1104** [comment]
没有试验过，如果你不需要GPU卡绑定这个功能的话可以直接使用官方版本，如果需要绑卡功能，可以参考gpu_ids.patch，修改nodemanager
