### ISSUE TITLE
TDMServing文档中提到的模型文件graph.txt、dense.txt、sparse.txt训练后没有产出

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#132]
新开源的TDMServing部分中关于模型数据的介绍中（ https://github.com/alibaba/x-deeplearning/wiki/TDMServing ），有下面的段落，提到了原始 TDM 模型数据，一共四个文件：
dense.txt、graph.txt、item_emb、sparse.txt

> TDM模型通过XDL线下训练后产生的数据有：
> 原始 TDM 树索引数据，userbehavior_tree.pb
> 原始 TDM 模型数据，dense.txt、graph.txt、item_emb、sparse.txt
> XDL线下数据需要经过处理，转换为线上数据文件，供 TDM Serving 使用。

在我们之前的训练中按照之前TDM文档
（ https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM) )
产出其中的item_emb应该是没有问题的，这个item_emb在聚类过程中是作为输入文件的，在tdm.json中可以配置item_emb生成后的保存目录

但是其余的三个文件(graph.txt，dense.txt，sparse.txt)，没有看到，搜索源代码只找到了疑似与graph.txt生成有关的saver.py文件，按照对源码的理解，在tdm.json中增加了配置项（"saver_ckpt": "10"）做尝试，重新训练、聚类，没能生成graph.txt。

请问以上疑问是我们训练的产出缺失造成的，还是TDMServing中省略了从训练产出之后的一些中间操作，还是原始数据的问题，怎么修改训练步骤才能生成graph.txt、dense.txt、sparse.txt这三个文件，谢谢

**Comment by lovickie** [comment]
XDL离线训练产出模型会针对Serving产出如题主所述格式的文件。该部分代码晚些时候会更新到XDL上。

**Comment by githcx** [comment]
> XDL离线训练产出模型会针对Serving产出如题主所述格式的文件。该部分代码晚些时候会更新到XDL上。

好的，谢谢。

**Comment by wshexin** [comment]
请问这部分代码（生成dense.txt等）什么时候可以上线？

**Comment by lovickie** [comment]
> 请问这部分代码（生成dense.txt等）什么时候可以上线？

这个月内就会把代码放上来

**Comment by sandflee** [comment]
急需这个功能来打通整个流程

**Comment by qianghuang84** [comment]
也是走到这一步走不通了

**Comment by gzkai** [comment]
同样走到这一步走不通

**Comment by CyanSong** [comment]
同样有问题

**Comment by drfilter** [comment]
这个问题解决了吗？

**Comment by sandflee** [comment]
> > 请问这部分代码（生成dense.txt等）什么时候可以上线？
> 
> 这个月内就会把代码放上来

有预期的完成时间吗？

**Comment by lazy2panda** [comment]
> > 请问这部分代码（生成dense.txt等）什么时候可以上线？
> 
> 这个月内就会把代码放上来

请问现在放上来了吗？

**Comment by larsoncs** [comment]
我也遇到这个问题
