### ISSUE TITLE
分布式模式下 checkpoint卡住

### ISSUE THREAD

**Issue by bcfntu** [alibaba/x-deeplearning#134]
1、问题：
以下是我保存checkpoint的方式：
        if int(xdl.get_task_index()) == 0:
            saver = xdl.Saver()
            checkpoint_version = "001"
            saver.save(version = checkpoint_version) 
分布式情况下会在这个地方卡住
2、现象:
查看日志，Schedule和PS 都打印了以下的错误：
Reactor stalled for 4002 ms on shard 5.
Backtrace:
  0x0000000000ee4e2c
  0x0000000000ee5158
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001026a
  /lib/x86_64-linux-gnu/libpthread.so.0+0x0000000000009dbc
  0x0000000000bfdc1e
  0x0000000000c00329
  0x0000000000c013c8
  0x0000000000c00813
  0x0000000000d622a0
  0x0000000000d49c4e
  0x0000000000d43776
  0x0000000000d4cc21
  0x0000000000e83dbb
  0x0000000000e830a1
  0x0000000000eaa5ab
  0x0000000000eabae5
  0x0000000000eac795
  0x0000000000eb3846
  0x0000000000edc3a7
  0x0000000000edc6a0
  0x0000000000f3596a
  0x0000000000f3b3f7
  0x0000000000f8973d
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c
3、帮助：
（1）错误是seastar库打印出来的，一般情况下，哪些问题会触发这个？
（2）checkpoint卡住 是否可能是由于searstar的这个错误导致？

**Comment by simon1024** [comment]
> 1、问题：
> 以下是我保存checkpoint的方式：
> if int(xdl.get_task_index()) == 0:
> saver = xdl.Saver()
> checkpoint_version = "001"
> saver.save(version = checkpoint_version)
> 分布式情况下会在这个地方卡住
> 2、现象:
> 查看日志，Schedule和PS 都打印了以下的错误：
> Reactor stalled for 4002 ms on shard 5.
> Backtrace:
> 0x0000000000ee4e2c
> 0x0000000000ee5158
> /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
> /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001026a
> /lib/x86_64-linux-gnu/libpthread.so.0+0x0000000000009dbc
> 0x0000000000bfdc1e
> 0x0000000000c00329
> 0x0000000000c013c8
> 0x0000000000c00813
> 0x0000000000d622a0
> 0x0000000000d49c4e
> 0x0000000000d43776
> 0x0000000000d4cc21
> 0x0000000000e83dbb
> 0x0000000000e830a1
> 0x0000000000eaa5ab
> 0x0000000000eabae5
> 0x0000000000eac795
> 0x0000000000eb3846
> 0x0000000000edc3a7
> 0x0000000000edc6a0
> 0x0000000000f3596a
> 0x0000000000f3b3f7
> 0x0000000000f8973d
> /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
> /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c
> 3、帮助：
> （1）错误是seastar库打印出来的，一般情况下，哪些问题会触发这个？
> （2）checkpoint卡住 是否可能是由于searstar的这个错误导致？

我也碰到了checkpint时，worker端卡住的情况。看堆栈，是在执行PsSaveOp, worker一直处于future.wait()状态。

**Comment by bcfntu** [comment]
@simon1024 
你的ps的日志也会报出Reactor stalled for 4002 ms on shard 5.错误吗？

我在小数据集上实验，seastar没报错，checkpoint可以执行下去

**Comment by codewdy** [comment]
一般而言这种情况可能是由于Checkpoint存储时间过长产生的错觉。
我们会在接下来的版本中对存储Checkpoint的时间进行优化。

**Comment by bcfntu** [comment]
@codewdy 
Reactor stalled for 4002 ms on shard 5.
seastar 报出的错 是什么原因引起的？
