### ISSUE TITLE
为什么TDM模型训练过程不支持通过控制损失函数值在一定次数波动小于某个阈值结束训练

### ISSUE THREAD

**Issue by jlinleung** [alibaba/x-deeplearning#136]

**Comment by lovickie** [comment]
我简单说下我个人的理解，以供讨论。
当前，作为匹配推荐算法，TDM的效果指标是评估产出的准确率与召回率，这也比loss更直观。
其次，在整个训练过程中，loss会呈波动下降趋势，准确率与召回率也会呈现一定波动。通过评测来选取一个最优模型是目前一个可行的方案之一。
当然未来TDM也可能不仅仅是匹配推荐，这是后话了。
