### ISSUE TITLE
TDMServing编译时报错

### ISSUE THREAD

**Issue by ybeforev** [alibaba/x-deeplearning#137]
在TDMServing编译过程中，提示以下错误，请问如何解决？
相关配置如下：
> OS: CentOS Linux release 7.4.1708 (Core)
> GCC: 5.2.0
> protobuf: 3.6.0

编译报错：
> Linking CXX executable tdm_example
> Linking CXX executable tdm_evaluation
> Linking CXX executable tdm_benchmark
> CMakeFiles/tdm_example.dir/tdm_example.cpp.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
> /usr/local/include/google/protobuf/arenastring.h:206: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_example.dir/tdm_example.cpp.o: In function `tdm_serving::MakeRequest(tdm_serving::SearchParam*, unsigned int)':
> tdm_example.cpp:(.text+0x16a8): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_example.dir/tdm_example.cpp.o: In function `tdm_serving::SearchExample(unsigned int)':
> tdm_example.cpp:(.text+0x1a6d): undefined reference to `google::protobuf::Message::DebugString() const'
> tdm_example.cpp:(.text+0x1cd9): undefined reference to `google::protobuf::Message::DebugString() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::ListInputName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::SparseFeatureName2FeedName(std::string const&, blaze::SparseFeatureType)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::IndicatorLevel2FeedName(int)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::GetFeedNameConfig(std::string const&)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/tdm_example] Error 1
> make[1]: *** [examples/CMakeFiles/tdm_example.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> CMakeFiles/tdm_evaluation.dir/tdm_evaluation.cpp.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
> /usr/local/include/google/protobuf/arenastring.h:206: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_evaluation.dir/tdm_evaluation.cpp.o: In function `tdm_serving::SearchEvaluate(unsigned int, unsigned int)':
> tdm_evaluation.cpp:(.text+0x1bff): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::ListInputName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::SparseFeatureName2FeedName(std::string const&, blaze::SparseFeatureType)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::IndicatorLevel2FeedName(int)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::GetFeedNameConfig(std::string const&)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [evaluation/tdm_evaluation] Error 1
> make[1]: *** [evaluation/CMakeFiles/tdm_evaluation.dir/all] Error 2
> CMakeFiles/tdm_benchmark.dir/tdm_benchmark.cpp.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
> /usr/local/include/google/protobuf/arenastring.h:206: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_benchmark.dir/tdm_benchmark.cpp.o: In function `tdm_serving::MakeRequests(std::vector<tdm_serving::SearchParam, std::allocator<tdm_serving::SearchParam> >*, unsigned int)':
> tdm_benchmark.cpp:(.text+0x1558): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::ListInputName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::SparseFeatureName2FeedName(std::string const&, blaze::SparseFeatureType)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::IndicatorLevel2FeedName(int)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::GetFeedNameConfig(std::string const&)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [benchmark/tdm_benchmark] Error 1
> make[1]: *** [benchmark/CMakeFiles/tdm_benchmark.dir/all] Error 2
> Linking CXX executable tdm_with_filter_example
> CMakeFiles/tdm_with_filter_example.dir/tdm_with_filter_example.cpp.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
> /usr/local/include/google/protobuf/arenastring.h:206: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_with_filter_example.dir/tdm_with_filter_example.cpp.o: In function `tdm_serving::MakeRequest(tdm_serving::SearchParam*, unsigned int)':
> tdm_with_filter_example.cpp:(.text+0x16d8): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
> CMakeFiles/tdm_with_filter_example.dir/tdm_with_filter_example.cpp.o: In function `tdm_serving::SearchExample(unsigned int)':
> tdm_with_filter_example.cpp:(.text+0x1a9d): undefined reference to `google::protobuf::Message::DebugString() const'
> tdm_with_filter_example.cpp:(.text+0x1d09): undefined reference to `google::protobuf::Message::DebugString() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::GetTypeName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::ListInputName() const'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::SparseFeatureName2FeedName(std::string const&, blaze::SparseFeatureType)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::FeedNameUtility::IndicatorLevel2FeedName(int)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `blaze::Predictor::GetFeedNameConfig(std::string const&)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
> ../tdm-serving/libtdm_serving.so: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/tdm_with_filter_example] Error 1
> make[1]: *** [examples/CMakeFiles/tdm_with_filter_example.dir/all] Error 2
> make: *** [all] Error 2

**Comment by douziaza** [comment]
可以提供下
1. 执行 cmake .. 后的信息
2. tdm库依赖的 protobuf 库信息：build/tdm-serving 下 ldd libtdm_serving.so
3. 链接时使用的库信息：build/examples/CMakeFiles/tdm_example.dir 下 flags.make 与 link.txt 信息

**Comment by ybeforev** [comment]
内容提供如下：
1. 执行 cmake .. 后信息：
```
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD_UNIT_TESTS=OFF
-- WITH_DEBUG_SYMBOLS=ON
-- CMAKE_INSTALL_PREFIX=/opt/tdm-serving/
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.so  
-- Found glog: /usr/local/lib/libglog.so
-- Found blaze: /opt/blaze/lib/libblaze.so
-- Configuring done
-- Generating done
-- Build files have been written to: /export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/build
```

2. ldd libtdm_serving.so:
```
	linux-vdso.so.1 =>  (0x00007fff3b77f000)
	libprotobuf.so.16 => /usr/local/lib/libprotobuf.so.16 (0x00007fc04adef000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fc04abd2000)
	libglog.so.0 => /usr/local/lib/libglog.so.0 (0x00007fc04a9a4000)
	libblaze.so => /opt/blaze/lib/libblaze.so (0x00007fc04a1b0000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc049e34000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007fc049b32000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007fc049910000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fc0496f8000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fc049335000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563fa2f3b000)
	libz.so.1 => /usr/lib/../lib64/libz.so.1 (0x00007fc04911f000)
	libmkl_intel_lp64.so => /export/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so (0x00007fc048602000)
	libmkl_intel_thread.so => /export/opt/intel/mkl/lib/intel64/libmkl_intel_thread.so (0x00007fc046234000)
	libmkl_core.so => /export/opt/intel/mkl/lib/intel64/libmkl_core.so (0x00007fc042202000)
	libiomp5.so => /export/opt/intel/lib/intel64/libiomp5.so (0x00007fc041e26000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fc041c22000)
```

3.1. flags.make:
```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# compile CXX with /usr/bin/c++
CXX_FLAGS = -Wall -W -fPIC -Wno-unused-but-set-variable -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -fopenmp -g  -O2 -DNDEBUG -I/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/build -I/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing -I/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/tdm-serving -I/usr/local/include -I/opt -I/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/tdm-serving/api -I/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/build/proto   

CXX_DEFINES =
```

3.2. link.txt:
`/usr/bin/c++   -Wall -W -fPIC -Wno-unused-but-set-variable -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -fopenmp -g  -O2 -DNDEBUG   CMakeFiles/tdm_example.dir/tdm_example.cpp.o  -o tdm_example -rdynamic ../tdm-serving/libtdm_serving.so -lprotobuf -lpthread -lglog /opt/blaze/lib/libblaze.so -Wl,-rpath,/export/x-deeplearning/xdl-facility/xdl-algorithm-solution/TDMServing/build/tdm-serving:/opt/blaze/lib`

**Comment by douziaza** [comment]
protobuf 是本地编译出来的么
另外，在 protobuf 2.4 与 gcc 4.8.5 上我有完整测试，可以尝试以此环境配置试下
稍后我搭建下 centos + pb 3.6 + gcc 5.2 环境试下

**Comment by ybeforev** [comment]
protobuf是本地编译出来的，使用的是官方下载的：protobuf-cpp-3.6.0.zip

**Comment by douziaza** [comment]
可以试下 gcc 4.8.5 + protobuf 2.4 是否会遇到同样问题

**Comment by douziaza** [comment]
我搭建了
CentOS Linux release 7.6.1810
GCC: 5.2.0
GCC：5.3.1
protobuf: 3.6.1
区别是把 blaze 库摘除了，因为 centos 虚拟环境不容易搭建 intel mkl
是可以编译过的

**Comment by douziaza** [comment]
目前搭建了
CentOS Linux release 7.6.1810
GCC：5.3.1
protobuf: 3.6.1

blaze：
    以 cmake ../ -DUSE_CUDA=0 -DUSE_MKL=0 DSYMBOL_EXPORT_CTL=1 && make && sudo make install 安装
    关闭 intel mkl，以 open_blas 替代，

可以编译通过

**Comment by ybeforev** [comment]
十分感谢！我试试

**Comment by jibingbing123** [comment]
所以最后是没使用mkl解决的吗
