### ISSUE TITLE
试了下目前xdl好像只支持在ubuntu系统上跑，不支持redhat上跑

### ISSUE THREAD

**Issue by jlinleung** [alibaba/x-deeplearning#140]
xdl要求glibc库版本是2.18， redhat上支持的最新glibc库版本是2.17。 试了下好像没法再redhat上跑， 请问后期会支持在不同系统环境上跑么

**Comment by codewdy** [comment]
你可以使用docker image的方式进行部署。或者对系统中的glibc版本进行升级。
XDL本身对glibc应该没有什么限制，希望能提供具体的错误原因和复现方法。

**Comment by jlinleung** [comment]
> 你可以使用docker image的方式进行部署。或者对系统中的glibc版本进行升级。
> XDL本身对glibc应该没有什么限制，希望能提供具体的错误原因和复现方法。

![image](https://user-images.githubusercontent.com/9393229/53393961-bee66480-39d8-11e9-95c2-2571b38dfd32.png)

![image](https://user-images.githubusercontent.com/9393229/53394094-21d7fb80-39d9-11e9-84ab-afc1d781ca75.png)

在redhat系统跑加载xdl提示glibc需要2.18，yum查了下最新是2.17版本
