### ISSUE TITLE
model_converter转din模型core

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#141]
按照wiki编译安装了blaze， 没有使用cuda和mkl。安装好之后，尝试跑模型服务样例，在对模型进行转换的时候出core。
出错信息如下：
<pre>
root@8908c4b8ac72:/opt/blaze/tools/example_model/din# python ../../model_converter.py -c ./model/graph_ulf.txt -d ./model/dense.npz -o ./output/model_blaze -b 1
conf_file= ./model/graph_ulf.txt  data_file= ./model/dense.npz  model_type= 6  weight_type= 1  io_type= 1  x_type= {}  out_file= ./output/model_blaze  is_binary= 1
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
</pre>
core堆栈：
<pre>
(gdb) bt
#0  0x00007f02de723428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f02de72502a in __GI_abort () at abort.c:89
#2  0x00007f024ca1f84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f024ca1d6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f024ca1d701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f024ca1d919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f024ca468f5 in std::__throw_regex_error(std::regex_constants::error_type) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f024f0d5ce6 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression (this=this@entry=0x7ffd2a635000)
    at /usr/include/c++/4.8/bits/regex_compiler.h:974
#8  0x00007f024f0d5f41 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=this@entry=0x7ffd2a635000)
    at /usr/include/c++/4.8/bits/regex_compiler.h:960
#9  0x00007f024f0d67ea in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (this=this@entry=0x7ffd2a635000)
    at /usr/include/c++/4.8/bits/regex_compiler.h:795
#10 0x00007f024f0d6897 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7ffd2a635000)
    at /usr/include/c++/4.8/bits/regex_compiler.h:773
#11 0x00007f024f0d6a2d in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7ffd2a635000)
    at /usr/include/c++/4.8/bits/regex_compiler.h:758
#12 0x00007f024f0d6dc5 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler (this=0x7ffd2a635000, __b=<optimized out>, __e=<optimized out>,
    __traits=..., __flags=<optimized out>) at /usr/include/c++/4.8/bits/regex_compiler.h:729
#13 0x00007f024f0d717f in std::__detail::__compile<char const*, std::regex_traits<char> > (__b=@0x7ffd2a635240: 0x7f024f3fa239 "[0-9][0-9]*",
    __e=@0x7ffd2a635260: 0x7f024f3fa244 "", __t=..., __f=__f@entry=16) at /usr/include/c++/4.8/bits/regex_compiler.h:1105
#14 0x00007f024f0cfbfb in std::basic_regex<char, std::regex_traits<char> >::basic_regex (__f=16, __p=0x7f024f3fa239 "[0-9][0-9]*", this=0x7ffd2a635280)
    at /usr/include/c++/4.8/bits/regex.h:388
#15 cnpy::parse_npy_header (fp=fp@entry=0x1ff4860, word_size=@0x7ffd2a635440: 69, shape=std::vector of length 0, capacity 0, fortran_order=@0x7ffd2a635420: false)
    at /xdl/blaze/blaze/model_importer/cnpy/cnpy.cc:127
#16 0x00007f024f0d02b3 in load_the_npy_file (fp=fp@entry=0x1ff4860) at /xdl/blaze/blaze/model_importer/cnpy/cnpy.cc:182
#17 0x00007f024f0d0861 in cnpy::npz_load (fname="./model/dense.npz") at /xdl/blaze/blaze/model_importer/cnpy/cnpy.cc:271
#18 0x00007f024f11bf6d in blaze::TFParam::Load (file_name=0x1ff4778 "\240G\377\001", this=<optimized out>) at /xdl/blaze/blaze/model_importer/tensorflow_importer.h:37
#19 blaze::XdlULFImporter::LoadNetWeightsFromTF (this=this@entry=0x7ffd2a635b60, data_file=data_file@entry=0x7f024f7721dc "./model/dense.npz")
    at /xdl/blaze/blaze/model_importer/xdl_ulf_importer.cc:76
#20 0x00007f024f11ce84 in blaze::XdlULFImporter::LoadModel (this=this@entry=0x7ffd2a635b60, conf_file=conf_file@entry=0x7f024f76b7d4 "./model/graph_ulf.txt",
    data_file=data_file@entry=0x7f024f7721dc "./model/dense.npz") at /xdl/blaze/blaze/model_importer/xdl_ulf_importer.cc:32
#21 0x00007f024f139f17 in Blaze_ConvertBlaze (model_conf_file=0x7f024f76b7d4 "./model/graph_ulf.txt", model_data_file=0x7f024f7721dc "./model/dense.npz",
    model_type=<optimized out>, weight_type=<optimized out>, io_type=<optimized out>, x_type_num=<optimized out>, x_type_key=0x7f024f750760, x_type_value=0x7f024f7507f0,
    blaze_model_file=0x7f024f76b854 "./output/model_blaze", binary=1) at /xdl/blaze/blaze/api/c_api/c_api_blaze_converter.cc:95
#22 0x00007f02dd99fe40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#23 0x00007f02dd99f8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#24 0x00007f02ddbaf3df in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#25 0x00007f02ddbb3d82 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#26 0x00000000004c166d in PyEval_EvalFrameEx ()
#27 0x00000000004b9b66 in PyEval_EvalCodeEx ()
#28 0x00000000004c17c6 in PyEval_EvalFrameEx ()
#29 0x00000000004b9b66 in PyEval_EvalCodeEx ()
#30 0x00000000004c17c6 in PyEval_EvalFrameEx ()
#31 0x00000000004b9b66 in PyEval_EvalCodeEx ()
#32 0x00000000004eb69f in ?? ()
#33 0x00000000004e58f2 in PyRun_FileExFlags ()
#34 0x00000000004e41a6 in PyRun_SimpleFileExFlags ()
#35 0x00000000004938ce in Py_Main ()
#36 0x00007f02de70e830 in __libc_start_main (main=0x493370 <main>, argc=10, argv=0x7ffd2a636f38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffd2a636f28) at ../csu/libc-start.c:291
#37 0x0000000000493299 in _start ()
(gdb) f 15
#15 cnpy::parse_npy_header (fp=fp@entry=0x1ff4860, word_size=@0x7ffd2a635440: 69, shape=std::vector of length 0, capacity 0, fortran_order=@0x7ffd2a635420: false)
    at /xdl/blaze/blaze/model_importer/cnpy/cnpy.cc:127
warning: Source file is more recent than executable.
127         std::regex num_regex("[0-9][0-9]*");
(gdb) p str_shape
$1 = error reading variable: Cannot access memory at address 0xffffffffffffffe8
(gdb) p header
$2 = "'descr': ' f4', 'fortran_order': False, 'shape': (200,), }", ' ' （repeats 58 times）, "\n"
(gdb)  
</pre>
有些符号没有显示出来，截图补充：
![image](https://user-images.githubusercontent.com/11550277/53152687-25424000-35f1-11e9-80b9-bde124e934b6.png)

**Comment by simon1024** [comment]
自己把代码摘出来试了下，在g++-4.8上，regex有问题，换成g++-4.9之后，可以成功。

**Comment by weberxie** [comment]
同样问题

**Comment by weberxie** [comment]
@simon1024 请问你解决这个问题了吗？最后用的g++版本是？

**Comment by simon1024** [comment]
> @simon1024 请问你解决这个问题了吗？最后用的g++版本是？

g++-4.9可以解决
$ apt install g++-4.9
$ export CC=/usr/bin/gcc-4.9 && export CXX=/usr/bin/g++-4.9
