### ISSUE TITLE
请问ps-plus是在运行分布式程序时默认使用的吗？如何在ps-plus和native ps之间切换？

### ISSUE THREAD

**Issue by lxl910915** [alibaba/x-deeplearning#142]

**Comment by codewdy** [comment]
你说的native ps是指的tensorflow的ps模式么？暂时没有支持此模式的计划。

**Comment by lxl910915** [comment]
> 你说的native ps是指的tensorflow的ps模式么？暂时没有支持此模式的计划。

native ps是指的tensorflow的ps。就是现在模式就使用了ps-plus是吧？
