### ISSUE TITLE
local模式下的gqps大于分布式模式下的gqps

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#144]
local模式下的gqps：只有60~80,；分布式环境下的gqps达到150。麻烦请教下大概是什么问题呢？
以下是配置：
"worker": {
    "instance_num": 6,
    "cpu_cores": 4,
    "gpu_cores": 0,
    "memory_m": 1000000
  },
  "ps": {
    "instance_num": 3,
    "cpu_cores": 4,
    "gpu_cores": 0,
    "memory_m": 1000000
  },

**Comment by songyue1104** [comment]
根据你的描述，分布式下的qps是大于local的，分布式qps是所有worker的qps之和，所以大于单机模式是正常的

**Comment by bboy-yang** [comment]
分布模式下的gqps：只有60~80,；单机环境下的gqps达到150。不好意思，说反了
