### ISSUE TITLE
跑ps 报错

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#148]
我按照上面的文档在纯净的unbuntu docker上面按装的，成功了，但是
我跑ps里面的seastar库的测试程序报错
Segmentation fault on shard 6.
Backtrace:
  0x00000000004438ec
  0x0000000000443a10
  0x0000000000443a85
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  0x00000000004c1ba1
  0x0000000000493637
  0x0000000000499eb7
  0x00000000004ec66d
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c

**Comment by songyue1104** [comment]
请提供跑测试的命令

**Comment by songziqin** [comment]
我没有跑测试，我只是按照你们的说明，在docker ubuntu 16.04上面编译并且安装了，
然后我就进入到xdl/third_party/seastar/build/release/apps/这个目录里面有seastar的
example。 我进入了几个httpd,memcached都报同样的错误：
root@103-34-105-sh-100-D04:/tmp/x-deeplearning/xdl/third_party/seastar/build/release/apps/memcached# ./memcached -c2
WARN  2019-02-25 07:35:13,312 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-02-25 07:35:13,312 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-02-25 07:35:13,313 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
seastar memcached v1.0
Segmentation fault on shard 1.
Backtrace:
  0x00000000005994ec
  0x0000000000599610
  0x0000000000599685
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  0x00000000005ea5d3
  0x00000000005efab7
  0x000000000063b66d
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c
Segmentation fault (core dumped)

**Comment by SuperbDong** [comment]
同样的报错 求解

**Comment by xd-kevin** [comment]
+1 感觉是系统的原因

**Comment by SeekerYb** [comment]
我遇到了几乎一模一样的问题。用gdb调了一下：
