### ISSUE TITLE
The deepctr example fail

### ISSUE THREAD

**Issue by ronjian** [alibaba/x-deeplearning#15]
The deepctr example failure log as below, please help, thanks in advance.

```
root@adeb1b227a39:~/x-deeplearning/xdl/examples/deepctr# python deepctr.py
```

```
Traceback (most recent call last):
  File "deepctr.py", line 21, in <module>
    enable_state=False) # enable reader state
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/io/data_reader.py", line 67, in __init__
    rank=xdl.get_task_index(), size=xdl.get_task_num())
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/io/data_sharding.py", line 73, in partition
    assert size > 0 and rank >= 0 and rank < size
AssertionError
```

**Comment by yiling-dc** [comment]
> The deepctr example failure log as below, please help, thanks in advance.
> 
> ```
> root@adeb1b227a39:~/x-deeplearning/xdl/examples/deepctr# python deepctr.py
> ```
> ```
> Traceback (most recent call last):
>   File "deepctr.py", line 21, in <module>
>     enable_state=False) # enable reader state
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/io/data_reader.py", line 67, in __init__
>     rank=xdl.get_task_index(), size=xdl.get_task_num())
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/io/data_sharding.py", line 73, in partition
>     assert size > 0 and rank >= 0 and rank < size
> AssertionError
> ```

If you want to run the example in a local mode, you should add the parameter "--run_mode=local" in your command. Just as the wiki https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#41-%E5%8D%95%E6%9C%BA%E8%AE%AD%E7%BB%83illustrates.
