### ISSUE TITLE
blaze的优势

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#150]
请教一个问题：为什么开发blaze推理引擎？blaze除了可以转换tf，xdl，ulf格式的模型统一加载之外，还有别的收益么？

**Comment by largestone1982** [comment]
主要是为了满足线上服务性能，TDM/DIEN等模型在原生TF/Mxnet上的性能不能满足需求。

**Comment by simon1024** [comment]
> TDM/DIEN等模型在原生TF/Mxnet上的性能不能满足高吞吐低延时的性能需求。

blaze做了哪些方面的优化呢？
