### ISSUE TITLE
protobuf3.6.0 版本问题

### ISSUE THREAD

**Issue by jingcheng-WU** [alibaba/x-deeplearning#152]
目前blaze里面第三方protobuf版本是3.6.0， 但是 tensorflow 1.12.0 has requirement protobuf>=3.6.1, but you'll have protobuf 3.6.0 which is incompatible. 这有问题么？

**Comment by largestone1982** [comment]
编译的blaze库不导出protobuf符号就行, 编译请带-DSYMBOL_EXPORT_CTL=1
