### ISSUE TITLE
请问增加特征是否需要id连续？

### ISSUE THREAD

**Issue by wshexin** [alibaba/x-deeplearning#153]
1.请问增加特征是否需要id连续？
2.如何理解以及是否有实现以下功能：
ps-plus模块还支持非id化数据存储查询，流式写出增量模型的功能

**Comment by songyue1104** [comment]
1. id化特征最好连续，这样不会有空洞，从而浪费内存
2. 非id化指的是特征不必做连续编码，流式写出指的是在支持在训练过程中实时把发生变化的weight写入消息队列，一般用于online learning
