### ISSUE TITLE
关于 TDM predict 输出结果的几点疑问

### ISSUE THREAD

**Issue by ybeforev** [alibaba/x-deeplearning#156]
有一些疑问想请教：
1. 利用自己 mock 的数据替换 mock.dat 后，每增加一轮训练（train & tree_cluster）对最终 predict 出来的结果影响很大（例如第 12 轮和第 13 轮训练后进行预测得到的结果差别很大）。请问 tdm 模型和树联合训练达到稳定的判断标准是什么？
2. 虽然训练后期 loss 能降到 0.2 左右，但预测时得到的结果兴趣概率不理想，大部分 user 得到的 item 兴趣概率为 0.7 左右，可能的原因有哪些？
3. 下面是某轮次的 predict 输出结果，对有的 user 的预测结果兴趣概率很低，有的 user 的预测结果兴趣概率比较高，请问这种现象正常吗？
4. #129 中的现象依然经常出现。

标准输出：
```
... ...
#### loss:[1.7043602]
global_step = 1161
batch['_ids'] = []
hello sess.run: 45
predict result:
  global_sample_num: 6
  global_r_num: 12
  global_gt_num: 229
  global_p_num: 240
  global_r: 0.052402
  global_p: 0.050000
  avg_r: 0.222222
  avg_p: 0.050000
#### loss:[1.0154605]
global_step = 1161
batch['_ids'] = []
hello sess.run: 46
predict result:
  global_sample_num: 7
  global_r_num: 12
  global_gt_num: 268
  global_p_num: 280
  global_r: 0.044776
  global_p: 0.042857
  avg_r: 0.190476
  avg_p: 0.042857
#### loss:[2.0741568]
global_step = 1161
batch['_ids'] = [[    0 12113]]
hello sess.run: 47
predict result:
  global_sample_num: 8
  global_r_num: 49
  global_gt_num: 379
  global_p_num: 320
  global_r: 0.129288
  global_p: 0.153125
  avg_r: 0.208333
  avg_p: 0.153125
result is None, finished success.
... ...
```

结果文件：
```
... ...
64_T:**870,0.382653;**727,0.361297;13289,0.360063;1203,0.336830;6272,0.327045;
63_T:**9756,0.976402;**9757,0.963269;9744,0.950019;9882,0.943086;12100,0.938670;
... ...
```

**Comment by ybeforev** [comment]
@largestone1982 感谢

**Comment by zhuhan1236** [comment]
1. 关于收敛的标准，训练过程可以观察loss的下降情况；联合训练（train & tree cluster）可以观察得到模型的预测召回率来判断是否收敛。其中每一次tree cluster之后，需要重新train到收敛才能进行正确的预测，预测结果差异大是否是这一原因？
2. 预测结果中的(user, item)兴趣概率在0.7左右是正常的结果。需要注意训练的loss是正/负样本的均值，和预测中最终的(user, item)兴趣概率不能完全对应。
3. 是正常现象，具体单个用户的预测结果，和用户本身的行为序列相关，模型给出的预测结果中的(user, item)兴趣概率仅在同一个用户的预测结果中有大小比较的意义，不同用户间会有差异。
4. #129 的结果只在模型训练极度不充分的情况下才会出现（随机初始化的模型，对所有user, item对的打分就是0.5附近，对应loss为0.7左右），可以check一下训练的配置以及loss下降的情况等看是否正常。
