### ISSUE TITLE
UserBehavior数据集总的训练轮次大概是多少？

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#158]
-  请问[TDM文档](https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM))里提到的这个UserBehavior数据集，我们下载了，打开看是一亿条的数据，有人跑过么？大概一共需要多少轮次的训练能够使用？

> 文档内容说明
> 本文旨在介绍TDM以及如何使用TDM开源项目进行实际业务生产所用，阅读完成后，你可以了解到：
> 
> TDM的基本系统组成
> TDM开源代码的运行和使用
> 应用TDM到具体实践的方法
> 受限于篇幅以及主旨，以下内容本文不涉及，或请参阅相关文档：
> 
> XDL训练平台的系统组成和使用。
> 公开数据集(UserBehavior)的下载、使用和授权。

**Comment by canglingye** [comment]
一般来说，需要训练4个epoch。
