### ISSUE TITLE
分布式模式相比单机模式难以收敛

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#159]
问题描述：分布式配置20个woker，8个ps，发现迭代80万step，test auc仍然只有0.5左右。而单机模式迭代不到1万step，test auc就达到0.68。1，想问下，xdl分布式是默认异步更新策略吗？2、为何会出现上述分布式难以收敛的情况？

**Comment by bboy-yang** [comment]
更新一下，分布式配置10跟个worker，4个ps，收敛正常。这是因为ps设置过多，导致异步更新时波动太多吗？

**Comment by sudongxiang** [comment]
个人建议，不要用异步模式（why？因为效果差）。我一直在用同步模式，手链很稳定。

**Comment by githcx** [comment]
> 个人建议，不要用异步模式（why？因为效果差）。我一直在用同步模式，收敛很稳定。

问个同步模式的问题：我们1个scheduler，1个ps，2个worker进行分布式训练，其中1个worker执行很少的session（大约10个session左右）就退出，最后显示result is none。另外一个worker看似正常执行，一直到最后有结果才退出（700+session），查看hdfs上的item embedding的输出目录和checkpoint目录，均有结果。请问这种现象在同步模式下是否正常？谢谢。
