### ISSUE TITLE
ps-plus 这个组件可以单独摘出来使用吗?

### ISSUE THREAD

**Issue by witgo** [alibaba/x-deeplearning#16]
就像zookeeper于hadoop一样,ps-plus 这个组件的用途应该更加广泛.

**Comment by guoxinyang** [comment]
是的，ps-plus模块本质是一个高性能parameter server，可以单独抽出来使用。

**Comment by guoxinyang** [comment]
很好的建议，不过目前项目组人手有限，后续会根据用户需求和项目人力决定是否进行这部分工作。

**Comment by shanshanpt** [comment]
@witgo The simple example of ps-plus : 
https://github.com/alibaba/x-deeplearning/blob/master/xdl/ps-plus/README.md

**Comment by witgo** [comment]
@shanshanpt  thx.
