### ISSUE TITLE
TDM dummy数据集训练的结果，在测试集的输出上存在item一样的问题

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#160]
TDM 1w条userbehavior的随机测试集，训练几十轮后用train.py跑predict输出预测结果，测试集采用10个用户，每个用户的Top20的item基本完全一样，只存在次序和概率的差别，请问是否正常？

**Comment by zhuhan1236** [comment]
这个现象和 #129 非常类似，应该是训练不充分导致的。UserBehavior数据集由于id量比较大，迭代轮数不够的情况下，可能只有小部分的热门id参与到了训练当中，导致预测结果基本一致

**Comment by jayhejie** [comment]
请参考成员 @zhuhan1236 的回答

**Comment by githcx** [comment]
> 这个现象和 #129 非常类似，应该是训练不充分导致的。UserBehavior数据集由于id量比较大，迭代轮数不够的情况下，可能只有小部分的热门id参与到了训练当中，导致预测结果基本一致

(1) 一共已经训练了几十轮(一轮迭代是执行train.py后再执行tree_cluster.py)，还是迭代轮数的问题么？
(2) 如何调整参数重新训练，可以达到@zhuhan1236 所说的“足够的迭代轮数”，谢谢？

**Comment by zhuhan1236** [comment]
> > 这个现象和 #129 非常类似，应该是训练不充分导致的。UserBehavior数据集由于id量比较大，迭代轮数不够的情况下，可能只有小部分的热门id参与到了训练当中，导致预测结果基本一致
> 
> (1) 一共已经训练了几十轮(一轮迭代是执行train.py后再执行tree_cluster.py)，还是迭代轮数的问题么？
> (2) 如何调整参数重新训练，可以达到@zhuhan1236 所说的“足够的迭代轮数”，谢谢？

能提供你的训练loss、预测打分结果么？从你描述的现象来看肯定是不合理的，但是不知道问题在哪。在单轮训练中（不进行tree_cluster时），大概全量数据过几个epoch后，基本上就收敛了。训练轮数可以通过tdm.json里的train_epochs来调整

**Comment by githcx** [comment]
> > > 这个现象和 #129 非常类似，应该是训练不充分导致的。UserBehavior数据集由于id量比较大，迭代轮数不够的情况下，可能只有小部分的热门id参与到了训练当中，导致预测结果基本一致
> > 
> > 
> > (1) 一共已经训练了几十轮(一轮迭代是执行train.py后再执行tree_cluster.py)，还是迭代轮数的问题么？
> > (2) 如何调整参数重新训练，可以达到@zhuhan1236 所说的“足够的迭代轮数”，谢谢？
> 
> 能提供你的训练loss、预测打分结果么？从你描述的现象来看肯定是不合理的，但是不知道问题在哪。在单轮训练中（不进行tree_cluster时），大概全量数据过几个epoch后，基本上就收敛了。训练轮数可以通过tdm.json里的train_epochs来调整

训练loss在最后一个session后输出介于0.2-0.3，预测打分在0.5附近，关于收敛，从loss最低值能否判断是否收敛呢？

**Comment by zhuhan1236** [comment]
> > > > 这个现象和 #129 非常类似，应该是训练不充分导致的。UserBehavior数据集由于id量比较大，迭代轮数不够的情况下，可能只有小部分的热门id参与到了训练当中，导致预测结果基本一致
> > > 
> > > 
> > > (1) 一共已经训练了几十轮(一轮迭代是执行train.py后再执行tree_cluster.py)，还是迭代轮数的问题么？
> > > (2) 如何调整参数重新训练，可以达到@zhuhan1236 所说的“足够的迭代轮数”，谢谢？
> > 
> > 
> > 能提供你的训练loss、预测打分结果么？从你描述的现象来看肯定是不合理的，但是不知道问题在哪。在单轮训练中（不进行tree_cluster时），大概全量数据过几个epoch后，基本上就收敛了。训练轮数可以通过tdm.json里的train_epochs来调整
> 
> 训练loss在最后一个session后输出介于0.2-0.3，预测打分在0.5附近，关于收敛，从loss最低值能否判断是否收敛呢？

从预测打分来看，模型应该是没有收敛的，因为随机模型的预测打分就是0.5附近；另外，关于training的loss值，随机初始化的loss大概是0.7左右，根据负采样比例的不同，收敛时的loss值也会不同，但是0.2-0.3的loss值确实太大了，按照默认配置的话，0.03左右的收敛loss算是合理范围
