### ISSUE TITLE
请问下 特征组 是个什么概念? #TDM

### ISSUE THREAD

**Issue by guotong1988** [alibaba/x-deeplearning#162]
![image](https://user-images.githubusercontent.com/4702353/53627197-cad55f00-3c42-11e9-8fc9-6a9a22116a19.png)

**Comment by canglingye** [comment]
在将用户特征划分为特征组后，在训练的过程中可以对整个特征组直接进行操作，比如Max\Sum\Avg pooling等。
当特征组大小为1时，即等价于用户的单个行为特征。
