### ISSUE TITLE
TDM的中tdmop_layer_counts是什么参数？

### ISSUE THREAD

**Issue by CyanSong** [alibaba/x-deeplearning#171]
文件的默认值是这个，不理解这是什么参数
`    "tdmop_layer_counts": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,19,22,25,30,76,200",`
在dummy单机数据集的教程中，需要修改，不知道这个参数具体是什么用途，烦请指点，谢谢！

**Comment by canglingye** [comment]
tdmop_layer_counts参数是用于控制在树上每层的负采样数量。
比如最后的200，则表示在叶子层需要负采样200个节点。

**Comment by mengyiliu22** [comment]
维度都是23，是指树最终有23层？层数应该和数据量大小相关吧，使用自定义语料时，这个参数该怎么设置呢

**Comment by CyanSong** [comment]
> 维度都是23，是指树最终有23层？层数应该和数据量大小相关吧，使用自定义语料时，这个参数该怎么设置呢
树的实际层数是由样本量决定的，基本上是log2（样本量）+1。如果树不超过23层就用默认值就好，代码会自己取对应的前n层（n=树层数）。

**Comment by mengyiliu22** [comment]
> 维度都是23，是指树最终有23层？层数应该和数据量大小相关吧，使用自定义语料时，这个参数该怎么设置呢
> 树的实际层数是由样本量决定的，基本上是log2（样本量）+1。如果树不超过23层就用默认值就好，代码会自己取对应的前n层（n=树层数）。

👍 我想看看这部分代码在哪里实现的，还没找到对应代码

**Comment by CyanSong** [comment]
> > 维度都是23，是指树最终有23层？层数应该和数据量大小相关吧，使用自定义语料时，这个参数该怎么设置呢
> > 树的实际层数是由样本量决定的，基本上是log2（样本量）+1。如果树不超过23层就用默认值就好，代码会自己取对应的前n层（n=树层数）。
> 
> 👍 我想看看这部分代码在哪里实现的，还没找到对应代码

train.py detaio调用了tdmop时，（通过两个so文件）运行了tdmop.cc里面的run函数，里面把原先的样本进行正负采样，生成新的训练样本集。
具体的正负采样操作在layerwise_selector.cc的select函数中完成的。
