### ISSUE TITLE
怎么实现多个特征组用同一个embedding

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#172]
我有多个特征组，需要用同一个embedding。但是xdl把emb variable的创建放到了embedding的实现内部，所以没法复用同一个embedding；而如果把多个特征组合成一个特征组去查embedding，又会被combine。对于这种需求，在xdl里应该怎么实现呢？

**Comment by songyue1104** [comment]
xdl.embedding接口的name参数配成同一个

**Comment by simon1024** [comment]
> xdl.embedding接口的name参数配成同一个

试了不行，内部会创建两个不同的variable，分别为 name和name_1

**Comment by songyue1104** [comment]
会有两个不同的xdl variable，但都指向同一个ps参数

**Comment by simon1024** [comment]
> 会有两个不同的xdl variable，但都指向同一个ps参数

你是说variable name和name_1指向的是同一个内存空间？这个和tf的处理不一样，在tf里是通过shared_name来控制的，那么xdl里是怎么做的？

**Comment by simon1024** [comment]
> 会有两个不同的xdl variable，但都指向同一个ps参数

我可以理解为，创建variable的时候，只要指定同样的名字，那么就会指向相同的ps参数么？

**Comment by lovickie** [comment]
是的，特征同空间的实现方式就是将xdl.embedding接口的name参数配成同一个
可以参考开源TDM

**Comment by simon1024** [comment]
> 是的，特征同空间的实现方式就是将xdl.embedding接口的name参数配成同一个
> 可以参考开源TDM

好的，谢谢
