### ISSUE TITLE
TDM的实现中好像并不能保证父节点和子节点的p(n|u)值关系

### ISSUE THREAD

**Issue by CyanSong** [alibaba/x-deeplearning#174]
论文中阐述了TDM树结构的索引结构，满足下面的数学关系
![](https://latex.codecogs.com/gif.latex?p^j(n|u)=\frac{\max\limits_{n_c&space;\in&space;\{n's\&space;children\&space;nodes\&space;in\&space;level\&space;j&plus;1\}}p^{j&plus;1}(n_c|u)}{\alpha^j}
)
这也是算法能够得到全局最优的保障。
但貌似实现的过程中，子节点和父节点的P值基本上独立，取决于DNN的输出，完全不能保障这个关系。
难道是训练生成样本的时候，能够保证其期望值满足上述关系么？好像也没法保证。
对TDM算法理论上的有效性表示怀疑。

**Comment by zhuhan1236** [comment]
> 论文中阐述了TDM树结构的索引结构，满足下面的数学关系
> ![](https://camo.githubusercontent.com/08599399e519483c249d627ece3154db0dfee40c/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f702535456a286e25374375293d253543667261632537422535436d61782535436c696d6974735f2537426e5f632673706163653b253543696e2673706163653b2537426e27732673706163653b6368696c6472656e2673706163653b6e6f6465732673706163653b696e2673706163653b6c6576656c2673706163653b6a2b31253744253744702535452537426a2b31253744286e5f632537437529253744253742253543616c7068612535456a253744)
> 这也是算法能够得到全局最优的保障。
> 但貌似实现的过程中，子节点和父节点的P值基本上独立，取决于DNN的输出，完全不能保障这个关系。
> 难道是训练生成样本的时候，能够保证其期望值满足上述关系么？好像也没法保证。
> 对TDM算法理论上的有效性表示怀疑。

最大堆兴趣树是我们为了解决TopK推荐匹配问题提出的一个方法论概念，它是完成最优TopK召回的充分但非必要条件。在论文中我们有提到，在训练每层的兴趣模型时，我们并没有直接显式地使用最大堆兴趣概率来对模型进行监督或约束，而是基于兴趣最大堆建模，首先生成了一系列满足最大堆性质的训练样本，然后通过训练模型来拟合样本的方式，保证了上下层兴趣序关系的传递。
