### ISSUE TITLE
分布式predict问题

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#175]
请教各位：发现restore checkpoint的时候，ps报错如下，但是我明明看看checkpoint中生成了ckpt-................3001/tf_model$dense_2$bias^0，为啥还说not found呢？

E0313 02:53:18.310192    86 checkpoint_utils.cc:64] Not found variable[tf_model/dense_2/bias] part[0] in variable_infos when load variable.
E0313 02:53:18.310338    86 checkpoint_utils.cc:64] Not found variable[tf_model/dense_2/kernel] part[0] in variable_infos when load variable.
E0313 02:53:18.310359    86 checkpoint_utils.cc:64] Not found variable[tf_model/dense_3/bias] part[0] in variable_infos when load variable.
E0313 02:53:18.310377    86 checkpoint_utils.cc:64] Not found variable[tf_model/dense_3/kernel] part[0] in variable_infos when load variable.
E0313 02:53:18.310422    86 checkpoint_utils.cc:64] Not found variable[xdl_global_step] part[0] in variable_infos when load variable.
E0313 02:53:24.852726    87 checkpoint_utils.cc:64] Not found variable[tf_model/dense_2/bias] part[0] in variable_infos when load variable.
E0313 02:53:24.852900    87 checkpoint_utils.cc:64] Not found variable[tf_model/dense_2/kernel] part[0] in variable_infos when load variable.
E0313 02:53:24.852921    87 checkpoint_utils.cc:64] Not found variable[tf_model/dense_3/bias] part[0] in variable_infos when load variable.
E0313 02:53:24.852936    87 checkpoint_utils.cc:64] Not found variable[tf_model/dense_3/kernel] part[0] in variable_infos when load variable.
E0313 02:53:24.853018    87 checkpoint_utils.cc:64] Not found variable[xdl_global_step] part[0] in variable_infos when load variable.

**Comment by songyue1104** [comment]
请提供复现问题的方法

**Comment by bboy-yang** [comment]
提供复现的方法，可能需要数据和代码。可能我对xdl的理解有偏差，想问下，crossmedia的加载ckpt的时候，如果自己写了pyfunc的op，会导致加载模型不成功呢？

**Comment by lovickie** [comment]
如果可以正常加载ckpt的话，那么这个信息的打印不是错误，只是指出该server上未存放某些变量，这是划分的结果。
我们会持续优化日志内容，避免不必要的误解。
