### ISSUE TITLE
【加急】怎么实现tf.feature_column.crossed_column

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#176]
看了下wiki，可以通过dsl描述自动交叉特征，但是没有样例，不知道怎么用。
能否说明下用法。

**Comment by lovickie** [comment]
sample2.txt
```
skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
skey1|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
skey2|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
skey1|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
skey2|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
```

config.json
```
{
  "job_name": "test",
  "dependent_dirs": "",
  "script": "test_feature_op.py",
  "worker": {
    "instance_num": 2,
    "cpu_cores": 4,
    "gpu_cores": 0,
    "memory_m": 4096
  },
  "ps": {
    "instance_num": 2,
    "cpu_cores": 2,
    "gpu_cores": 0,
    "memory_m": 4096
  }
}
```

test_feature_op.py
```
import xdl

data_io = xdl.DataIO("mytest", xdl.parsers.txt, xdl.fs.local)
print data_io

data_io.batch_size(4)
data_io.epochs(1)
data_io.threads(1)
data_io.feature(name="upv14", type=xdl.features.sparse)
data_io.feature(name="ufav3", type=xdl.features.sparse, table=0)
data_io.feature(name="com", type=xdl.features.sparse, dsl="Name=com;Expr=cartesian(ufav3,upv14);Type=KV")

feature_op = xdl.GetIOP("FeatureOP")
data_io.add_op(feature_op)
feature_op.init({})    # should be after data_io.add_op(feature_op)

data_io.add_path('sample2.txt')
data_io.startup()

batch = data_io.read()
print 'finish read: batch =', batch

sess = xdl.TrainSession([])
upv14 = batch['upv14']
ufav3 = batch['ufav3']
com = batch['com']
result = sess.run([upv14.ids, upv14.values, ufav3.ids, ufav3.values, com.ids, com.values])

print 'upv14 =', result[0], result[1]
print 'ufav3 =', result[2], result[3]
print 'com =', result[4], result[5]
```

编辑以上三个文件在同一目录，然后在安装了xdl的docker中运行
```
python test_feature_op.py --run_mode=local --config=config.json
```

**Comment by simon1024** [comment]
> sample2.txt
> 
> ```
> skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
> skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
> skey1|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
> skey2|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
> skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
> skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
> skey1|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
> skey2|gkey1|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
> skey1|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000000
> skey2|gkey|ufav3@201:0.100000;upv14@101:0.100000,102:0.200000,101:0.300000|a@0.010000,0.020000,0.030000;s@0.040000|1.000000,0.000000|150000001
> ```
> config.json
> 
> ```
> {
>   "job_name": "test",
>   "dependent_dirs": "",
>   "script": "test_feature_op.py",
>   "worker": {
>     "instance_num": 2,
>     "cpu_cores": 4,
>     "gpu_cores": 0,
>     "memory_m": 4096
>   },
>   "ps": {
>     "instance_num": 2,
>     "cpu_cores": 2,
>     "gpu_cores": 0,
>     "memory_m": 4096
>   }
> }
> ```
> test_feature_op.py
> 
> ```
> import xdl
> 
> data_io = xdl.DataIO("mytest", xdl.parsers.txt, xdl.fs.local)
> print data_io
> 
> data_io.batch_size(4)
> data_io.epochs(1)
> data_io.threads(1)
> data_io.feature(name="upv14", type=xdl.features.sparse)
> data_io.feature(name="ufav3", type=xdl.features.sparse, table=0)
> data_io.feature(name="com", type=xdl.features.sparse, dsl="Name=com;Expr=cartesian(ufav3,upv14);Type=KV")
> 
> feature_op = xdl.GetIOP("FeatureOP")
> data_io.add_op(feature_op)
> feature_op.init({})    # should be after data_io.add_op(feature_op)
> 
> data_io.add_path('sample2.txt')
> data_io.startup()
> 
> batch = data_io.read()
> print 'finish read: batch =', batch
> 
> sess = xdl.TrainSession([])
> upv14 = batch['upv14']
> ufav3 = batch['ufav3']
> com = batch['com']
> result = sess.run([upv14.ids, upv14.values, ufav3.ids, ufav3.values, com.ids, com.values])
> 
> print 'upv14 =', result[0], result[1]
> print 'ufav3 =', result[2], result[3]
> print 'com =', result[4], result[5]
> ```
> 编辑以上三个文件在同一目录，然后在安装了xdl的docker中运行
> 
> ```
> python test_feature_op.py --run_mode=local --config=config.json
> ```

很详细，感谢
