### ISSUE TITLE
如何在xdl指定gpu id

### ISSUE THREAD

**Issue by beercool** [alibaba/x-deeplearning#177]
例子里面看到
 @xdl.mxnet_wrapper(is_training=is_training, device_type='gpu')
默认是0号
请问能指定是0，1，2，3号卡的某一张吗？

**Comment by yiling-dc** [comment]
在分布式训练中，不能指定特定序号的某张卡，但是xdl_submit工具提供了GPU卡隔离的功能，可以使不同的container独占自己申请的GPU资源。如果需要使用此功能，需要在官方的HADOOP上面安装一个patch，具体的安装使用方法请参考 https://github.com/alibaba/x-deeplearning/wiki/%E9%9B%86%E7%BE%A4%E9%83%A8%E7%BD%B2%E4%B8%8E%E5%88%86%E5%B8%83%E5%BC%8F%E6%8F%90%E4%BA%A4
