### ISSUE TITLE
CrossMedia图像索引id分片不均问题

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#178]
model_server_splitter.cc里面有对图像索引id按model server的size进行分片操作：
int k = (raw[i] & 1023) % server_size，
但是这样的操作会导致某个model server的索引分配不均，有的没有分配，这样会引起如下报错：
xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[tf session run failed, errormsg:In[0] is not a matrix. Instead it has shape [0]
         [[{{node user_graphfc1/MatMul}} = MatMul[T=DT_FLOAT, _output_shapes=[[?,256]], transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0, user_graphfc1/weights/read)]]
请问有是否对这个问题做防御操作呢？

**Comment by codewdy** [comment]
能提供一个可复现的代码么？
