### ISSUE TITLE
请问 TDM UserBehavior 时间窗口是如何限定为 10 个的？

### ISSUE THREAD

**Issue by ybeforev** [alibaba/x-deeplearning#179]
![image](https://user-images.githubusercontent.com/40728260/54418102-e3637000-473e-11e9-8147-229ac96f37e0.png)

论文中有提到时间窗口，请问：
1. 时间窗口的数目是由什么参数控制的？
2. 时间窗口与 tdm.json 中的配置项 seq_len 有关么？如果有，它们之间有什么联系？
3. 论文中 UserBehavior 数据集训练及评测时的参数配置是怎么样的（不做针对小数据集的修改就是吗）？

**Comment by zhuhan1236** [comment]
> ![image](https://user-images.githubusercontent.com/40728260/54418102-e3637000-473e-11e9-8147-229ac96f37e0.png)
> 
> 论文中有提到时间窗口，请问：
> 
> 1. 时间窗口的数目是由什么参数控制的？
> 2. 时间窗口与 tdm.json 中的配置项 seq_len 有关么？如果有，它们之间有什么联系？
> 3. 论文中 UserBehavior 数据集训练及评测时的参数配置是怎么样的（不做针对小数据集的修改就是吗）？

时间窗划分是在网络定义里控制的，具体参见代码 [train.py](https://github.com/alibaba/x-deeplearning/blob/master/xdl-algorithm-solution/TDM/script/tdm_ub_att_ubuntu/train.py) 的240行

seq_len表示用户行为最大长度截断，默认配置就是UB的训练及评测参数
