### ISSUE TITLE
笔记本不支持FMA指令集，tensorflow还得自己编译，蛋疼

### ISSUE THREAD

**Issue by hitflame** [alibaba/x-deeplearning#18]
tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use FMA instructions, but these aren't available on your machine.

**Comment by songyue1104** [comment]
我们会尽快给两个不带指令优化编译的镜像

**Comment by hitflame** [comment]
嗯嗯，谢谢，已经在自己编译了



hitzhaowenqiang@sina.com
 
发件人： songyue1104
发送时间： 2018-12-22 20:59
收件人： alibaba/x-deeplearning
抄送： Wenqiang Zhao; Author
主题： Re: [alibaba/x-deeplearning] 笔记本不支持FMA指令集，tensorflow还得自己编译，蛋疼 (#18)
我们会尽快给两个不带指令优化编译的镜像

**Comment by AlexanLee** [comment]
遇到同样问题，昨天编译了一晚，还是没成功，坑多啊。

**Comment by hitflame** [comment]
是呀，毕竟第一批散户



hitzhaowenqiang@sina.com
 
发件人： Alexan Bruce Lee
发送时间： 2018-12-23 11:11
收件人： alibaba/x-deeplearning
抄送： Wenqiang Zhao; Author
主题： Re: [alibaba/x-deeplearning] 笔记本不支持FMA指令集，tensorflow还得自己编译，蛋疼 (#18)
遇到同样问题，昨天编译了一晚，还是没成功，坑多啊。

**Comment by guoxinyang** [comment]
不带指令集优化的版本已经发布，我close掉这个issue了。https://github.com/alibaba/x-deeplearning/wiki/%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85#%E4%B8%8B%E8%BD%BDxdl-docker%E9%95%9C%E5%83%8F
