### ISSUE TITLE
xdl.embedding的feature_dim大约1亿时，Aneal不能分配参数了

### ISSUE THREAD

**Issue by lxl910915** [alibaba/x-deeplearning#189]
xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 10000000, vtype='hash')
xdl.embedding的feature_dim大约1亿时，报错：Cannot Placement, Too Heavy。
请问是使用方法不正确吗？

**Comment by yiling-dc** [comment]
这是内存不够了，加下PS的内存
