### ISSUE TITLE
模型热启动后再次保存ckpt出现error

### ISSUE THREAD

**Issue by beercool** [alibaba/x-deeplearning#191]
Duplicate of #126 
模型热启动后再次保存ckpt出现error
热加载模型按照wiki中的方法进行
https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#checkpoint
恢复模型参数
import xdl
saver = xdl.Saver()
checkpoint_version = "xxx"
saver.restore(version = checkpoint_version)

报错：
File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 79, in save
    execute(self.save_op(version))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
    raise ArgumentError(status.msg)
xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[Serializer should not accept nullptr
Check Status [PS2XDL::ConvertStatus(st)] at [/home/chihan.hs/gitlab/XDL-OpenSource/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]

**Comment by songyue1104** [comment]
这个问题应该已经修复了，镜像没有更新，你可以重新编译安装一下

**Comment by githcx** [comment]
> 这个问题应该已经修复了，镜像没有更新，你可以重新编译安装一下

请问git的版本SHA是多少，我这里的现象是卡死。

**Comment by guoxinyang** [comment]
> > 这个问题应该已经修复了，镜像没有更新，你可以重新编译安装一下
> 
> 请问git的版本SHA是多少，我这里的现象是卡死。

就是目前master的最新代码，你的模型是不是太大了？或者有没有简单能复现的脚本提供一下？

**Comment by githcx** [comment]
> > > 这个问题应该已经修复了，镜像没有更新，你可以重新编译安装一下
> > 
> > 
> > 请问git的版本SHA是多少，我这里的现象是卡死。
> 
> 就是目前master的最新代码，你的模型是不是太大了？或者有没有简单能复现的脚本提供一下？

模型只有几十M，不算大。
另外，采用截止目前的次新版 77e5fb1，TDM 跑 train.py 脚本，卡在第一次保存checkpoint的地方，原因不明，所以更新版本后，异常还更多了。

**Comment by githcx** [comment]
经过加Log编译运行，发现崩溃处在文件
xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
的SaveTensor函数中，不调用restore做热恢复时，initializer不为NULL，否则为NULL，导致后续逻辑崩溃。
![image](https://user-images.githubusercontent.com/2312126/54985271-788e2080-4feb-11e9-8a53-5390373e4a62.png)

直接报错位置如下图所示(文件xdl/ps-plus/ps-plus/common/serializer.h)：
![image](https://user-images.githubusercontent.com/2312126/54985509-e0446b80-4feb-11e9-8adc-d57a6b88f70d.png)

**Comment by githcx** [comment]
> 这个问题应该已经修复了，镜像没有更新，你可以重新编译安装一下

最新版中这个问题没有修复，截图如下
![image](https://user-images.githubusercontent.com/2312126/55063289-9ffbf080-50b2-11e9-8ee5-284e5658a664.png)

调用的方式如下所示，请问是否正确无误：
![image](https://user-images.githubusercontent.com/2312126/55063389-d8033380-50b2-11e9-820b-f1310ffc2c27.png)

**Comment by githcx** [comment]
> Duplicate of #126
> 模型热启动后再次保存ckpt出现error
> 热加载模型按照wiki中的方法进行
> https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#checkpoint
> 恢复模型参数
> import xdl
> saver = xdl.Saver()
> checkpoint_version = "xxx"
> saver.restore(version = checkpoint_version)
> 
> 报错：
> File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 79, in save
> execute(self.save_op(version))
> File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
> return current_graph().execute(outputs, run_option, run_statistic)
> File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
> check_error(result.status)
> File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
> raise ArgumentError(status.msg)
> xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[Serializer should not accept nullptr
> Check Status [PS2XDL::ConvertStatus(st)] at [/home/chihan.hs/gitlab/XDL-OpenSource/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]

@beercool  做了以下修改并重新编译安装xdl后，checkpoint保存的异常消失，可以试试。
请 @songyue1104  确认下修改是否正确无误，如果没问题，可以做下fix。

版本：1cc89d6
文件：https://github.com/alibaba/x-deeplearning/blob/master/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
函数：MergeLoadVariable
行号：279行

修改diff：
```
diff --git a/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc b/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
index f9ffc5c..187325a 100644
--- a/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
+++ b/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
@@ -276,6 +276,7 @@ Status CheckpointUtils::MergeLoadVariable(const std::string& var_name, const Var
                       memcpy((void*)target + (ids[ki]*slice_size), (void*)source + (item_ids[ki]*slice_size), slice_size);
                   } while(0));
           for (auto& slot : var->slots) {
+            if (slot.second.tensor->Shape().IsScalar()) continue;
             size_t ssize = SizeOfType(slot.second.tensor->Type()) * slot.second.tensor->Shape().NumElements() / slot.second.tensor->Shape()[0];
             CASES(slot.second.tensor->Type(), do {
                         T* target = slot.second.tensor->Raw<T>();
```

**Comment by beercool** [comment]
> > Duplicate of #126
> > 模型热启动后再次保存ckpt出现error
> > 热加载模型按照wiki中的方法进行
> > https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#checkpoint
> > 恢复模型参数
> > import xdl
> > saver = xdl.Saver()
> > checkpoint_version = "xxx"
> > saver.restore(version = checkpoint_version)
> > 报错：
> > File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 79, in save
> > execute(self.save_op(version))
> > File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
> > return current_graph().execute(outputs, run_option, run_statistic)
> > File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
> > check_error(result.status)
> > File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
> > raise ArgumentError(status.msg)
> > xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[Serializer should not accept nullptr
> > Check Status [PS2XDL::ConvertStatus(st)] at [/home/chihan.hs/gitlab/XDL-OpenSource/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]
> 
> @beercool 做了以下修改并重新编译安装xdl后，checkpoint保存的异常消失，可以试试。
> 请 @songyue1104 确认下修改是否正确无误，如果没问题，可以做下fix。
> 
> 版本：1cc89d6
> 文件：https://github.com/alibaba/x-deeplearning/blob/master/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
> 函数：MergeLoadVariable
> 行号：279行
> 
> 修改diff：
> 
> ```
> diff --git a/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc b/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
> index f9ffc5c..187325a 100644
> --- a/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
> +++ b/xdl/ps-plus/ps-plus/server/checkpoint_utils.cc
> @@ -276,6 +276,7 @@ Status CheckpointUtils::MergeLoadVariable(const std::string& var_name, const Var
>                        memcpy((void*)target + (ids[ki]*slice_size), (void*)source + (item_ids[ki]*slice_size), slice_size);
>                    } while(0));
>            for (auto& slot : var->slots) {
> +            if (slot.second.tensor->Shape().IsScalar()) continue;
>              size_t ssize = SizeOfType(slot.second.tensor->Type()) * slot.second.tensor->Shape().NumElements() / slot.second.tensor->Shape()[0];
>              CASES(slot.second.tensor->Type(), do {
>                          T* target = slot.second.tensor->Raw<T>();
> ```

亲测可用，多谢！
