### ISSUE TITLE
数据文件很多的时候，开始训练前会卡一阵

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#192]
在数据量比较大的时候，发现worker在训练之前总是会卡一阵，没有任何日志，不知道在做什么。卡住的时间达到了10几甚至20分钟。

文件数量：8000个hdfs文件，每个文件8万样本
worker数量：48
batch：2048

为什么会这样呢？看代码，worker在读取数据之前，会先获取所有数据的meta信息，但应该耗时也没有这么长。

**Comment by songyue1104** [comment]
应该是在获取meta，可以把文件调小验证一下，如果是这个问题可以改成读之前取meta

**Comment by woso** [comment]
还有个问题，现在每个文件开始前会查一下大小，如果是hdfs，每个文件查一下大小还是挺慢的，后面的版本会改成读文件之前再查大小

**Comment by simon1024** [comment]
> 还有个问题，现在每个文件开始前会查一下大小，如果是hdfs，每个文件查一下大小还是挺慢的，后面的版本会改成读文件之前再查大小

是的，我说的获取meta就是指这个地方，期待新版优化
