### ISSUE TITLE
xdl saver笔误，引起checkpoint保存异常

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#193]
最新版本 commit 24637dc
文件 x-deeplearning/xdl/xdl/python/training/saver.py中有如下笔误，导致TDM脚本保存checkpoint报错，可以修改一下。
![image](https://user-images.githubusercontent.com/2312126/55069720-a93f8a00-50bf-11e9-9348-8ce1919d486a.png)

**Comment by songyue1104** [comment]
谢谢，已经修复
