### ISSUE TITLE
xdl支持字符串类型的特征么

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#197]
如题

**Comment by songyue1104** [comment]
xdl目前支持hash128的特征，后面的版本会添加hash64的支持，字符串需要先hash成128再送进xdl训练

**Comment by simon1024** [comment]
> xdl目前支持hash128的特征，后面的版本会添加hash64的支持，字符串需要先hash成128再送进xdl训练

好的，多谢
