### ISSUE TITLE
我这边执行docker里面的din例子，为啥提示错误

### ISSUE THREAD

**Issue by dotcool** [alibaba/x-deeplearning#199]
root@cc-1:/home/xxx/DIN/script# python train.py --run_mode=local --config=config.train.json
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from model import *
  File "/home/xxx/DIN/script/model.py", line 6, in <module>
    from rnn import dynamic_rnn
  File "/home/xxx/DIN/script/rnn.py", line 45, in <module>
    _like_rnncell = rnn_cell_impl._like_rnncell
AttributeError: 'module' object has no attribute '_like_rnncell'

提示这个错误，我是通过docker来安装的

**Comment by songyue1104** [comment]
看起来像是tf的版本不对，你重新装了tf？

**Comment by dotcool** [comment]
@songyue1104 ，没有重装呢，就用的你们提供的cpu版本的docker镜像，tf版本是1.12.0

**Comment by dotcool** [comment]
@songyue1104  ,使用的就是这个官方的docker版本 

docker pull registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-cpu-tf1.12

![image](https://user-images.githubusercontent.com/6111056/55453876-4181c580-5610-11e9-8559-654f9c587621.png)

**Comment by githcx** [comment]
> root@cc-1:/home/xxx/DIN/script# python train.py --run_mode=local --config=config.train.json
> Traceback (most recent call last):
> File "train.py", line 4, in 
> from model import *
> File "/home/xxx/DIN/script/model.py", line 6, in 
> from rnn import dynamic_rnn
> File "/home/xxx/DIN/script/rnn.py", line 45, in 
> _like_rnncell = rnn_cell_impl._like_rnncell
> AttributeError: 'module' object has no attribute '_like_rnncell'
> 
> 提示这个错误，我是通过docker来安装的

看起来可以在官方docker里面的路径下 /usr/local/lib/python2.7/dist-packages/
看看 tensorflow 安装的egg目录下面执行下 grep -rn _like_rnncell ，看看报错的属性是否真的不存在，排除tf安装的问题。
