### ISSUE TITLE
xdl的data io，read出来的batch，数量不够batchsize是会全补零么？

### ISSUE THREAD

**Issue by CyanSong** [alibaba/x-deeplearning#203]
在TDM代码中看到一段逻辑：
正常label两列加和必为1，补全的label为0，故减一之后即可得到-1，作为ignore label。
观察到正常的从tdmop中构造的label必定和为1，那补全的label是来自哪里的？是当样本最后，不够batchsize，read出的batch会补0么？

**Comment by changdq** [comment]
数量不够的batch会全补0。出现补0有两种情况：1. 在组batch的时间限制内样本没充满 2. 一个epoch结束后不足一个batch的样本会补0.
