### ISSUE TITLE
TDM分布式训练中 scheduler 在save checkpoint时hdfsOpenFile调用报错

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#206]
启动scheduler后，ps也连接scheduler成功，然后启动一个worker开始分布式训练

worker成功的跑了10个session，由于设置的checkpoint的保存间隔是10个session，所以触发save的操作，客户端抛出错误
![image](https://user-images.githubusercontent.com/2312126/55781510-e272f380-5adc-11e9-9cd7-a1cc6a840397.png)

然后查看scheduler，有如下的报错
![save_ckpt](https://user-images.githubusercontent.com/2312126/55781356-8ad48800-5adc-11e9-957c-7c9e8367ff90.png)

根据报错的行号，查看了scheduler_impl.cc报错位置，最终定位到是如下位置的调用失败
![image](https://user-images.githubusercontent.com/2312126/55781674-52817980-5add-11e9-9455-7ded86851806.png)
最终追溯到file_system_hdfs.cc中的如下调用失败
![image](https://user-images.githubusercontent.com/2312126/55781833-9eccb980-5add-11e9-88ff-a3a837a641a9.png)

其中，报错的调用语句实际上调用的是hdfs动态链接库libhdfs.so中定义的文件打开操作
hdfs_->hdfsOpenFile(fs, name.c_str(), O_WRONLY, 0, 0, 0);
创建checkpoint的hdfs路径是存在的（/user/tdm_mock_train/checkpoint/）且权限都已经改为777
，如下图所示
![image](https://user-images.githubusercontent.com/2312126/55782098-303c2b80-5ade-11e9-9028-a903c1b4b968.png)

初步判断，1）hdfs配置或者 2）libhdfs api调用问题导致调用失败。
为了排除原因 2），写了一个c++调用libhdfs的简单例子，里面加入了hdfsConnect和hdfsOpenFile的调用，执行后，连接hdfs正常，但是打开文件的时候抛出以下异常
![image](https://user-images.githubusercontent.com/2312126/55782552-1e0ebd00-5adf-11e9-8c7a-6984d7b99918.png)
可以看出，这个例子调用libhdfs的api的报错和scheduler保存checkpoint时打开文件的报错有区别，并非完全一致，不能简单归为相同的原因。

请问能否根据所有上述给出的信息，判断究竟是1）hdfs配置 还是 2）libhdfs api调用导致了scheduler的保存异常？

**Comment by githcx** [comment]
已解决，CLASSPATH中hdfs-client相关的jar包顺序导致的兼容性问题，全都放到CLASSPATH开始的位置即可解决。

**Comment by lazy2panda** [comment]
> 已解决，CLASSPATH中hdfs-client相关的jar包顺序导致的兼容性问题，全都放到CLASSPATH开始的位置即可解决。

请问是哪些jar包呢？我把文件名带hdfs的jar包都放在前面了，还是一样的错误
