### ISSUE TITLE
TDM分布式训练手动启动任务，两个worker跑的session数目相差较大

### ISSUE THREAD

**Issue by UanonymousU** [alibaba/x-deeplearning#207]
起了一个ps，两个worker。手工启动worker时尽量保证同时启动，在两个worker上的输出结果如下，请问是否正常？

worker0
```
>>>>>>>>>>>> 0>>>>>>>>>>>
#### loss:[0.69678086]
#### loss:[0.70211625]
#### loss:[0.6084697]
#### loss:[0.6059632]
#### loss:[0.5847815]
#### loss:[0.58311415]
#### loss:[0.5368748]
#### loss:[0.51202357]
save checkpoint at global_step[10], ckptversion[ckpt-..................10]
#### loss:[0.5089955]
#### loss:[0.5038289]
#### loss:[0.5040285]
#### loss:[0.51401836]
#### loss:[0.5197581]
save checkpoint at global_step[20], ckptversion[ckpt-..................20]
#### loss:[0.5243595]
#### loss:[0.5309426]
#### loss:[0.543803]
#### loss:[0.5425523]
#### loss:[0.5447689]
save checkpoint at global_step[30], ckptversion[ckpt-..................30]
#### loss:[0.5402058]
#### loss:[0.5442697]
#### loss:[0.54829115]
#### loss:[0.5440236]
#### loss:[0.5548794]
#### loss:[0.54756856]
#### loss:[0.5482015]
#### loss:[0.5468473]
save checkpoint at global_step[40], ckptversion[ckpt-..................40]
#### loss:[0.5426669]
#### loss:[0.55101967]
#### loss:[0.5463644]
#### loss:[0.542059]
#### loss:[0.5294114]
#### loss:[0.531877]
#### loss:[0.51974535]
#### loss:[0.5206749]
#### loss:[0.5072326]
#### loss:[0.51375073]
save checkpoint at global_step[50], ckptversion[ckpt-..................50]
#### loss:[0.508865]
#### loss:[0.502143]
#### loss:[0.504248]
#### loss:[0.50432223]
#### loss:[0.49636436]
#### loss:[0.50494796]
#### loss:[0.50348943]
#### loss:[0.5000756]
#### loss:[0.50311947]
#### loss:[0.49959338]
save checkpoint at global_step[60], ckptversion[ckpt-..................60]
#### loss:[0.4987596]
#### loss:[0.49881828]
#### loss:[0.4967595]
#### loss:[0.4942485]
#### loss:[0.49733713]
#### loss:[0.4973833]
#### loss:[0.4992534]
#### loss:[0.49411198]
#### loss:[0.4946048]
#### loss:[0.49817136]
save checkpoint at global_step[70], ckptversion[ckpt-..................70]
#### loss:[0.49333847]
#### loss:[0.49596402]
#### loss:[0.4951939]
#### loss:[0.48920688]
#### loss:[0.48998046]
#### loss:[0.49253118]
#### loss:[0.49196905]
#### loss:[0.49100846]
#### loss:[0.48727894]
#### loss:[0.4899543]
save checkpoint at global_step[80], ckptversion[ckpt-..................80]
#### loss:[0.49514937]
#### loss:[0.48585927]
#### loss:[0.48511368]
result is None, finished success.
start put item_emb
```

worker1
```
>>>>>>>>>>>> 0>>>>>>>>>>>
#### loss:[0.57077694]
#### loss:[0.49612015]
#### loss:[0.44642013]
#### loss:[0.4131964]
#### loss:[0.3931611]
#### loss:[0.37938032]
#### loss:[0.37230265]
#### loss:[0.3679174]
#### loss:[0.36620474]
#### loss:[0.36556318]
#### loss:[0.3674891]
#### loss:[0.36637244]
#### loss:[0.8913373]
result is None, finished success.
```

train.py中sharding将数据等分，所以预期输出应该是两个worker跑大体相同数目的session才对？而这里worker0跑的session数目远多于worker1。

**Comment by UanonymousU** [comment]
@songyue1104 @largestone1982 @shanshanpt 希望能解答一下，不知道这是否是正常情况。

**Comment by yiling-dc** [comment]
> @songyue1104 @largestone1982 @shanshanpt 希望能解答一下，不知道这是否是正常情况。

sharding的代码或者其他相关代码能否贴一下

**Comment by UanonymousU** [comment]
源码中 sharding 部分 segments % index，这里修改了一下，没用 sharding 不知道是否有影响：

![image](https://user-images.githubusercontent.com/49020720/56022563-91623a00-5d3e-11e9-8a47-c125f7ccfe06.png)

**Comment by yiling-dc** [comment]
> 源码中 sharding 部分 segments % index，这里修改了一下，没用 sharding 不知道是否有影响：
> 
> ![image](https://user-images.githubusercontent.com/49020720/56022563-91623a00-5d3e-11e9-8a47-c125f7ccfe06.png)

你这段代码的意思是，编号从1~400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1~400结尾的文件，一共有多少个文件？

**Comment by yiling-dc** [comment]
你这段代码的意思是，编号从1400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1400结尾的文件，一共有多少个文件？

**Comment by UanonymousU** [comment]
> 你这段代码的意思是，编号从1400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1400结尾的文件，一共有多少个文件？

一共 400 个文件，tdm.json 中的配置的，未做更改。

**Comment by yiling-dc** [comment]
> > 你这段代码的意思是，编号从1400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1400结尾的文件，一共有多少个文件？
> 
> 一共 400 个文件，tdm.json 中的配置的，未做更改。

这400个文件是如何产出的，大小是否相差很大

**Comment by UanonymousU** [comment]
1. 这些文件通过 tree_init.py 生成，里面好像有均分样本机制
2. 实际分到两个 worker 上的样本数目分别为：
    - worker0 3294
    - worker1 3463
是否是因为用的原始的随机数据 mock.dat 导致样本数目不够大？

**Comment by woso** [comment]
> > > > 你这段代码的意思是，编号从1400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1400结尾的文件，一共有多少个文件？
> > > 
> > > 
> > > 一共 400 个文件，tdm.json 中的配置的，未做更改。
> > 
> > 
> > 这400个文件是如何产出的，大小是否相差很大
> 
> 1. 这些文件通过 tree_init.py 生成，里面好像有均分样本机制
> 2. 实际分到两个 worker 上的样本数目分别为：
>    
>    * worker0 3294
>    * worker1 3463
> 
> 是否是因为用的原始的随机数据 mock.dat 导致样本数目不够大？

是400个文件一共只有6千条样本吗？

**Comment by woso** [comment]
> > > > > 你这段代码的意思是，编号从1400结尾的文件，偶数编号的都分配到worker0，奇数编号的都分配到worker1，那你这些编码从1400结尾的文件，一共有多少个文件？
> > > > 
> > > > 
> > > > 一共 400 个文件，tdm.json 中的配置的，未做更改。
> > > 
> > > 
> > > 这400个文件是如何产出的，大小是否相差很大
> > 
> > 
> > 
> > 1. 这些文件通过 tree_init.py 生成，里面好像有均分样本机制
> > 2. 实际分到两个 worker 上的样本数目分别为：
> >    
> >    * worker0 3294
> >    * worker1 3463
> > 
> > 是否是因为用的原始的随机数据 mock.dat 导致样本数目不够大？
> 
> 是400个文件一共只有6千条样本吗？

batch size多少? 跑几个epoch?

**Comment by UanonymousU** [comment]
感谢，是 batch size 未修改导致的，修改为 50 后，出现如下情况：worker0 执行完 put item_embed，而worker1 仍在跑 session 。

这样的话，请问 worker1 后续跑 session 对 embedding 的更新如何体现到 item_embed 中呢？

**Comment by woso** [comment]
> 感谢，是 batch size 未修改导致的，修改为 50 后，出现如下情况：worker0 执行完 put item_embed，而worker1 仍在跑 session 。
> 
> 这样的话，请问 worker1 后续跑 session 对 embedding 的更新如何体现到 item_embed 中呢？

我理解一下，你说的意思是一个worker先开始，另外一个worker开始训练的比较晚对吧？
异步训练会出现这样的情况，如果要求每次所有worker都更新，可以使用同步模式

**Comment by UanonymousU** [comment]
> > 感谢，是 batch size 未修改导致的，修改为 50 后，出现如下情况：worker0 执行完 put item_embed，而worker1 仍在跑 session 。
> > 这样的话，请问 worker1 后续跑 session 对 embedding 的更新如何体现到 item_embed 中呢？
> 
> 我理解一下，你说的意思是一个worker先开始，另外一个worker开始训练的比较晚对吧？
> 异步训练会出现这样的情况，如果要求每次所有worker都更新，可以使用同步模式

1. 两个 worker 手工启动，启动时间相差几秒
2. 目前使用的已经是同步训练模式，tdm.json 里面配置如下所示：

    **"train_mode": "sync",**

**Comment by UanonymousU** [comment]
考虑到可能是否是数据量太小的缘故，因此搭建了 #207 中的多机训练环境（截取 ub 数据集中的 120w 条数据）。出现以下情况：

1. 训练时损失不下降
2. worker0 执行完 put item_embed 后，其他 worker 仍旧在跑 session（持续时间达 3h）

感觉自己哪里弄错了，现象不符合预期。

**Comment by cuisonghui** [comment]
@UanonymousU 想和你请教下TDM分布式训练的问题。有遇见过scheduler异常退出的情况吗,token不一致，我把train.py中的
### xdl.execute(xdl.ps_synchronize_leave_op(np.array(xdl.get_task_index(), dtype=np.int32)))
注释掉就好了，但是会不会影响训练结果，目前不确定。
有联系方式吗，向你请教下
