### ISSUE TITLE
TDM 是否可以不用考虑用户的timestamp

### ISSUE THREAD

**Issue by whyoneisall** [alibaba/x-deeplearning#210]
您好，刚入门的小菜鸟，咨询一下，当不知道用户的ts的时候，可以使用TDM模型么？如果用的话，是直接将数据集的ts直接全部置为0？因为有些数据集时没有考虑时间因素的，希望大佬能指导一下，感谢！

**Comment by zhuhan1236** [comment]
> 您好，刚入门的小菜鸟，咨询一下，当不知道用户的ts的时候，可以使用TDM模型么？如果用的话，是直接将数据集的ts直接全部置为0？因为有些数据集时没有考虑时间因素的，希望大佬能指导一下，感谢！

TDM目前在样本、特征构成上，采用的是类似序列建模的方式，对ts特征有依赖；对于没有ts特征的场景，直接将ts全部置0，在程序正确性上不会有问题，可以先尝试一下看看效果；但是在缺失ts特征的情况下，建议对模型的特征、样本构造进行相应的修改，来取得更好的召回效果
