### ISSUE TITLE
请问，能否解释一下从数据读取到embedding流程的处理逻辑？

### ISSUE THREAD

**Issue by qk-huang** [alibaba/x-deeplearning#214]
1、vtype | 参数类型：index/hash中index和hash分别什么含义？index可不可以理解为直接使用数据集中的id进行embedding索引，而hash是将数据集中类别特征hash后进行embedding索引？
2、reduce方法，支持sum/mean，对于reduce是将同一个特征的多个取值进行求和或取均值吗？那么如果这个特征kv形式中v有值的话，这个值是如何参与计算的呢？
3、如果能够用样例中的样本做个举例就好了

**Comment by guoxinyang** [comment]
> 1、vtype | 参数类型：index/hash中index和hash分别什么含义？index可不可以理解为直接使用数据集中的id进行embedding索引，而hash是将数据集中类别特征hash后进行embedding索引？
> 2、reduce方法，支持sum/mean，对于reduce是将同一个特征的多个取值进行求和或取均值吗？那么如果这个特征kv形式中v有值的话，这个值是如何参与计算的呢？
> 3、如果能够用样例中的样本做个举例就好了

1、index指的是输入的sparse特征进行过序列化，id是从0开始递增的，hash是我们支持的非序列化样本，每个key用一个int128表示，这个tensorflow本身是不支持的
2、目前不支持kv格式的

**Comment by snowpeakz** [comment]
@guoxinyang  请问什么场景下需要支持非序列化样本？

**Comment by lxl910915** [comment]
> > 1、vtype | 参数类型：index/hash中index和hash分别什么含义？index可不可以理解为直接使用数据集中的id进行embedding索引，而hash是将数据集中类别特征hash后进行embedding索引？
> > 2、reduce方法，支持sum/mean，对于reduce是将同一个特征的多个取值进行求和或取均值吗？那么如果这个特征kv形式中v有值的话，这个值是如何参与计算的呢？
> > 3、如果能够用样例中的样本做个举例就好了
> 
> 1、index指的是输入的sparse特征进行过序列化，id是从0开始递增的，hash是我们支持的非序列化样本，每个key用一个int128表示，这个tensorflow本身是不支持的
> 2、目前不支持kv格式的

@guoxinyang 看了这个解释还是不太明白index和hash的区别。
这个hash和tensorflow中的feature_colume中的hash有什么不一样的地方？另外，“tensorflow本身是不支持”，该怎么理解？  
谢谢！

**Comment by songyue1104** [comment]
@lxl910915   feature_column里的hash是有冲突的，因为bucket size是固定的，无法扩容，xdl里的hash是无冲突的，可以自动扩容

**Comment by lxl910915** [comment]
> @lxl910915 feature_column里的hash是有冲突的，因为bucket size是固定的，无法扩容，xdl里的hash是无冲突的，可以自动扩容

谢谢解答。 如果不做自动扩容，且允许冲突。xld的hash和feature_column的hash是一样的吗？
@songyue1104
