### ISSUE TITLE
源码编译问题

### ISSUE THREAD

**Issue by zhiweige** [alibaba/x-deeplearning#215]
请问按照wiki上的源码编译步骤，编译完tensorflow和mxnet之后，编译xdl前需要把seastar和ps-plus编译好吗？这些流程步骤在哪里能看到呢？谢谢

**Comment by SeekerYb** [comment]
我试了不需要。按照这个编译就行了：
https://github.com/alibaba/x-deeplearning/wiki/%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85
脚本里包含了编译seastar和ps-plus的步骤。
但是，如果环境依赖不满足，seastar和ps-plus会编译失败。此时整个编译脚本不会停，而是继续，后面的步骤就会报找不到seastar和ps-plus的库的问题。

**Comment by zhiweige** [comment]
感谢回答！
我之前尝试的时候，应该是seastar和ps-plus没有编译过去，所以后面遇到了找不到这两个库的问题。想请教一下seastar和ps-plus的编译是在哪一步做的呢？

**Comment by LmYjQ** [comment]
> 感谢回答！
> 我之前尝试的时候，应该是seastar和ps-plus没有编译过去，所以后面遇到了找不到这两个库的问题。想请教一下seastar和ps-plus的编译是在哪一步做的呢？

遇到了类似的问题"x-deeplearning/xdl/third_party/seastar/core/sstring.hh:37:36: fatal error: experimental/string_view: No such file or directory"，请问您解决了吗
