### ISSUE TITLE
请问有完整的使用DataReader的例子吗

### ISSUE THREAD

**Issue by SeekerYb** [alibaba/x-deeplearning#217]
按照wiki里写的，类似这种格式的数据：
```
7859345_420968_1007|user_3423487|clk_14@32490:1.0,32988:2.0;prefer@323423,32342|qscore@0.8,0.5;ad_price@33.8|0.0,1.0|1544094136
```
是怎么解析的，有例子吗？
只在这里看到用DataReader：
https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#data_io
但后面怎么用没有写。例子里也没有。

**Comment by SeekerYb** [comment]
找到例子了。

**Comment by zhhu1996** [comment]
> 找到例子了。

请问哪里有解析数据的例子？
