### ISSUE TITLE
ps连接不上scheduler

### ISSUE THREAD

**Issue by mengyiliu22** [alibaba/x-deeplearning#219]
尝试分布式训练tdm模型时候，总是不成功，感觉是没连接上ps，请问这个会是什么原因呢?

**Comment by yiling-dc** [comment]
> https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> 
> 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> 
> 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> 还请帮忙解答一下

请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上

**Comment by mengyiliu22** [comment]
> > https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> > 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> > 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> > 还请帮忙解答一下
> 
> 请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上

使用你们文档里的命令启动的， 启动了一个scheduler：
./ps -r scheduler -sp zfs://localhost:2181/scheduler  -cp . -bc false -p 8801 -sn 1 -snet 10000 -smem 10000 -sqps 100000 

手动启动的server数量是个什么概念呢？文档里没有看到启动server相关的.  还请多指教，对这一块不太了解

**Comment by yiling-dc** [comment]
> > > https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> > > 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> > > 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> > > 还请帮忙解答一下
> > 
> > 
> > 请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上
> 
> 使用你们文档里的命令启动的， 启动了一个scheduler：
> ./ps -r scheduler -sp zfs://localhost:2181/scheduler -cp . -bc false -p 8801 -sn 1 -snet 10000 -smem 10000 -sqps 100000
> 
> 手动启动的server数量是个什么概念呢？文档里没有看到启动server相关的. 还请多指教，对这一块不太了解

这条命令是指还要启动一个server，所以你还需要手动起一个server，那个readme有些笔误，我已更正。

**Comment by mengyiliu22** [comment]
> > > > https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> > > > 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> > > > 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> > > > 还请帮忙解答一下
> > > 
> > > 
> > > 请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上
> > 
> > 
> > 使用你们文档里的命令启动的， 启动了一个scheduler：
> > ./ps -r scheduler -sp zfs://localhost:2181/scheduler -cp . -bc false -p 8801 -sn 1 -snet 10000 -smem 10000 -sqps 100000
> > 手动启动的server数量是个什么概念呢？文档里没有看到启动server相关的. 还请多指教，对这一块不太了解
> 
> 这条命令是指还要启动一个server，所以你还需要手动起一个server，那个readme有些笔误，我已更正。

启动scheduler和server之后，scheduler日志如下，这个是表示已经连接上了吗？此外，启动cli的命令 ./tool -v val -sn 1 -sp zfs://localhost:2181/scheduler -a testxxx作用是什么，-a参数和-v参数的含义分别是什么？
<img width="835" alt="image" src="https://user-images.githubusercontent.com/15141419/57424789-7efaf380-724b-11e9-8718-18d12939da14.png">

**Comment by yiling-dc** [comment]
> > > > > https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> > > > > 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> > > > > 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> > > > > 还请帮忙解答一下
> > > > 
> > > > 
> > > > 请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上
> > > 
> > > 
> > > 使用你们文档里的命令启动的， 启动了一个scheduler：
> > > ./ps -r scheduler -sp zfs://localhost:2181/scheduler -cp . -bc false -p 8801 -sn 1 -snet 10000 -smem 10000 -sqps 100000
> > > 手动启动的server数量是个什么概念呢？文档里没有看到启动server相关的. 还请多指教，对这一块不太了解
> > 
> > 
> > 这条命令是指还要启动一个server，所以你还需要手动起一个server，那个readme有些笔误，我已更正。
> 
> 启动scheduler和server之后，scheduler日志如下，这个是表示已经连接上了吗？此外，启动cli的命令 ./tool -v val -sn 1 -sp zfs://localhost:2181/scheduler -a testxxx作用是什么，-a参数和-v参数的含义分别是什么？
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/15141419/57424789-7efaf380-724b-11e9-8718-18d12939da14.png">

这就是启动成功了，-v代表variable_name -a 代表action模式，可以自己看下tool下面的代码，很好理解

**Comment by mengyiliu22** [comment]
> > > > > > https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus
> > > > > > 按照这份文档教程，启动scheduler时一直打印：0508 12:06:04.452194 48907 scheduler_impl.cc:356] Waiting for 1 more servers
> > > > > > 环境是ubutun镜像里自己安装了tf后端，编译了cpu版本的xdl
> > > > > > 还请帮忙解答一下
> > > > > 
> > > > > 
> > > > > 请确认一下scheduler的启动命令里启动了多少server，跟你手动启动的server数量能否对应上
> > > > 
> > > > 
> > > > 使用你们文档里的命令启动的， 启动了一个scheduler：
> > > > ./ps -r scheduler -sp zfs://localhost:2181/scheduler -cp . -bc false -p 8801 -sn 1 -snet 10000 -smem 10000 -sqps 100000
> > > > 手动启动的server数量是个什么概念呢？文档里没有看到启动server相关的. 还请多指教，对这一块不太了解
> > > 
> > > 
> > > 这条命令是指还要启动一个server，所以你还需要手动起一个server，那个readme有些笔误，我已更正。
> > 
> > 
> > 启动scheduler和server之后，scheduler日志如下，这个是表示已经连接上了吗？此外，启动cli的命令 ./tool -v val -sn 1 -sp zfs://localhost:2181/scheduler -a testxxx作用是什么，-a参数和-v参数的含义分别是什么？
> > <img alt="image" width="835" src="https://user-images.githubusercontent.com/15141419/57424789-7efaf380-724b-11e9-8718-18d12939da14.png">
> 
> 这就是启动成功了，-v代表variable_name -a 代表action模式，可以自己看下tool下面的代码，很好理解

多谢解答，解决了困了很久的问题
