### ISSUE TITLE
online-learing没有对应的文档

### ISSUE THREAD

**Issue by DecKen** [alibaba/x-deeplearning#22]
hi, 看了公众号文章说的 [Online-Learning：大规模在线学习] 的介绍, 但是并没有看到在该项目中的文档和代码, 如果有的话, 麻烦告知下.

**Comment by guoxinyang** [comment]
谢谢关注，目前代码是支持对Kafka的读写，文档后续会补上

**Comment by DecKen** [comment]
我好奇的是Online-Learning这一块 实时特征频控和过期特征淘汰这两者是如何实现的?  这一块后续也会开源出来吗?

> 谢谢关注，目前代码是支持对Kafka的读写，文档后续会补上

**Comment by guoxinyang** [comment]
@DecKen 代码已经开放出来了，实时特征频控目前支持概率过滤的方式，实现方法在hashmap.cc中的GetWithAddProbability方法，后续还会支持按bloom filter进行过滤。特征淘汰支持按某个slot的值做删除，目前常用做法是按上次更新到现在的global_step差值做过滤，实现在hash_unary_filter.cc和ps_mark_op.cc中，具体方法是每一轮用ps_mark_op标记特征更新的global_step，然后隔一定时间或步数，调用hash_unary_filter对所有key进行一遍过滤。

**Comment by whuaxiom** [comment]
> @DecKen 代码已经开放出来了，实时特征频控目前支持概率过滤的方式，实现方法在hashmap.cc中的GetWithAddProbability方法，后续还会支持按bloom filter进行过滤。特征淘汰支持按某个slot的值做删除，目前常用做法是按上次更新到现在的global_step差值做过滤，实现在hash_unary_filter.cc和ps_mark_op.cc中，具体方法是每一轮用ps_mark_op标记特征更新的global_step，然后隔一定时间或步数，调用hash_unary_filter对所有key进行一遍过滤。

embedding有个参数是feature_dim，是说需要预先计算feature_dim么？在online learning的时候获取feature_dim不太方便

**Comment by kobe0849** [comment]
> @DecKen 代码已经开放出来了，实时特征频控目前支持概率过滤的方式，实现方法在hashmap.cc中的GetWithAddProbability方法，后续还会支持按bloom filter进行过滤。特征淘汰支持按某个slot的值做删除，目前常用做法是按上次更新到现在的global_step差值做过滤，实现在hash_unary_filter.cc和ps_mark_op.cc中，具体方法是每一轮用ps_mark_op标记特征更新的global_step，然后隔一定时间或步数，调用hash_unary_filter对所有key进行一遍过滤。

你们的做法是对每一个特征记录一个类似时间戳的东西，然后一定时间戳之后都没有更新到这个特征就把它删除，这么理解吗?具体怎么去设置这个时间呢，是保持总特征数量控制在一定范围还是就拍时间呢？

**Comment by songyue1104** [comment]
XDL有两种方式控制特征数量，一个是特征准入，即特征出现次数高于一定的阈值才会参与训练，目前采用的是概率的方式，后续会实现基于counting-bloomfilter的精准过滤。第二个是特征淘汰，目前提供基于时间的淘汰方式，业务代码需要定期调用清理op，后续我们会建立更完善的特征综合评分机制

**Comment by hazoth** [comment]
期待文档。
问个问题，一般来说在线学习，怎样更新模型？我看文档里，在线推理需要xdl模型导出转换成blaze。那对于在线学习怎么处理呢。

**Comment by simon1024** [comment]
> 期待文档。
> 问个问题，一般来说在线学习，怎样更新模型？我看文档里，在线推理需要xdl模型导出转换成blaze。那对于在线学习怎么处理呢。

同期待文档，准备搞在线学习。梳理了导出增量模型的过程，但是对于模型如何对接到blaze，进行增量更新，不是很明白。

**Comment by nolanliou** [comment]
> @DecKen 代码已经开放出来了，实时特征频控目前支持概率过滤的方式，实现方法在hashmap.cc中的GetWithAddProbability方法，后续还会支持按bloom filter进行过滤。特征淘汰支持按某个slot的值做删除，目前常用做法是按上次更新到现在的global_step差值做过滤，实现在hash_unary_filter.cc和ps_mark_op.cc中，具体方法是每一轮用ps_mark_op标记特征更新的global_step，然后隔一定时间或步数，调用hash_unary_filter对所有key进行一遍过滤。

有个问题咨询一下，如果用ps_mark_op标记更新的特征，请问当前step被更新的特征ID是要怎么获取呢？谢谢。

**Comment by anqin** [comment]
> > 期待文档。
> > 问个问题，一般来说在线学习，怎样更新模型？我看文档里，在线推理需要xdl模型导出转换成blaze。那对于在线学习怎么处理呢。
> 
> 同期待文档，准备搞在线学习。梳理了导出增量模型的过程，但是对于模型如何对接到blaze，进行增量更新，不是很明白。

 同求文档。不知道现在是否有人解决。
1）online如何training
2) 如何对接online的推理

 @DecKen @kobe0849 @hazoth @simon1024 @songyue1104
