### ISSUE TITLE
deepctr例子中，embedding设置成vtype='index' 会报错

### ISSUE THREAD

**Issue by brillwang** [alibaba/x-deeplearning#221]
在跑deepctr例子中
原有的一段代码是这样，
emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024, vtype='hash')
个人是想不经过hash，改成了下面的代码
emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024, vtype='index')
但是报错，我理解是选用index格式的话是直接去对应的位置取查找embedding是吗？不知道哪里理解出现了偏差呢？ 另外进到sparse的数据我是已经哈希或者做过处理了，id在维度之内，想直接按id去对应Index取embedding这种方式的话应该如何弄呢？

2019-05-09 17:23:24.807424: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "deepctr_test.py", line 61, in <module>
    train()
  File "deepctr_test.py", line 40, in train
    sess.run(train_op)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 266, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 241, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 51, in run
    results = execute(run_item, run_option, run_statistic)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 305, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
    raise ArgumentError(status.msg)
xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[BuildSparseSlice: Id should be a vector
Check Status [PS2XDL::ConvertStatus(st)] at [/home/brillwang/open_source/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_sparse_pull_op.cc]operator()@48]

**Comment by yiling-dc** [comment]
> 在跑deepctr例子中
> 原有的一段代码是这样，
> emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024, vtype='hash')
> 个人是想不经过hash，改成了下面的代码
> emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024, vtype='index')
> 但是报错，我理解是选用index格式的话是直接去对应的位置取查找embedding是吗？不知道哪里理解出现了偏差呢？ 另外进到sparse的数据我是已经哈希或者做过处理了，id在维度之内，想直接按id去对应Index取embedding这种方式的话应该如何弄呢？
> 
> 2019-05-09 17:23:24.807424: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> Traceback (most recent call last):
> File "deepctr_test.py", line 61, in 
> train()
> File "deepctr_test.py", line 40, in train
> sess.run(train_op)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 266, in run
> return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 241, in run
> return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 51, in run
> results = execute(run_item, run_option, run_statistic)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 305, in execute
> return current_graph().execute(outputs, run_option, run_statistic)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
> check_error(result.status)
> File "/usr/lib/python2.7/site-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
> raise ArgumentError(status.msg)
> xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[BuildSparseSlice: Id should be a vector
> Check Status [PS2XDL::ConvertStatus(st)] at [/home/brillwang/open_source/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_sparse_pull_op.cc]operator()@48]

你处理过的数据，ID是几维的？这个报错是ID的维度不对

**Comment by brillwang** [comment]
我把sparse的里面看了下，最多也不超过1000的，然后还是报这个错误embedding改成10240也一样，不知道方便加个微信 briller1 联系吗？

**Comment by yiling-dc** [comment]
> 我把sparse的里面看了下，最多也不超过1000的，然后还是报这个错误embedding改成10240也一样，不知道方便加个微信 briller1 联系吗？
> sparse的都是这样
> skey0|gkey0|sparse0@988:0.462050;sparse1@480:0.263620|deep0@0.011690,0.072661,..........
> 复制了10行，改了skey和gkey

emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024, vtype='index', serialized=True)

加上这个选项:serialized

默认的key是hash128，所以id的维度是[?, 2]，你现在如果改成index的话，id只有一维（注意这里说的维度不是宽度），因此要加上这个选项

**Comment by brillwang** [comment]
emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024000, vtype='index', serialized=True)
def embedding(name, sparse_input, initializer, emb_dim, feature_dim,
              combiner='sum', 
              vtype=VarType.Index, 
              length=50, 
              reverse=False, 
              batch_read=3000,
              feature_add_probability=1.0):
加了说没有这个参数，然后看embedding定义里面也没有这个东西。。
另外这个我可以理解原来的key都是占用两个空间的是吗，改成index方式就是1个空间了。

**Comment by yiling-dc** [comment]
> emb1 = xdl.embedding('emb1', batch['sparse0'], xdl.TruncatedNormal(stddev=0.001), 8, 1024000, vtype='index', serialized=True)
> def embedding(name, sparse_input, initializer, emb_dim, feature_dim,
> combiner='sum',
> vtype=VarType.Index,
> length=50,
> reverse=False,
> batch_read=3000,
> feature_add_probability=1.0):
> 加了说没有这个参数，然后看embedding定义里面也没有这个东西。。
> 另外这个我可以理解原来的key都是占用两个空间的是吗，改成index方式就是1个空间了。

sorry，刚才写错了，已更新。是在feature的接口里加那个参数。

**Comment by brillwang** [comment]
好的，感谢
