### ISSUE TITLE
nice project！

### ISSUE THREAD

**Issue by Ethan199111** [alibaba/x-deeplearning#223]
想问下 线下有机会当面请教下吗？我也是做分布式机器学习框架的 借鉴了很多ps-plus的思路

**Comment by songziqin** [comment]
我想问哈这个ps哪里好了，比如我问个问题，在对参数进行参数动态优化分配中，比如ps-lite对参数分配很简单就是对每一个feature id 进行hash然后对server个数取模，这样实现的逻辑是如果每个feature id 分配到每个server的概率一样大，那么最后的参数分配就是均衡的。为什么ps-plus后面用了比这个复杂的逻辑呢。这个我没有看明白，可以说说末。

**Comment by yiling-dc** [comment]
> 我想问哈这个ps哪里好了，比如我问个问题，在对参数进行参数动态优化分配中，比如ps-lite对参数分配很简单就是对每一个feature id 进行hash然后对server个数取模，这样实现的逻辑是如果每个feature id 分配到每个server的概率一样大，那么最后的参数分配就是均衡的。为什么ps-plus后面用了比这个复杂的逻辑呢。这个我没有看明白，可以说说末。

简单的平均分，会造成client到server的请求数目大量增加，如果不做其他处理，这样的分配策略会非常的低效，这也是现在某些开源框架在超大规模稀疏数据下速度很慢的原因之一。一个高效的分配策略应该是这样的：1. variable尽量少分；2. 满足memory限制；3. IO和CPU处理时间尽量均衡。目前xdl里就是按照这样的原则进行处理的。当然，你说的这种平均分配的策略，需要配合其他优化才能消除它带来的负面影响，之后的xdl版本升级中会出现相关的feature。

**Comment by songziqin** [comment]
@yiling-dc 您好哈，我看了balance_placementer.cc这一部分的实现逻辑，我其实有疑问的，你们在做variable分配的时候，其实是按照一个一个variable来进行的，每次分配完成的结果是每个solution->servers[s].net与avg_net接近。假设第一个variable来了，按照这个算法，它最后的结果是每个server所分配到一样的slice才是最优的，假设可以整除。第二个variable来了，也是这个逻辑，得到的结果是这个variable被分配到各个server的slice 数一样。依此类推，这样怎么可以保证1呢，让variable尽量少分。可能我没有看明白。麻烦解释哈。

**Comment by songziqin** [comment]
@yiling-dc.不好意思 我感觉看得有点懂了 你们貌似说得有点道理呢。

**Comment by Esail** [comment]
@songziqin  其实我倒不担心这种分配策略，我们都是自定义slice policy这样肯定能保证最优。我担心的是任务在yarn上运行时，网卡被多个container共享时会发生race condition的情况。

**Comment by songziqin** [comment]
@Esail 一般是一台机器就跑一个container吧。干嘛跑那么多container呢。

**Comment by Esail** [comment]
@songziqin 一台机器就跑一个container那还要资源调度和容器干嘛？直接在裸机上起不是更好吗？ 现实时，集群一定要同时跑多个任务，一个任务也需要同时跑多组参数来选择最佳模型

**Comment by songziqin** [comment]
@yiling-dc  我还有两个疑问，一个是我看到你们只提供了mxnet、tensorflow。为什么没有提供libtorch这个选项呢。还有在现实中，比较稀疏的是像userid,itemid这些ID类特征，比较消耗存储。这些其实variable比较少。其它的variable并没有那么稀疏。这种情况你们的分配策略也会有很高的收益末。

**Comment by songziqin** [comment]
@Esail 那我觉得我对容器的理解有误解吧。但是我们这边一台机器就起一个容器。然后这个容器会把这台机器跑满。

**Comment by cuisonghui** [comment]
> @Esail 那我觉得我对容器的理解有误解吧。但是我们这边一台机器就起一个容器。然后这个容器会把这台机器跑满。

@songziqin 请问你们是怎么把cpu资源给跑满的呢，需要调整什么参数，单机器一个worker，我这边cpu占用率很低，一直跑不满，我只能一台机器多worker
