### ISSUE TITLE
restart-client stuck

### ISSUE THREAD

**Issue by all3n** [alibaba/x-deeplearning#225]
在分布式yarn训练出现 导致container 卡主不能退出

Disconnected By read errno 104
('An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: %s', 'ErrorCode[4], ErrorMsg[network error\nCheck Status [PS2XDL::ConvertStatus(st)] at [/builds/deep-learning/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_sparse_apply_adam_op.cc]operator()@65]')
Disconnected By read errno 111
Disconnected By read errno 111
Disconnected By read errno 111
Traceback (most recent call last):
  File "pnn_xdl.py", line 324, in <module>
    tf.app.run(main=main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "pnn_xdl.py", line 287, in main
    model.train()
  File "pnn_xdl.py", line 244, in train
    values = train_sess.run(train_ops)
  File "/usr/local/lib/python2.7/dist-packages/xdl/python/training/train_session.py", line 265, in run
    self._restart_client()
  File "/usr/local/lib/python2.7/dist-packages/xdl/python/training/train_session.py", line 259, in _restart_client
    raise InternalError("restart client failed")
xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[restart client failed]

这个 错误有时候是ps_sparse_apply_adam_op
ps_pull_op
ps_apply_moving_average_op.cc
一般都是这个三个
('An error was raised. This may be due to a preemption in a 
connected worker or parameter server. The current session will be closed and a new session will be created. Error: %s', 'ErrorCode[4], 
ErrorMsg[network error\nCheck Status [PS2XDL::ConvertStatus(st)] at [/builds/deep-learning/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_pull_op.cc]operator()@44]')

**Comment by yiling-dc** [comment]
通常情况下，worker出现这种log是因为ps或者scheduler的问题导致的，可以查一下ps或者scheduler的日志，看有没有有用信息，或者看下这些机器上有没有oom的系统日志。
