### ISSUE TITLE
ESMM测试时报错：File exhausted

### ISSUE THREAD

**Issue by Daiquanjian** [alibaba/x-deeplearning#228]
root@server-B:/home/xxx/ESMM/script# python esmm.py --run_mode=local --ckpt_dir=./ckpt --config=config.json
config: {u'checkpoint': {u'ckpt': u'./ckpt-...............12000'}, u'files': [u'../data/test_data.0', u'../data/test_data.1', u'../data/test_data.2', u'../data/test_data.3'], u'is_training': False}
restore from ./ckpt-...............12000
Traceback (most recent call last):
  File "esmm.py", line 300, in <module>
    run(is_training, files)
  File "esmm.py", line 124, in run
    saver.restore(ckpt)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 81, in restore
    execute(self.restore_op(version))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 33, in check_error
    raise PsError(status.msg)
xdl.python.lib.error.PsError: ErrorCode[4], ErrorMsg[File exhausted
Check Status [PS2XDL::ConvertStatus(st)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_restore_op.cc]operator()@40]

File exhausted这个错误信息是什么意思？在哪个文件定义？

**Comment by guoxinyang** [comment]
file exhausted是因为提供的checkpoint不对，我猜是因为ckpt写的是"./ckpt-...............12000"，应该是"ckpt-...............12000"

**Comment by Daiquanjian** [comment]
> file exhausted是因为提供的checkpoint不对，我猜是因为ckpt写的是"./ckpt-...............12000"，应该是"ckpt-...............12000"

**Comment by Daiquanjian** [comment]
> file exhausted是因为提供的checkpoint不对，我猜是因为ckpt写的是"./ckpt-...............12000"，应该是"ckpt-...............12000"

**Comment by Daiquanjian** [comment]
> file exhausted是因为提供的checkpoint不对，我猜是因为ckpt写的是"./ckpt-...............12000"，应该是"ckpt-...............12000"

感谢回复。我把./ckpt-...............12000改成了ckpt-...............12000，但依然出现了这个错误。另外，file exhausted这个错误在我的训练中保存checkpoint时就出现过了，错误信息如下：
save checkpoint at global_step[500], ckpt version[ckpt-.................500]
('An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: %s', 'ErrorCode[4], ErrorMsg[File exhausted\nCheck Status [PS2XDL::ConvertStatus(st)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]')
这似乎是服务器被抢占的意思？请大佬解读一下。

**Comment by Daiquanjian** [comment]
感谢回复。我把./ckpt-...............12000改成了ckpt-...............12000，但依然出现了这个错误。另外，file exhausted这个错误在我的训练中保存checkpoint时就出现过了，错误信息如下：
save checkpoint at global_step[500], ckpt version[ckpt-.................500]
('An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: %s', 'ErrorCode[4], ErrorMsg[File exhausted\nCheck Status [PS2XDL::ConvertStatus(st)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]')
这似乎是服务器被抢占的意思？请大佬解读一下。 @guoxinyang

**Comment by Daiquanjian** [comment]
我的train_config.json配置如下：
{
    "checkpoint": {
        "ckpt": ""
    },
    "files": ["../data/train_data.0"],
    "is_training": true
}

**Comment by guoxinyang** [comment]
save 出现这个错误，可能是因为多个worker同时调用了save?save最好使用CheckpointHook来保存。另外这个问题最好提供下scheduler的日志，因为实际问题发生在server端。

**Comment by Daiquanjian** [comment]
> save 出现这个错误，可能是因为多个worker同时调用了save?save最好使用CheckpointHook来保存。另外这个问题最好提供下scheduler的日志，因为实际问题发生在server端。

在ESMM代码中，模型是通过CheckpointHook保存的。请问scheduler日志怎么查看呢（我是小白T-T）？ @guoxinyang

**Comment by 1980695671** [comment]
请问我运行完esmm，也设置了模型保存目录，为什么没有生成模型呢。。
