### ISSUE TITLE
ftrl 算法有bug

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#229]
FtrlUpdater 这个操作 if (abs(*linear) > l1_reg) {，不应该用abs吧。应该用fabs.如果*linear是个浮点数，abs(*linear)这个返回应该是0，比如-0.000003，返回0，感觉是个大的bug.

**Comment by guoxinyang** [comment]
感谢指出错误，我们改一下。

**Comment by songziqin** [comment]
@guoxinyang 这个级别的错误你们都没有检查出来，我也挺意外的,国外的大的公司的开源框架,一般不会有这个级别的bug吧.

**Comment by songziqin** [comment]
@guoxinyang 问哈这个bug为什么还没有修复呢。

**Comment by songziqin** [comment]
我搞错了。
