### ISSUE TITLE
代码逻辑有点奇怪

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#231]
我看了done_closure.h的代码，我的理解是请求的逻辑处理完了，需要给客户端返回请求数据，为什么把它放到一个队列，然后又把它取出来呢，然后执行返回响应呢。感觉逻辑挺奇怪的。
outputHub->Enqueue(item, cpu_id_, 0, NULL);
 ps::network::Future<ps::network::Item> f = outputHub->GetFuture(cpu_id_, 0);
 f.Get();

**Comment by shanshanpt** [comment]
通信线程和上层计算线程之间交互需要通过这个queue。
