### ISSUE TITLE
训练出现nan值

### ISSUE THREAD

**Issue by zhanglistar** [alibaba/x-deeplearning#232]
稀疏特征和dense特征都有，在训练几天后会出现nan值，尝试调小学习率、正则化等都无效，xdl支持梯度裁剪吗？

**Comment by zhanglistar** [comment]
> 稀疏特征和dense特征都有，在训练几天后会出现nan值，尝试调小学习率、正则化等都无效，xdl支持梯度裁剪吗？

做了clip问题消失

**Comment by supersush** [comment]
您好，我出现了和您一样的问题。请问您是如何做梯度裁剪的。 @zhanglistar
