### ISSUE TITLE
Online-Learning的代码没开放出来？

### ISSUE THREAD

**Issue by xiaobaoding** [alibaba/x-deeplearning#24]
公众号文章里提到的对Online-Learning的支持（去ID化的稀疏特征表示、实时特征频控、过期特征淘汰等），代码里好像没找到对应的实现，是还没开放出来么？
另外，有些op好像也找不到对应的实现

**Comment by guoxinyang** [comment]
这个和 https://github.com/alibaba/x-deeplearning/issues/22 是一个问题，已经回答在那边，请参考。
