### ISSUE TITLE
恢复模型参数遇到问题

### ISSUE THREAD

**Issue by sibangde** [alibaba/x-deeplearning#243]
文档中保存和恢复模型的方法如下，下面所说的恢复模型参数方法好像只是针对通过Saver保存的，但是如果是通过CheckpointHook保存的，怎么用saver.restore()恢复了，我试了下面的方法但是会说找不到checkpoint？
保存模型变量
1. 通过Saver保存
import xdl
saver = xdl.Saver()
checkpoint_version = "xxx" # checkpoint名称，一般是global step
saver.save(version = checkpoint_version)  
2. 通过CheckpointHook保存
import xdl
train_op = ...
hook = xdl.CheckpointHook(save_interval_step=1000) # 每1000个global step保存一次
sess = xdl.TrainSession(hooks=[hook])
sess.run(train_op)
1. 恢复模型参数
import xdl
saver = xdl.Saver()
checkpoint_version = "xxx"
saver.restore(version = checkpoint_version)

**Comment by songyue1104** [comment]
需要命令行或json配置里传入checkpoint路径
