### ISSUE TITLE
请问XDL在哪个环节将计算交接给后端引擎tensorflow的

### ISSUE THREAD

**Issue by theflyfish** [alibaba/x-deeplearning#244]
看了下XDL的源码，有几个地方非常疑惑：
1）XDL  python定义好图之后，用XDL自己的实现的session进行了图的执行，并没有使用tensorflow的session去做；所以想问下xdl是怎么跟后端的tensorflow结合的
2）在分布式的场景下，使用ps-plus替换了tensorflow的参数服务，这块又是怎么样替换的，是在tensorflow原生的图处理流程上替换了send reciver rendvous相关的逻辑吗
3）看core/famework下的代码，貌似XDL自己也实现了一套图执行与op计算的逻辑，不知道这块与tensorflow mxnet有无关系，期待回复，多谢

**Comment by songyue1104** [comment]
1） 看python和core下面backend部分代码
2） 通过feed方式传给tf的
3） 训练的整体流程都是由XDL graph驱动的，tf和mxnet只是xdl的一个op

**Comment by theflyfish** [comment]
感谢回答，还有一点不明白
2）tf中的varibles参数应该是通过placement的方式放置到nativePS上，这部分XDL是怎么接管到ps-plus上的

**Comment by songziqin** [comment]
> 1） 看python和core下面backend部分代码
> 2） 通过feed方式传给tf的
> 3） 训练的整体流程都是由XDL graph驱动的，tf和mxnet只是xdl的一个op

我想问哈，这个xdl的实现是不是可以更加的精简，就是通过扩展op的方式实现
