### ISSUE TITLE
xdl_submit支持 hadoop-yarn 2.X版本吗

### ISSUE THREAD

**Issue by itscarrot** [alibaba/x-deeplearning#245]
如果用CPU的话，xdl_submit支持 hadoop-yarn 2.X版本吗

**Comment by yiling-dc** [comment]
2.X 和3.X 在API上是有区别的，如果你要使用的话，可以把pom文件里的依赖替换掉，然后把相应需要修改的代码改一下重新编译就好了，工作量也不是很大。
