### ISSUE TITLE
编译错误！

### ISSUE THREAD

**Issue by AlexanLee** [alibaba/x-deeplearning#25]
不知道有自己编译通过的没有，按照文中说的编译过程，宿主机器mac mojave.编译了两个晚上都没有编译成功！不知道是不是文中描述的步骤有什么缺失没有？已经踩了一堆坑了～～

**Comment by shanshanpt** [comment]
错误信息放一下，我在mac air，mac pro的docker上都编译过。

**Comment by shanshanpt** [comment]
不过不建议在pc机器上操作，因为有一些三方库编译非常耗时，耗资源。

**Comment by AlexanLee** [comment]
c++: internal compiler error: Killed (program cc1plus)

**Comment by shanshanpt** [comment]
@AlexanLee 这个一般是编译的时候内存不够导致的，有一个简单的办法，但是可能会编译比较慢，将xdl/third_party/seastar/service/build_script/build.sh中 ```ninja -j8 ``` 改成 ```ninja -j1``` , ```make -j32``` 改成 ```make -j1``` ，-j表示的是编译线程数。
推荐在资源比较高的开发机器上编译。

**Comment by shanshanpt** [comment]
@AlexanLee 对，主要是因为三方库中有一些确实是消耗资源很多。解决了就好哈

**Comment by songyue1104** [comment]
@AlexanLee 建议把踩的坑给我们反馈一下
