### ISSUE TITLE
dead loop in tdm_ub_att_ubuntu while execute python tree_cluster.py

### ISSUE THREAD

**Issue by better629** [alibaba/x-deeplearning#252]
There is a dead loop while execute `python tree_cluster.py`, the output is 
```
Minbatch, batch size: 607, elapsed: 2.37421298027
Minbatch, batch size: 607, elapsed: 2.44371891022
Minbatch, batch size: 607, elapsed: 2.43994808197
Minbatch, batch size: 607, elapsed: 2.27980279922
Minbatch, batch size: 607, elapsed: 2.8827059269
Minbatch, batch size: 608, elapsed: 2.89527893066
Minbatch, batch size: 608, elapsed: 3.00607395172
Minbatch, batch size: 607, elapsed: 2.77252697945
Got empty job, pid: 12971, time: 0
Got empty job, pid: 12992, time: 0
Got empty job, pid: 12962, time: 0
Got empty job, pid: 13021, time: 0
Got empty job, pid: 13012, time: 0
Got empty job, pid: 13030, time: 0
Got empty job, pid: 13039, time: 0
Got empty job, pid: 13053, time: 0
Got empty job, pid: 13048, time: 0
Got empty job, pid: 13062, time: 0
Got empty job, pid: 13075, time: 0
Got empty job, pid: 12834, time: 0
Got empty job, pid: 13084, time: 0
Got empty job, pid: 13094, time: 0
Got empty job, pid: 12854, time: 0
Got empty job, pid: 13125, time: 0
Got empty job, pid: 13157, time: 0
Got empty job, pid: 13166, time: 0
Got empty job, pid: 13171, time: 0
Got empty job, pid: 13184, time: 0
Got empty job, pid: 12863, time: 0
Got empty job, pid: 12877, time: 0
Got empty job, pid: 12899, time: 0
Got empty job, pid: 12882, time: 0
Process 12926 exits
Process 12926 process 607 items
Process 12908 exits
Process 12908 process 607 items
Process 12917 exits
Process 12917 process 607 items
Process 12953 exits
Process 12953 process 607 items
Process 12944 exits
Process 12944 process 607 items
Process 12935 exits
Process 12935 process 608 items
Process 12868 exits
Process 12868 process 608 items
Process 12825 exits
Process 12825 process 607 items
Got empty job, pid: 12992, time: 1
Got empty job, pid: 12962, time: 1
Got empty job, pid: 12971, time: 1
Got empty job, pid: 13021, time: 1
Got empty job, pid: 13012, time: 1
Got empty job, pid: 13030, time: 1
Got empty job, pid: 13039, time: 1
Got empty job, pid: 13053, time: 1
Got empty job, pid: 13048, time: 1
Got empty job, pid: 13062, time: 1
Got empty job, pid: 13075, time: 1
Got empty job, pid: 12834, time: 1
Got empty job, pid: 13084, time: 1
Got empty job, pid: 13094, time: 1
Got empty job, pid: 12854, time: 1
Got empty job, pid: 13125, time: 1
Got empty job, pid: 13157, time: 1
Got empty job, pid: 13166, time: 1
Got empty job, pid: 13171, time: 1
Got empty job, pid: 13184, time: 1
Got empty job, pid: 12863, time: 1
Got empty job, pid: 12877, time: 1
Got empty job, pid: 12899, time: 1
Got empty job, pid: 12882, time: 1
Got empty job, pid: 12962, time: 2
Got empty job, pid: 12992, time: 2
Got empty job, pid: 13021, time: 2
Got empty job, pid: 13012, time: 2
Got empty job, pid: 12971, time: 2
Got empty job, pid: 13030, time: 2
Got empty job, pid: 13039, time: 2
Got empty job, pid: 13053, time: 2
Got empty job, pid: 13048, time: 2
Got empty job, pid: 13062, time: 2
Got empty job, pid: 13075, time: 2
Got empty job, pid: 12834, time: 2
Got empty job, pid: 13084, time: 2
Got empty job, pid: 13094, time: 2
Got empty job, pid: 12854, time: 2
Got empty job, pid: 13125, time: 2
Got empty job, pid: 13157, time: 2
Got empty job, pid: 13166, time: 2
Got empty job, pid: 13171, time: 2
Got empty job, pid: 13184, time: 2
Got empty job, pid: 12863, time: 2
Got empty job, pid: 12877, time: 2
Got empty job, pid: 12899, time: 2
Got empty job, pid: 12882, time: 2
Got empty job, pid: 12992, time: 3
Got empty job, pid: 12962, time: 3
Got empty job, pid: 13012, time: 3
Got empty job, pid: 12971, time: 3
Got empty job, pid: 13021, time: 3
Got empty job, pid: 13030, time: 3
Got empty job, pid: 13039, time: 3
Got empty job, pid: 13053, time: 3
Got empty job, pid: 13048, time: 3
Got empty job, pid: 13062, time: 3
Got empty job, pid: 13075, time: 3
Process 12834 exits
Process 12834 process 0 items
Got empty job, pid: 13084, time: 3
Got empty job, pid: 13094, time: 3
Process 12854 exits
Process 12854 process 0 items
Got empty job, pid: 13125, time: 3
Got empty job, pid: 13157, time: 3
Got empty job, pid: 13166, time: 3
Got empty job, pid: 13171, time: 3
Got empty job, pid: 13184, time: 3
Process 12863 exits
Process 12863 process 0 items
Process 12877 exits
Process 12877 process 0 items
Process 12899 exits
Process 12899 process 0 items
Process 12882 exits
Process 12882 process 0 items
Got empty job, pid: 13075, time: 17
Got empty job, pid: 13084, time: 17
Got empty job, pid: 13048, time: 17
Got empty job, pid: 13094, time: 17
Got empty job, pid: 13125, time: 17
Got empty job, pid: 13157, time: 17
Got empty job, pid: 13166, time: 17
Got empty job, pid: 13171, time: 17
Got empty job, pid: 13184, time: 17
Got empty job, pid: 13021, time: 18
Got empty job, pid: 13012, time: 18
Got empty job, pid: 12962, time: 18
Got empty job, pid: 13053, time: 18
Got empty job, pid: 12971, time: 18
Got empty job, pid: 13030, time: 18
Got empty job, pid: 13039, time: 18
Got empty job, pid: 12992, time: 18
Got empty job, pid: 13062, time: 18
Got empty job, pid: 13075, time: 18
Got empty job, pid: 13084, time: 18
Got empty job, pid: 13048, time: 18
Got empty job, pid: 13094, time: 18
Got empty job, pid: 13125, time: 18
Got empty job, pid: 13157, time: 18
Got empty job, pid: 13166, time: 18
Got empty job, pid: 13171, time: 18
Got empty job, pid: 13184, time: 18
Got empty job, pid: 13012, time: 19
Got empty job, pid: 12962, time: 19
Got empty job, pid: 13053, time: 19
Got empty job, pid: 12971, time: 19
Got empty job, pid: 13030, time: 19
```

The reason may be the input data set is small, but the `parall` parameter in `data/tdm.json` is large. So, if you use mock.dat as input, set `parall` to small num like 4 or 8.

**Comment by better629** [comment]
Even with a large dataset, the `parall` parameter in `data/tdm.json` is smaller than `cpu nums` perfer. It's just a suggestion.

**Comment by chengenbao** [comment]
> There is a dead loop while execute `python tree_cluster.py`, the output is
> 
> ```
> Minbatch, batch size: 607, elapsed: 2.37421298027
> Minbatch, batch size: 607, elapsed: 2.44371891022
> Minbatch, batch size: 607, elapsed: 2.43994808197
> Minbatch, batch size: 607, elapsed: 2.27980279922
> Minbatch, batch size: 607, elapsed: 2.8827059269
> Minbatch, batch size: 608, elapsed: 2.89527893066
> Minbatch, batch size: 608, elapsed: 3.00607395172
> Minbatch, batch size: 607, elapsed: 2.77252697945
> Got empty job, pid: 12971, time: 0
> Got empty job, pid: 12992, time: 0
> Got empty job, pid: 12962, time: 0
> Got empty job, pid: 13021, time: 0
> Got empty job, pid: 13012, time: 0
> Got empty job, pid: 13030, time: 0
> Got empty job, pid: 13039, time: 0
> Got empty job, pid: 13053, time: 0
> Got empty job, pid: 13048, time: 0
> Got empty job, pid: 13062, time: 0
> Got empty job, pid: 13075, time: 0
> Got empty job, pid: 12834, time: 0
> Got empty job, pid: 13084, time: 0
> Got empty job, pid: 13094, time: 0
> Got empty job, pid: 12854, time: 0
> Got empty job, pid: 13125, time: 0
> Got empty job, pid: 13157, time: 0
> Got empty job, pid: 13166, time: 0
> Got empty job, pid: 13171, time: 0
> Got empty job, pid: 13184, time: 0
> Got empty job, pid: 12863, time: 0
> Got empty job, pid: 12877, time: 0
> Got empty job, pid: 12899, time: 0
> Got empty job, pid: 12882, time: 0
> Process 12926 exits
> Process 12926 process 607 items
> Process 12908 exits
> Process 12908 process 607 items
> Process 12917 exits
> Process 12917 process 607 items
> Process 12953 exits
> Process 12953 process 607 items
> Process 12944 exits
> Process 12944 process 607 items
> Process 12935 exits
> Process 12935 process 608 items
> Process 12868 exits
> Process 12868 process 608 items
> Process 12825 exits
> Process 12825 process 607 items
> Got empty job, pid: 12992, time: 1
> Got empty job, pid: 12962, time: 1
> Got empty job, pid: 12971, time: 1
> Got empty job, pid: 13021, time: 1
> Got empty job, pid: 13012, time: 1
> Got empty job, pid: 13030, time: 1
> Got empty job, pid: 13039, time: 1
> Got empty job, pid: 13053, time: 1
> Got empty job, pid: 13048, time: 1
> Got empty job, pid: 13062, time: 1
> Got empty job, pid: 13075, time: 1
> Got empty job, pid: 12834, time: 1
> Got empty job, pid: 13084, time: 1
> Got empty job, pid: 13094, time: 1
> Got empty job, pid: 12854, time: 1
> Got empty job, pid: 13125, time: 1
> Got empty job, pid: 13157, time: 1
> Got empty job, pid: 13166, time: 1
> Got empty job, pid: 13171, time: 1
> Got empty job, pid: 13184, time: 1
> Got empty job, pid: 12863, time: 1
> Got empty job, pid: 12877, time: 1
> Got empty job, pid: 12899, time: 1
> Got empty job, pid: 12882, time: 1
> Got empty job, pid: 12962, time: 2
> Got empty job, pid: 12992, time: 2
> Got empty job, pid: 13021, time: 2
> Got empty job, pid: 13012, time: 2
> Got empty job, pid: 12971, time: 2
> Got empty job, pid: 13030, time: 2
> Got empty job, pid: 13039, time: 2
> Got empty job, pid: 13053, time: 2
> Got empty job, pid: 13048, time: 2
> Got empty job, pid: 13062, time: 2
> Got empty job, pid: 13075, time: 2
> Got empty job, pid: 12834, time: 2
> Got empty job, pid: 13084, time: 2
> Got empty job, pid: 13094, time: 2
> Got empty job, pid: 12854, time: 2
> Got empty job, pid: 13125, time: 2
> Got empty job, pid: 13157, time: 2
> Got empty job, pid: 13166, time: 2
> Got empty job, pid: 13171, time: 2
> Got empty job, pid: 13184, time: 2
> Got empty job, pid: 12863, time: 2
> Got empty job, pid: 12877, time: 2
> Got empty job, pid: 12899, time: 2
> Got empty job, pid: 12882, time: 2
> Got empty job, pid: 12992, time: 3
> Got empty job, pid: 12962, time: 3
> Got empty job, pid: 13012, time: 3
> Got empty job, pid: 12971, time: 3
> Got empty job, pid: 13021, time: 3
> Got empty job, pid: 13030, time: 3
> Got empty job, pid: 13039, time: 3
> Got empty job, pid: 13053, time: 3
> Got empty job, pid: 13048, time: 3
> Got empty job, pid: 13062, time: 3
> Got empty job, pid: 13075, time: 3
> Process 12834 exits
> Process 12834 process 0 items
> Got empty job, pid: 13084, time: 3
> Got empty job, pid: 13094, time: 3
> Process 12854 exits
> Process 12854 process 0 items
> Got empty job, pid: 13125, time: 3
> Got empty job, pid: 13157, time: 3
> Got empty job, pid: 13166, time: 3
> Got empty job, pid: 13171, time: 3
> Got empty job, pid: 13184, time: 3
> Process 12863 exits
> Process 12863 process 0 items
> Process 12877 exits
> Process 12877 process 0 items
> Process 12899 exits
> Process 12899 process 0 items
> Process 12882 exits
> Process 12882 process 0 items
> Got empty job, pid: 13075, time: 17
> Got empty job, pid: 13084, time: 17
> Got empty job, pid: 13048, time: 17
> Got empty job, pid: 13094, time: 17
> Got empty job, pid: 13125, time: 17
> Got empty job, pid: 13157, time: 17
> Got empty job, pid: 13166, time: 17
> Got empty job, pid: 13171, time: 17
> Got empty job, pid: 13184, time: 17
> Got empty job, pid: 13021, time: 18
> Got empty job, pid: 13012, time: 18
> Got empty job, pid: 12962, time: 18
> Got empty job, pid: 13053, time: 18
> Got empty job, pid: 12971, time: 18
> Got empty job, pid: 13030, time: 18
> Got empty job, pid: 13039, time: 18
> Got empty job, pid: 12992, time: 18
> Got empty job, pid: 13062, time: 18
> Got empty job, pid: 13075, time: 18
> Got empty job, pid: 13084, time: 18
> Got empty job, pid: 13048, time: 18
> Got empty job, pid: 13094, time: 18
> Got empty job, pid: 13125, time: 18
> Got empty job, pid: 13157, time: 18
> Got empty job, pid: 13166, time: 18
> Got empty job, pid: 13171, time: 18
> Got empty job, pid: 13184, time: 18
> Got empty job, pid: 13012, time: 19
> Got empty job, pid: 12962, time: 19
> Got empty job, pid: 13053, time: 19
> Got empty job, pid: 12971, time: 19
> Got empty job, pid: 13030, time: 19
> ```
> 
> The reason may be the input data set is small, but the `parall` parameter in `data/tdm.json` is large. So, if you use mock.dat as input, set `parall` to small num like 4 or 8.

As you said, when the data set is small, you should change `parall` to small number. The reason of the dead loop is that a worker process is exited only when it has executed some tasks, when the data set is small, some worker can not get task.

**Comment by chengenbao** [comment]
> Even with a large dataset, the `parall` parameter in `data/tdm.json` is smaller than `cpu nums` perfer. It's just a suggestion.

The `data/tdm.json` is only a example configuration, user should config it to suit their job
