### ISSUE TITLE
xdl tag=v1.1 bug

### ISSUE THREAD

**Issue by better629** [alibaba/x-deeplearning#257]
Line 164 `self._save.export_graph(as_text=self._as_text);` in `https://github.com/alibaba/x-deeplearning/blob/v1.1/xdl/xdl/python/training/saver.py` 
There does not have `attribute '_save'`

**Comment by lovickie** [comment]
Fixed. Thanks very much!

**Comment by better629** [comment]
> Fixed. Thanks very much!

@lovickie
