### ISSUE TITLE
运行esmm时报错，请问这个错误提示是什么意思啊？

### ISSUE THREAD

**Issue by z-h-u-j-u-n** [alibaba/x-deeplearning#259]
`python esmm.py --run_mode=local --ckpt_dir=./ckpt --config=config.json
`
config: {u'checkpoint': {u'ckpt': u'./ckpt'}, u'files': [u'/home/zhhu/ESMM/data/build/esmm_train_data.0', u'/home/zhhu/ESMM/data/build/esmm_train_data.1', u'/home/zhhu/ESMM/data/build/esmm_train_data.2', u'/home/zhhu/ESMM/data/build/esmm_train_data.3'], u'is_training': True}
2019-08-23 06:33:23.153699: F /home/yue.song/XDL-OpenSource-master/xdl/xdl/data_io/scheduler.cc:138] Check failed: rparam->end_ > rparam->begin_ 
Aborted (core dumped)

**Comment by z-h-u-j-u-n** [comment]
找到问题了，是生成数据的问题...

**Comment by Ru-Xiang** [comment]
你好，我遇到了相同的问题，能描述下具体是生成数据的什么问题吗， 我用一个分区数据是没有问题的，但是用dir就报错了

**Comment by Ru-Xiang** [comment]
> 你好，我遇到了相同的问题，能描述下具体是生成数据的什么问题吗， 我用一个分区数据是没有问题的，但是用dir就报错了

我这里的原因找到了，供后来人参考： 原因是Spark生成的数据下有一个_SUCCESS文件，删掉就好了
