### ISSUE TITLE
样本格式疑惑

### ISSUE THREAD

**Issue by zhhu1996** [alibaba/x-deeplearning#260]
`# sample id        | group id   | sparse                                       | dense                      | label | timestamp
7859345_420968_1007|user_3423487|clk_14@32490:1.0,32988:2.0;prefer@323423,32342|qscore@0.8,0.5;ad_price@33.8|0.0,1.0|1544094136`
对于sparse和dense列的特征，我有些疑惑：
按照您在文档中说的`多组特征用';'分隔，一个特征名字和内存用'@'分隔，内容多值用','分隔，稀疏的key和value用':'分隔`
那prefer@323423,32342是什么意思啊？
这组特征我也看不懂clk_14@32490:1.0,32988:2.0
感谢您的指导

**Comment by zhhu1996** [comment]
我尝试这样解析：
`clk_14@32490:1.0,32988:2.0`
表示特征名clk_14，key=32490，value=1.0和key=32988，value=2.0
`prefer@323423,32342`
表示特征名prefer，取值为323423,32342
是像我这样理解的吗？

**Comment by better629** [comment]
> 我尝试这样解析：
> `clk_14@32490:1.0,32988:2.0`
> 表示特征名clk_14，key=32490，value=1.0和key=32988，value=2.0
> `prefer@323423,32342`
> 表示特征名prefer，取值为323423,32342
> 是像我这样理解的吗？

Yes, you are right.

**Comment by zhhu1996** [comment]
okey, thanks!
