### ISSUE TITLE
请问TDM怎么实现分布式的训练和线上serving

### ISSUE THREAD

**Issue by cuisonghui** [alibaba/x-deeplearning#264]
因为我们的索引量可能在几千万，请问怎么做到分布式检索？
如果直接把索引切片的话，用户的行为数据可能就不是连续的，这样是否可训练？

**Comment by zhuhan1236** [comment]
> 因为我们的索引量可能在几千万，请问怎么做到分布式检索？
> 如果直接把索引切片的话，用户的行为数据可能就不是连续的，这样是否可训练？

几千万量级的索引，单机应该能够handle吧？分布式训练的话，直接按照XDL的说明配置分布式模式，就能实现多机多卡并行训练

**Comment by cuisonghui** [comment]
> > 因为我们的索引量可能在几千万，请问怎么做到分布式检索？
> > 如果直接把索引切片的话，用户的行为数据可能就不是连续的，这样是否可训练？
> 
> 几千万量级的索引，单机应该能够handle吧？分布式训练的话，直接按照XDL的说明配置分布式模式，就能实现多机多卡并行训练

我可能没说明白，我主要担心的是如果索引量过大(item过多)，tdm那颗检索树，耗时会很不理想,后续我会测试一下，因为官方给的benchmark也只是在400W的item上。
所以想到最简单的暴力方法，可不可以把item分成多份，每份都生成一个模型和一颗检索树。
然后请求并发打到多颗检索树上，但是这样是否就造成用户行为序列不是连续的，不知道会不会对模型有很大影响。
另外请教,xdl blaze已经实现了分布式的serving了吗

**Comment by zhuhan1236** [comment]
> > > 因为我们的索引量可能在几千万，请问怎么做到分布式检索？
> > > 如果直接把索引切片的话，用户的行为数据可能就不是连续的，这样是否可训练？
> > 
> > 
> > 几千万量级的索引，单机应该能够handle吧？分布式训练的话，直接按照XDL的说明配置分布式模式，就能实现多机多卡并行训练
> 
> 我可能没说明白，我主要担心的是如果索引量过大(item过多)，tdm那颗检索树，耗时会很不理想,后续我会测试一下，因为官方给的benchmark也只是在400W的item上。
> 所以想到最简单的暴力方法，可不可以把item分成多份，每份都生成一个模型和一颗检索树。
> 然后请求并发打到多颗检索树上，但是这样是否就造成用户行为序列不是连续的，不知道会不会对模型有很大影响。
> 另外请教,xdl blaze已经实现了分布式的serving了吗

实际上主要的时间开销不在索引树的查找上，而是在兴趣度的计算上，也就是深度网络的inference。所以在千万量级的索引量、且QPS非常大时，可以通过每台Server机器都使用完整的索引树结构、将inference任务分发实现并行的方案。blaze目前的inference本身并不是分布式的，但是支持多机共同serving，即每台机器都保留全量model、独立打分

**Comment by cuisonghui** [comment]
> > > > 因为我们的索引量可能在几千万，请问怎么做到分布式检索？
> > > > 如果直接把索引切片的话，用户的行为数据可能就不是连续的，这样是否可训练？
> > > 
> > > 
> > > 几千万量级的索引，单机应该能够handle吧？分布式训练的话，直接按照XDL的说明配置分布式模式，就能实现多机多卡并行训练
> > 
> > 
> > 我可能没说明白，我主要担心的是如果索引量过大(item过多)，tdm那颗检索树，耗时会很不理想,后续我会测试一下，因为官方给的benchmark也只是在400W的item上。
> > 所以想到最简单的暴力方法，可不可以把item分成多份，每份都生成一个模型和一颗检索树。
> > 然后请求并发打到多颗检索树上，但是这样是否就造成用户行为序列不是连续的，不知道会不会对模型有很大影响。
> > 另外请教,xdl blaze已经实现了分布式的serving了吗
> 
> 实际上主要的时间开销不在索引树的查找上，而是在兴趣度的计算上，也就是深度网络的inference。所以在千万量级的索引量、且QPS非常大时，可以通过每台Server机器都使用完整的索引树结构、将inference任务分发实现并行的方案。blaze目前的inference本身并不是分布式的，但是支持多机共同serving，即每台机器都保留全量model、独立打分

谢谢回答，我随后研究并尝试一下。
