### ISSUE TITLE
TDM为什么选择了树而不是直接使用ANN图算法（HNSW）

### ISSUE THREAD

**Issue by prozhuchen** [alibaba/x-deeplearning#272]
1. 想咨询一下，为什么TDM选择了树这种结构来加速召回，而不是使用HNSW这类更优秀的ANN算法。从benchnark上来看，以树为结构的ann算法比以图为结构的ann算法在召回效果上要差不少。
2. 阿里内部有对比过使用TDM和直接使用HNSW这类ANN算法的召回效果吗？

谢谢。

**Comment by cuisonghui** [comment]
阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类

**Comment by zhuhan1236** [comment]
TDM和传统意义上的ANN检索算法的核心区别是，对“距离”的定义不一样。一般而言，ANN算法的目标是查找离Query向量距离最近的Item向量。这里的“距离”，是向量之间的距离度量（L2距离、内积距离、余弦距离等）。在推荐问题中，我们需要召回的是“用户最感兴趣的Item”。此时，如果使用ANN查询的方法来召回，一个基本的假设是，用户对Item的兴趣度量，可以表示成“用户向量”和“Item向量”的距离。在这样的逻辑之上，才会有具体的ANN算法的选择问题。回到TDM中，我们对“用户对Item的兴趣”度量本身进行了升级（使用复杂模型来计算兴趣度），因为“用户向量”到“Item向量”的距离这一方式过于简单，无法精准地预估用户兴趣分布。此时，传统的ANN检索方法不再适用，因为已经没有了明确的Query向量。所以，TDM使用树结构这种具有明确层次关系的索引结构，作为Item索引对召回进行加速。论文中有对比TDM和精确的NN算法的召回效果差异

**Comment by prozhuchen** [comment]
> TDM和传统意义上的ANN检索算法的核心区别是，对“距离”的定义不一样。一般而言，ANN算法的目标是查找离Query向量距离最近的Item向量。这里的“距离”，是向量之间的距离度量（L2距离、内积距离、余弦距离等）。在推荐问题中，我们需要召回的是“用户最感兴趣的Item”。此时，如果使用ANN查询的方法来召回，一个基本的假设是，用户对Item的兴趣度量，可以表示成“用户向量”和“Item向量”的距离。在这样的逻辑之上，才会有具体的ANN算法的选择问题。回到TDM中，我们对“用户对Item的兴趣”度量本身进行了升级（使用复杂模型来计算兴趣度），因为“用户向量”到“Item向量”的距离这一方式过于简单，无法精准地预估用户兴趣分布。此时，传统的ANN检索方法不再适用，因为已经没有了明确的Query向量。所以，TDM使用树结构这种具有明确层次关系的索引结构，作为Item索引对召回进行加速。论文中有对比TDM和精确的NN算法的召回效果差异

论文中对比TDM和暴力检索的结果有些让人迷惑，理论上暴力检索应该是最好的（虽然慢）；我理解它那个图的意思是在同样的检索时间下。

**Comment by prozhuchen** [comment]
> 阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
> 我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
> 而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类

我猜他们真实使用的时候，可能最后一轮训练之后就不会重新聚类了，直接使用训练出来的结果？

**Comment by cuisonghui** [comment]
> > 阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
> > 我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
> > 而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类
> 
> 我猜他们真实使用的时候，可能最后一轮训练之后就不会重新聚类了，直接使用训练出来的结果？
嗯，你这么说感觉有些道理。
聚类决定了树结构，树结构决定了beamsearch的检索过程，即怎么剪枝，那树聚类的好坏就是决定最终效果的上限了，而树的聚类过程只是用模型产出的embedding通过距离对树进行重建(kmeans)，那这个过程感觉并没有比ann有很大的优势啊，好像优势仅在于user和item的之间相似度使用复杂模型进行表征。
我的理解不知道是不是太浅了。。。

**Comment by cuisonghui** [comment]
> > 阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
> > 我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
> > 而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类
> 
> 我猜他们真实使用的时候，可能最后一轮训练之后就不会重新聚类了，直接使用训练出来的结果？

嗯，你这么说感觉有些道理。
聚类决定了树结构，树结构决定了beamsearch的检索过程，即怎么剪枝，那树聚类的好坏就是决定最终效果的上限了，而树的聚类过程只是用模型产出的embedding通过距离对树进行重建(kmeans)，那这个过程感觉并没有比ann有很大的优势啊，好像优势仅在于user和item的之间相似度使用复杂模型进行表征。
我的理解不知道是不是太浅了。。。

**Comment by cuisonghui** [comment]
> TDM和传统意义上的ANN检索算法的核心区别是，对“距离”的定义不一样。一般而言，ANN算法的目标是查找离Query向量距离最近的Item向量。这里的“距离”，是向量之间的距离度量（L2距离、内积距离、余弦距离等）。在推荐问题中，我们需要召回的是“用户最感兴趣的Item”。此时，如果使用ANN查询的方法来召回，一个基本的假设是，用户对Item的兴趣度量，可以表示成“用户向量”和“Item向量”的距离。在这样的逻辑之上，才会有具体的ANN算法的选择问题。回到TDM中，我们对“用户对Item的兴趣”度量本身进行了升级（使用复杂模型来计算兴趣度），因为“用户向量”到“Item向量”的距离这一方式过于简单，无法精准地预估用户兴趣分布。此时，传统的ANN检索方法不再适用，因为已经没有了明确的Query向量。所以，TDM使用树结构这种具有明确层次关系的索引结构，作为Item索引对召回进行加速。论文中有对比TDM和精确的NN算法的召回效果差异

但是树的重聚类过程，使用的还是item向量，根据距离（L2距离、内积距离、余弦距离等）分成两类，重构树结构.

**Comment by zhuhan1236** [comment]
> > > 阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
> > > 我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
> > > 而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类
> > 
> > 
> > 我猜他们真实使用的时候，可能最后一轮训练之后就不会重新聚类了，直接使用训练出来的结果？
> 
> 嗯，你这么说感觉有些道理。
> 聚类决定了树结构，树结构决定了beamsearch的检索过程，即怎么剪枝，那树聚类的好坏就是决定最终效果的上限了，而树的聚类过程只是用模型产出的embedding通过距离对树进行重建(kmeans)，那这个过程感觉并没有比ann有很大的优势啊，好像优势仅在于user和item的之间相似度使用复杂模型进行表征。
> 我的理解不知道是不是太浅了。。。

树结构作为一种索引，其质量的好坏，确实对beamsearch检索和模型训练有影响，但只是影响最终效果的一方面，另一个重要的影响是检索模型的能力，及 user-node 兴趣度判别模型的精度。相比于ann方式普遍采用的向量距离度量，有很多兴趣度量能力更强的模型可以使用。理论上，TDM的框架中也能使用类似于HNSW这种层次化图的结构，但本质上的差异是，TDM对兴趣度量方式不做限制

**Comment by zhuhan1236** [comment]
> > TDM和传统意义上的ANN检索算法的核心区别是，对“距离”的定义不一样。一般而言，ANN算法的目标是查找离Query向量距离最近的Item向量。这里的“距离”，是向量之间的距离度量（L2距离、内积距离、余弦距离等）。在推荐问题中，我们需要召回的是“用户最感兴趣的Item”。此时，如果使用ANN查询的方法来召回，一个基本的假设是，用户对Item的兴趣度量，可以表示成“用户向量”和“Item向量”的距离。在这样的逻辑之上，才会有具体的ANN算法的选择问题。回到TDM中，我们对“用户对Item的兴趣”度量本身进行了升级（使用复杂模型来计算兴趣度），因为“用户向量”到“Item向量”的距离这一方式过于简单，无法精准地预估用户兴趣分布。此时，传统的ANN检索方法不再适用，因为已经没有了明确的Query向量。所以，TDM使用树结构这种具有明确层次关系的索引结构，作为Item索引对召回进行加速。论文中有对比TDM和精确的NN算法的召回效果差异
> 
> 但是树的重聚类过程，使用的还是item向量，根据距离（L2距离、内积距离、余弦距离等）分成两类，重构树结构.

这种通过聚类来实现树结构构建的方式，确实存在一定的局限性且不是理论最优的。关于树结构学习方面，我们后续又做了进一步的工作，具体的可以参考我们最新的工作[JTM](https://arxiv.org/abs/1902.07565)

**Comment by cuisonghui** [comment]
> > > TDM和传统意义上的ANN检索算法的核心区别是，对“距离”的定义不一样。一般而言，ANN算法的目标是查找离Query向量距离最近的Item向量。这里的“距离”，是向量之间的距离度量（L2距离、内积距离、余弦距离等）。在推荐问题中，我们需要召回的是“用户最感兴趣的Item”。此时，如果使用ANN查询的方法来召回，一个基本的假设是，用户对Item的兴趣度量，可以表示成“用户向量”和“Item向量”的距离。在这样的逻辑之上，才会有具体的ANN算法的选择问题。回到TDM中，我们对“用户对Item的兴趣”度量本身进行了升级（使用复杂模型来计算兴趣度），因为“用户向量”到“Item向量”的距离这一方式过于简单，无法精准地预估用户兴趣分布。此时，传统的ANN检索方法不再适用，因为已经没有了明确的Query向量。所以，TDM使用树结构这种具有明确层次关系的索引结构，作为Item索引对召回进行加速。论文中有对比TDM和精确的NN算法的召回效果差异
> > 
> > 
> > 但是树的重聚类过程，使用的还是item向量，根据距离（L2距离、内积距离、余弦距离等）分成两类，重构树结构.
> 
> 这种通过聚类来实现树结构构建的方式，确实存在一定的局限性且不是理论最优的。关于树结构学习方面，我们后续又做了进一步的工作，具体的可以参考我们最新的工作[JTM](https://arxiv.org/abs/1902.07565)

好的，谢谢您的回答，我继续学习研究研究。

> > > > 阿里妈妈之前分享过一次讲义，但是我还没仔细研究。
> > > > 我理解的大意思是ann是两段式的训练过程，embedding过程和使用embedding建索引是分开的。
> > > > 而tdm是联合训练的，但是我目前还不理解，这个联合是体现在什么地方，因为树的重新聚类过程也是使用模型产出的embedding进行聚类
> > > 
> > > 
> > > 我猜他们真实使用的时候，可能最后一轮训练之后就不会重新聚类了，直接使用训练出来的结果？
> > 
> > 
> > 嗯，你这么说感觉有些道理。
> > 聚类决定了树结构，树结构决定了beamsearch的检索过程，即怎么剪枝，那树聚类的好坏就是决定最终效果的上限了，而树的聚类过程只是用模型产出的embedding通过距离对树进行重建(kmeans)，那这个过程感觉并没有比ann有很大的优势啊，好像优势仅在于user和item的之间相似度使用复杂模型进行表征。
> > 我的理解不知道是不是太浅了。。。
> 
> 树结构作为一种索引，其质量的好坏，确实对beamsearch检索和模型训练有影响，但只是影响最终效果的一方面，另一个重要的影响是检索模型的能力，及 user-node 兴趣度判别模型的精度。相比于ann方式普遍采用的向量距离度量，有很多兴趣度量能力更强的模型可以使用。理论上，TDM的框架中也能使用类似于HNSW这种层次化图的结构，但本质上的差异是，TDM对兴趣度量方式不做限制

谢谢回答，我再好好体会体会。

**Comment by larsoncs** [comment]
我这里使用tree_cluster.py聚类之后，再次训练，发现recall降低很多啊，感觉是不是上面你们说到的，“”这种通过聚类来实现树结构构建的方式，确实存在一定的局限性且不是理论最优的“
