### ISSUE TITLE
blaze predictor_example failed

### ISSUE THREAD

**Issue by xxqcheers** [alibaba/x-deeplearning#275]
在linux 16.04 按照官方的说明，编译源码，执行demo的时候碰到错误

"
~/x-deeplearning/blaze/build/example/cpp目录下
执行
strace ./predictor_example ./sparse_qed ./model_blaze_optimized
报错信息
x-deeplearning/blaze/blaze/common/registry.h:44] key=Bridge not exist) = 84
x-deeplearning/blaze/blaze/api/cpp_api/predictor_manager_impl.cc:157] Create Model Predictor failed, ./model_blaze_optimized msg=[failed at operator.cc:119]op. op_type=Bridge ) = 190

[INFO ] [2019-09-29 17:02:44] [18687] [~/x-deeplearning/blaze/blaze/api/cpp_api/predictor.cc:133] New PredictorManager
[INFO ] [2019-09-29 17:02:44] [18687] [~/x-deeplearning/blaze/blaze/optimizer/optimizer.h:34] optimizer op num: 217 -> 217
[ERROR] [2019-09-29 17:02:44] [18687] [~/x-deeplearning/blaze/blaze/common/registry.h:44] key=Bridge not exist
[ERROR] [2019-09-29 17:02:44] [18687] [~/x-deeplearning/blaze/blaze/api/cpp_api/predictor_manager_impl.cc:157] Create Model Predictor failed, ./model_blaze_optimized msg=[failed at operator.cc:119]op. op_type=Bridge 
Segmentation fault (core dumped)
"

**Comment by WellsRevive** [comment]
Bridge要在GPU设备执行，是不是指定错设备了？

**Comment by xxqcheers** [comment]
> Bridge要在GPU设备执行，是不是指定错设备了？
看样子是的，我在CPU设备上运行的
