### ISSUE TITLE
TDM论文中，非叶子节点的embedding是怎么得来的

### ISSUE THREAD

**Issue by prozhuchen** [alibaba/x-deeplearning#276]
如题，求问

**Comment by cuisonghui** [comment]
从代码中，非叶子节点在构建树的时候，会通过叶子节点构造出来，在模型训练的时候，通过上溯采样，非叶子节点会成为正负样本的label node,可以看文档中给的图，也就是node embedding，应该是从这里得到的。
我还在看代码，可能当前理解的不是很到位。

**Comment by zhuhan1236** [comment]
非叶子节点的embedding是随机初始化后，通过模型训练得到的，和叶节点embedding一致

**Comment by prozhuchen** [comment]
> 非叶子节点的embedding是随机初始化后，通过模型训练得到的，和叶节点embedding一致

正解，感谢

**Comment by songruifei** [comment]
> > 非叶子节点的embedding是随机初始化后，通过模型训练得到的，和叶节点embedding一致
> 
> 正解，感谢

您好，非叶子节点拿什么去做嵌入，是用节点id嵌入吗？还是unit_id_expand嵌入？

**Comment by songruifei** [comment]
> 非叶子节点的embedding是随机初始化后，通过模型训练得到的，和叶节点embedding一致

您好，非叶子节点拿什么去做嵌入，是用节点id嵌入吗？还是unit_id_expand嵌入？

**Comment by zhuhan1236** [comment]
> > 非叶子节点的embedding是随机初始化后，通过模型训练得到的，和叶节点embedding一致
> 
> 您好，非叶子节点拿什么去做嵌入，是用节点id嵌入吗？还是unit_id_expand嵌入？

非叶节点是拿节点本身的id做嵌入的

**Comment by larsoncs** [comment]
非叶节点，只有本身的ID  embedding吗？

**Comment by zhuhan1236** [comment]
> 非叶节点，只有本身的ID embedding吗？

是的，只会有本身ID对应的单独的embedding

**Comment by pengyunshan** [comment]
非叶子节点是通过模型训练得到的的话？每一轮不是要重新kmeans聚类成树吗？聚类之后非叶子节点就变了呀，那多次训练的意义是啥呢？
