### ISSUE TITLE
tdm单机试验使用cpu训练，[WARNING]: no gradient found for var，正常吗,loss也一直再降

### ISSUE THREAD

**Issue by cuisonghui** [alibaba/x-deeplearning#280]
[INFO] start_sample_layer -1
[INFO] level 0, layer_counts.push_back: 0
[INFO] level 1, layer_counts.push_back: 1
[INFO] level 2, layer_counts.push_back: 2
[INFO] level 3, layer_counts.push_back: 3
[INFO] level 4, layer_counts.push_back: 4
[INFO] level 5, layer_counts.push_back: 5
[INFO] level 6, layer_counts.push_back: 6
[INFO] level 7, layer_counts.push_back: 7
[INFO] level 8, layer_counts.push_back: 8
[INFO] level 9, layer_counts.push_back: 9
[INFO] level 10, layer_counts.push_back: 10
[INFO] level 11, layer_counts.push_back: 11
[INFO] level 12, layer_counts.push_back: 12
[INFO] level 13, layer_counts.push_back: 13
fea_groups [20, 20, 10, 10, 2, 2, 2, 1, 1, 1] total_group_length 69 eb_dim 24
call FullyConnected3D
in FullyConnected3D use prelu
call FullyConnected3D
in FullyConnected3D use prelu
if mx.symbol.FullyConnected
if self.use_batch_norm:
if self.active_op == 'prelu':
if mx.symbol.FullyConnected
if self.use_batch_norm:
if self.active_op == 'prelu':
if mx.symbol.FullyConnected
if self.use_batch_norm:
if self.active_op == 'prelu':
if mx.symbol.FullyConnected
[WARNING]: no gradient found for var:bn_1_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_1_d_moving_var under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_2_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_2_d_moving_var under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_3_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_3_d_moving_var under scope: , maybe not used?
>>>>>>>>>>>> 0 >>>>>>>>>>>
#### loss:[1.2097614]
save checkpoint at global_step[25], ckpt version[ckpt-..................25]
result is None, finished success.
start put item_emb
GetLatestCheckpoint [/home/mi/workspace/tdm/data/tdm_mock_train/checkpoint//ckpt-..................25]
Start convert [item_emb], part[0]
finish convert [item_emb], part[0], id_cnt[15580], duration[162ms]
finish convert ckpt[/home/mi/workspace/tdm/data/tdm_mock_train/checkpoint/], duration[163ms]
rm -f data/item_emb
hadoop fs -get /home/mi/workspace/tdm/data/emb_converted/item_emb data/item_emb
sed -i 's/..//' data/item_emb
hadoop fs -put -f data/item_emb /home/mi/workspace/tdm/data/emb_converted
finish put item_emb
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored

**Comment by cuisonghui** [comment]
@songyue1104 @lovickie @largestone1982 @shanshanpt

**Comment by lovickie** [comment]
no gradient found for var的mxnet提示可以忽略。
loss趋势下降是正常的，但结尾突然抬升可能不太正常，检查一下数据。
另外tdm的模型效果最终要看predict的pr，详见算法描述。

**Comment by cuisonghui** [comment]
嗯，好的，谢谢，我随后用真实数据分布式训练试一试。
