### ISSUE TITLE
xdl 训练如何做到起两个线程跑同一个图

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#282]
我在这边每个机器上有2个GPU，想要每个机器上起两个线程训练，跑同一个图，我想问哈，可不可以起两个线程跑同一个图，然后每个线程的图放到不同的GPU上跑，这个如何做呢。我这边发现是失败的。我这边报了这个错误。。
File "/usr/local/lib/python2.7/dist-packages/xdl/python/backend/tf/tf_hook.py", line 52, in get_variable
    raise Exception("must set reuse flag to enable reuse")。
如果同时跑一个图，我想问哈是不是不是线程安全的呢。。

**Comment by songyue1104** [comment]
看你的描述是想做数据并行，并且在同一个进程里用两个线程来驱动，这样的话你需要两个dataio，两个相同的graph（placement到不同的gpu上），在tf里开启variable reuse，创建两个xdl session，放到两个线程里run，我理解这样做和起两个worker做在性能上不会有什么提升，而且代码会变复杂

**Comment by songziqin** [comment]
好的。谢谢。理解了。。
