### ISSUE TITLE
xdl.embedding 参数设置为'GPU'，比设置为'CPU'还要慢,发现GPU的KSum op后面空了0.1秒

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#287]
刚开始这边设置xdl.embedding参数为CPU，我看了timeline的，比较耗时的是两个操作，一个是KSum另外一个是KSumGrad.但是当我设置xdl.embedding参数为GPU的时候，这两个操作貌似时间更长了，我想问哈，按理论上来说，用GPU应该更快才对呀。。

**Comment by songziqin** [comment]
![屏幕快照 2019-10-23 上午11 13 01](https://user-images.githubusercontent.com/16793507/67353862-38454f80-f586-11e9-8ff5-1a58cdef1dd3.png)

**Comment by songziqin** [comment]
![屏幕快照 2019-10-23 下午4 38 34](https://user-images.githubusercontent.com/16793507/67374441-c1bf4680-f5b3-11e9-855e-95d452b95151.png)

**Comment by songyue1104** [comment]
放到gpu上要考虑计算/通信比，只有计算/通信比高的op才有放到gpu上的价值
