### ISSUE TITLE
tdm中关于样本扩充配置的疑问以及训练的batchsize的对应关系

### ISSUE THREAD

**Issue by cuisonghui** [alibaba/x-deeplearning#293]
tdm.json的中配置
"tdmop_layer_counts": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,19,22,25,30,76,200", 
我的树大概是21层，如下所示，那基本一个样本肯定会被扩充成200多个样本吗？
我大概一亿的原始样本，理论上来说就被扩充成200多亿的样本吗？
这个配置请问怎么调整比较合适，感觉样本膨胀太大了。
那么"train_batch_size"对应的是原始样本还是扩充后的样本?

**Comment by zhuhan1236** [comment]
> tdm.json的中配置
> "tdmop_layer_counts": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,19,22,25,30,76,200",
> 我的树大概是21层，如下所示，那基本一个样本肯定会被扩充成200多个样本吗？
> 我大概一亿的原始样本，理论上来说就被扩充成200多亿的样本吗？
> 这个配置请问怎么调整比较合适，感觉样本膨胀太大了。
> 那么"train_batch_size"对应的是原始样本还是扩充后的样本?

按照这个配置，一个原始样本确实会被扩展成200多个样本，train_batch_size对应的是扩充后的样本数量。关于扩充比例的问题，实际上大部分的召回模型训练，都会有比较大的负采样比，如果觉得负采样比太大导致训练样本过多，可以适当将每层的负采样数量调小

**Comment by cuisonghui** [comment]
@zhuhan1236  好的，谢谢，另外还有一个问题，如果原始样本量比较大，我目前的资源无法满足训练要求，请问怎么在减少原始样本量的基础上，而不损失太多模型收益，并且也能保证对item的覆盖比较广。这方面是否能给一些建议，我目前是随机选取一部分比例的用户，但是这样会损失很多item。

**Comment by zhuhan1236** [comment]
> @zhuhan1236 好的，谢谢，另外还有一个问题，如果原始样本量比较大，我目前的资源无法满足训练要求，请问怎么在减少原始样本量的基础上，而不损失太多模型收益，并且也能保证对item的覆盖比较广。这方面是否能给一些建议，我目前是随机选取一部分比例的用户，但是这样会损失很多item。

除了以user为粒度随机选取以外，还可以以整体原始样本为粒度进行随机选取，或者以item作为样本的频次做一个分布来挑选，以增加冷门item样本被保留的概率

**Comment by cuisonghui** [comment]
好的，谢谢解答。
