### ISSUE TITLE
tdm分布式训练，worker怎么调整并发度，以提高cpu利用率

### ISSUE THREAD

**Issue by cuisonghui** [alibaba/x-deeplearning#294]
请问怎么调整worker并发度，目前cpu利用率很低，调整tdm.json中的"train_threads"也不起作用，
还是说需要自己开发支持并发操作？
如果实在不行就一台机器部署多个worker了

**Comment by lovickie** [comment]
train_threads 只是IO的线程数，组batch速度够用就行了开多了也没用。如果用gpu训练的话，cpu的占用率不会很高（500% maybe）。如果用cpu训练的话，看看调度起来的docker分配的cpu数目，该配置在config.train.json里的worker和ps的cpu数目，可以check看看生效了没有

**Comment by cuisonghui** [comment]
@lovickie  我是手工启动的分布式集群，应该是没有使用到config.train.json这个文件，不知道这些参数是否需要单独配置。
手动启动命令如下:
worker
nohup python train.py  --task_name=worker  --run_mode=distributed --ckpt_dir=hdfs://****/tdm/tdm_mock_train/checkpoint --task_index=$1 --task_num=$2 --zk_addr=zfs://******/tdm/scheduler 1>train.log/worker_$1.log 2>&1 &

ps server
nohup python train.py  --task_name=ps --task_index=$1 --zk_addr=zfs://*****/tdm/scheduler 1>train.log/ps_server_$1.log 2>&1 &

ps scheduler

nohup python train.py --task_name=scheduler --zk_addr=zfs://*****/tdm/scheduler --ps_num=4 --ps_cpu_cores=2 --ps_memory_m=8000 --ckpt_dir=hdfs://*****/tdm/tdm_mock_train/checkpoint 1>train.log/ps_scheduler.log 2>&1 &

**Comment by lazy2panda** [comment]
> train_threads 只是IO的线程数，组batch速度够用就行了开多了也没用。如果用gpu训练的话，cpu的占用率不会很高（500% maybe）。如果用cpu训练的话，看看调度起来的docker分配的cpu数目，该配置在config.train.json里的worker和ps的cpu数目，可以check看看生效了没有

我是用的cpu在local模式下运行的，但是cpu也是占不满，大概1000%左右，docker并没有限制cpu数量，物理机有32核，调整了config.train.json里的worker和ps的cpu数目，还是这样，请问有可能是什么原因呢？ @lovickie

**Comment by lovickie** [comment]
> > train_threads 只是IO的线程数，组batch速度够用就行了开多了也没用。如果用gpu训练的话，cpu的占用率不会很高（500% maybe）。如果用cpu训练的话，看看调度起来的docker分配的cpu数目，该配置在config.train.json里的worker和ps的cpu数目，可以check看看生效了没有
> 
> 我是用的cpu在local模式下运行的，但是cpu也是占不满，大概1000%左右，docker并没有限制cpu数量，物理机有32核，调整了config.train.json里的worker和ps的cpu数目，还是这样，请问有可能是什么原因呢？ @lovickie

恩，执行流程中，潮汐搬的在推拉数据与计算中交替，因此cpu利用率是有瓶颈的。代码级优化的手段很多，我们内部正在尝试一些场景下的优化策略，成熟之后会开放出来交流一下。
