### ISSUE TITLE
tdm手工分布式模式训练，训练到后半段时间，内存占用会持续上涨，导致内存耗尽，worker卡住。

### ISSUE THREAD

**Issue by cuisonghui** [alibaba/x-deeplearning#295]
使用的是tdm_ub_att_ubuntu中的train.py进行的训练,使用的是xdl1.2版本。
其中代码只改动了一个参数:
### 把embedding函数的feature_dim参数从50000调整到800000

我发现，在训练的后半段时间内存会开始持续上涨，大概是下图中的样子。
图中标识 训练1和训练2，其中训练2不能正常训练完。
![TDM001](https://user-images.githubusercontent.com/8772285/68556426-337d0880-046d-11ea-902e-fd77a93999b0.jpg)

训练1最后可以完成训练,因为最终训练完也没有把内存打满，可以正常完成。
训练2因为训练样本更多，需要的时间更长一些，所以一直到晚上8点多，内存耗尽了，所有worker都卡住，checkpoint的最终保存也停留在那个时间点
两次训练大概都是在训练过程的过半段，大概是训练到3/5的时候，就开始内存持续增加
请问这个内存持续增加是正常现象，还是有问题呢?

还有遇到这种问题怎么追查，不知道怎么使用gdb追查python调起的c++程序，目前无从调试。

@lovickie @zhuhan1236 @songyue1104

**Comment by lovickie** [comment]
core是一样查的，打开ulimit -c unlimited 之后，在core文件系统路径下会生成core
gdb python xxx即可调试一样的。
内部曾经长时间跑过训练，worker内存上涨的问题都没遇到过。。。

**Comment by cuisonghui** [comment]
@lovickie  好吧，我再观察观察。

**Comment by lovickie** [comment]
仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。

**Comment by cuisonghui** [comment]
@lovickie  好的，谢谢指导，我随后调试一下这个问题，我现在还在定位模型转换成blaze后的问题。

**Comment by lovickie** [comment]
> 仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
> blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
> capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。

另外，tdm的predict要谨防队列长度过小，导致卡住的问题。因为tdm的predict比较特殊，有个样本扩展并且不释放重新回流到队列里的逻辑。该队列，既接受正常读样本获得的sg，又接受单轮预测后回流的sg，如果队列满了，就会卡住。data_io.pause设置的是predict时sg队列读取sg的最大数目，也是为了防止sg队列卡住。

**Comment by lovickie** [comment]
> @lovickie 好的，谢谢指导，我随后调试一下这个问题，我现在还在定位模型转换成blaze后的问题。

这个问题跟速度有关，刚好我们内部的场景中一直复现不出这个条件，耽误了问题的定位。

**Comment by cuisonghui** [comment]
> > 仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
> > blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
> > capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。
> 
> 另外，tdm的predict要谨防队列长度过小，导致卡住的问题。因为tdm的predict比较特殊，有个样本扩展并且不释放重新回流到队列里的逻辑。该队列，既接受正常读样本获得的sg，又接受单轮预测后回流的sg，如果队列满了，就会卡住。data_io.pause设置的是predict时sg队列读取sg的最大数目，也是为了防止sg队列卡住。

嗯，之前在看dataio的代码，predict确实有样本回流的特殊处理。
您说的队列长度，是这里控制的吧
`sgroup_q_ = new BlockingQueue<SGroup *>(schema_->batch_size_*threads_read_);`
对应的tdm.json中应该是"predict_batch_size"这个参数吧，
嗯，那我就是因为这个问题卡住的，
因为我的"predict_batch_size"设置的是100，而"predict_io_pause_num"是10000，就会卡住。
然后我把predict_io_pause_num改成100就没问题了。

**Comment by cuisonghui** [comment]
> > @lovickie 好的，谢谢指导，我随后调试一下这个问题，我现在还在定位模型转换成blaze后的问题。
> 
> 这个问题跟速度有关，刚好我们内部的场景中一直复现不出这个条件，耽误了问题的定位。

速度值得是训练速度，还是取样本的io速度呢

**Comment by cuisonghui** [comment]
> 仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
> blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
> capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。

周末我进行离线训练，发现内存持续增长的问题，可以直接重现，不用等到训练后半段。
因为我调整了负样本采样率，导致模型训练的时间更长，内存不够，worker直接卡住，我把所有进程全部杀掉，然后从出问题之前的checkpoint恢复，每个worker样本只设置几万，也就是把没训练完的样本训练完。这个时候观察，worker启动起来以后，内存就开始持续增长，而不是像之前的后半段才开始。几万样本实际上很快就能训练完，但是观察worker，成功训练完几万样本后，checkpoint也随即保存到hdfs，但是worker不停止，会持续一个多年小时，一直在训练，loss一直在打印，内存持续增长，我很迷惑这个过程中，训练的样本从哪里来的

**Comment by cuisonghui** [comment]
> 仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
> blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
> capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。

注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。
这句话没太理解。

batch指的是train_batch_size个样本吗，还是
data_io.cc中DataIO::DoPack函数下面代码:

....
`if (!RunOps(sgroup)) {
....
std::vector<Batch *> batchs = packer->Run(sgroup);
....
`
我的理解sgroup应该对应的是一个原始样本,然后经过RunOps，会变成一个样本+这个样本的扩充样本就变成了std::vector<Batch *> batchs

**Comment by cuisonghui** [comment]
> 仔细检查了代码，内存“泄漏”可能是因为IO缓存的 sample group 队列默认设置在 tdm 这种样本高比例扩展的场景中不合适。
> blaze-fix-v1.2分支给data_io提供 sgroup_queue_capacity(capacity) 的接口，注意IO的多线程共享该一个队列。
> capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。注意在自己的场景中，一个batch通常由最多最少几个sample_group组成。

>  capacity的设置，下限要考虑IO读取样本速度能否匹配得上训练速度，上限考虑的是内存的占用。

**Comment by cuisonghui** [comment]
sgroup_queue_capacity()使用默认的配置，目前内存抑制效果很明显，分布式训练速度基本不受影响
![1576115077980](https://user-images.githubusercontent.com/8772285/70888984-845bc000-201c-11ea-909b-e60b133b705a.jpg)
