### ISSUE TITLE
稀疏特征如何在线性模型中进行组合排列？

### ISSUE THREAD

**Issue by kimi132009** [alibaba/x-deeplearning#296]
我想用xdl训练deepFm模型，稀疏特征可以按照教程转成embedding喂给dnn，但是FM部分的一阶特征还是需要原始的稀疏特征进行训练，请问在xdl里面是如何处理稀疏特征的排列和线性模型表达的？
xdl的文本格式是下面这样的
# sample id        | group id   | sparse                                       | dense                      | label | timestamp
7859345_420968_1007|user_3423487|clk_14@32490:1.0,32988:2.0;prefer@323423,32342|qscore@0.8,0.5;ad_price@33.8|0.0,1.0|1544094136

还是像tensorflow那样转成libsvm格式么？还是有其他方法？

**Comment by songyue1104** [comment]
XDL提供了标准的SparseTensor表示稀疏特征，目前XDL对稀疏特征的操作仅限于embedding，如果有更多的需求可以将SparseTensor的几个成员tensor传进tf或mxnet后端进行处理

**Comment by kimi132009** [comment]
@songyue1104 那请问一下，现在咱们这个SparseTensor里面的dense_shape是如何确定的？是自动对所有数据进行统计还是需要我们自己人为设定？

**Comment by songyue1104** [comment]
dense shape不需要指定，目前也没有用到

**Comment by supersush** [comment]
想问下，在做embedding的时候，value是如何处理的，比如clk_14@32490:1.0,32988:2.0 这里边的1.0和2.0是如何加入embedding中的？ @songyue1104
