### ISSUE TITLE
请问tdm线下生成的文件是什么意思呢？

### ISSUE THREAD

**Issue by andrew-zzz** [alibaba/x-deeplearning#309]
线上servering部分我们公司不支持,可能要inference部分定制,但是不知道以下文件表示的含义 所以无法定制解析inference过程
TDM模型通过XDL线下训练后产生的数据有：
原始 TDM 树索引数据，userbehavior_tree.pb  这个是din模型的pb文件？
原始 TDM 模型数据，dense.txt、graph.txt、item_emb、sparse.txt。这些文件是干什么的？

**Comment by zhuhan1236** [comment]
> 线上servering部分我们公司不支持,可能要inference部分定制,但是不知道以下文件表示的含义 所以无法定制解析inference过程
> TDM模型通过XDL线下训练后产生的数据有：
> 原始 TDM 树索引数据，userbehavior_tree.pb 这个是din模型的pb文件？
> 原始 TDM 模型数据，dense.txt、graph.txt、item_emb、sparse.txt。这些文件是干什么的？

userbehavior_tree.pb是树结构定义
dense.txt是网络dense部分参数
graph.txt是整个计算图及参数
item_emb是ID -> embedding的映射文件
sparse.txt是sparse部分的描述文件

**Comment by andrew-zzz** [comment]
> > 线上servering部分我们公司不支持,可能要inference部分定制,但是不知道以下文件表示的含义 所以无法定制解析inference过程
> > TDM模型通过XDL线下训练后产生的数据有：
> > 原始 TDM 树索引数据，userbehavior_tree.pb 这个是din模型的pb文件？
> > 原始 TDM 模型数据，dense.txt、graph.txt、item_emb、sparse.txt。这些文件是干什么的？
> 
> userbehavior_tree.pb是树结构定义
> dense.txt是网络dense部分参数
> graph.txt是整个计算图及参数
> item_emb是ID -> embedding的映射文件
> sparse.txt是sparse部分的描述文件

感谢大佬
