### ISSUE TITLE
TDM serving for java?

### ISSUE THREAD

**Issue by zscwind** [alibaba/x-deeplearning#311]
TDM serving is just for C++。How to use tdm in java?

**Comment by zscwind** [comment]
TDM serving is just for C++。How to use tdm in java?

**Comment by zscwind** [comment]
TDM serving is just for C++。How to use tdm in java?

**Comment by zhuhan1236** [comment]
> TDM serving is just for C++。How to use tdm in java?

Currently, TDM serving doesn't support java. To use TDM in java, you should write your own tree retrieval code and import blaze in java for network inference.
