### ISSUE TITLE
DIN的paper提到的自适应正则看代码中没有体现呀

### ISSUE THREAD

**Issue by zhenghang** [alibaba/x-deeplearning#32]
DIN的paper提到的自适应正则看代码中没有体现呀，有看到Dice中有parametric_relu方法，没有看到对特征频次变量更新的代码。

**Comment by zhougr1993** [comment]
请参考这里的回答 https://github.com/zhougr1993/DeepInterestNetwork/issues/10
如我们在paper里所说MBA-Reg是一个针对规模较大的数据训练时考虑到L2正则计算开销的算法。MBA-Reg是和L2正则近似的，在公开的小数据集上用L2正则就可以了，同时公开的数据集的特征ID总量也不是特别大，过拟合的问题没有很严重，所以我们没有报告正则的实验。
在我们的生产数据集上有的特征比如ItemID维度是非常大的，同时样本量巨大，因此我们使用了MBA-Reg。相关的代码就没有在这个面向公开数据集的代码里给出。

**Comment by zhenghang** [comment]
感谢回复，这块能分享一下具体在tensorflow中如何实现的吗

**Comment by zhenghang** [comment]
感谢大神，已基本沟通清楚

**Comment by zhenghang** [comment]
后续有进展，我在这里同步

**Comment by kobe0849** [comment]
> 后续有进展，我在这里同步

具体如何实现方案有同步吗

**Comment by codefish1990** [comment]
求如何实现的？

**Comment by codefish1990** [comment]
论文中DIN主要有3个改进（attention；自适应正则；Dice），请问主要的提升来自于哪个改进？
另外，自适应正则是如何实现？

**Comment by xzy007** [comment]
求更新DIN的mba-reg实现细节
