### ISSUE TITLE
data_io加载hdfs报错

### ISSUE THREAD

**Issue by nonunu** [alibaba/x-deeplearning#337]
loadFileSystems error:
(unable to get root cause for java.lang.NoClassDefFoundError)
(unable to get stack trace for java.lang.NoClassDefFoundError)
hdfsBuilderConnect(forceNewInstance=0, nn=hacluster, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
(unable to get root cause for java.lang.NoClassDefFoundError)
(unable to get stack trace for java.lang.NoClassDefFoundError)
2020-07-17 12:05:09.198791:   /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hacluster

**Comment by Ru-Xiang** [comment]
能麻烦介绍下怎么解决的吗

**Comment by ideal-lee** [comment]
> 能麻烦介绍下怎么解决的吗

您好，能问下问题解决了吗，感谢！

**Comment by ideal-lee** [comment]
> loadFileSystems error:
> (unable to get root cause for java.lang.NoClassDefFoundError)
> (unable to get stack trace for java.lang.NoClassDefFoundError)
> hdfsBuilderConnect(forceNewInstance=0, nn=hacluster, port=0, kerbTicketCachePath=(NULL), userName=(NULL)) error:
> (unable to get root cause for java.lang.NoClassDefFoundError)
> (unable to get stack trace for java.lang.NoClassDefFoundError)
> 2020-07-17 12:05:09.198791: /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hacluster

您好，能问下问题解决了吗？感谢！
