### ISSUE TITLE
使用mxnet报错

### ISSUE THREAD

**Issue by AlexanLee** [alibaba/x-deeplearning#34]
mxnet按照编译步骤安装成功后，使用测试的例子，还是报如下错误：
AttributeError: 'module' object has no attribute 'mxnet_wrapper'

为什么了？

**Comment by songyue1104** [comment]
编译选项是否设置了-DMXNET_BACKEND=1，wiki里给的是tensorflow作为后端的例子

**Comment by AlexanLee** [comment]
> 编译选项是否设置了-DMXNET_BACKEND=1，wiki里给的是tensorflow作为后端的例子

可能是这个问题。那同时用两个后端的话，是把这个两个都加上就行？

**Comment by zhangpeng-fei** [comment]
你好，我这边也遇到这个问题。我加了-DMXNET_BACKEND=1 。
问一下。有没有已经安装好的mxnet的镜像呢？

**Comment by 1980695671** [comment]
DMXNET_BACKEND=1 
请问这句话加在哪里，我是pip安装的mxnet

**Comment by zhangpeng-fei** [comment]
> DMXNET_BACKEND=1
> 请问这句话加在哪里，我是pip安装的mxnet
这个是在编译mxnet库的时候加的参数。你大可不必这样编译麻烦，官方文档有提供已经安装了mxnet的镜像。

**Comment by zhangpeng-fei** [comment]
> DMXNET_BACKEND=1
> 请问这句话加在哪里，我是pip安装的mxnet

这个是在编译mxnet库的时候加的参数。你大可不必这样编译麻烦，官方文档有提供已经安装了mxnet的镜像。
