### ISSUE TITLE
Embedding 接口问题， 不同特征hash空间需要无冲突么？

### ISSUE THREAD

**Issue by Ru-Xiang** [alibaba/x-deeplearning#344]
不同特征，如果公用一个name的 embedding空间，那么他们的值是不是就不能有冲突？

**Comment by zhangyuhanjc** [comment]
我这里测试的是 如果只是离线训练 离线评测的话 ，只要每个特征有自己的 name 就没问题， 但如果你要对模型进行blaze转换  然后tdmServing 就会有问题，原因：tdm训练时使用不同特征使用不用的embding矩阵 但是多个embedding转换成tmdServing矩阵二进制文件时 变成了一个“矩阵”，而不同特征之间的id相互覆盖 ， 我的解决办法是给不同特征的特征值 加上offset
