### ISSUE TITLE
xdl的教程和镜像不一致太多了

### ISSUE THREAD

**Issue by githcx** [alibaba/x-deeplearning#36]
这个文档质量太低了，至少有以下问题：
1) 文档中出现WORK_PATH叙述中错位
2) 镜像下载后大量的基础库比如sklearn，mxnet报错，纯小白无法顺利安装
3) 关键的修改位置描述含混不清
4) 下的镜像tag是tf12，结果镜像里的train.py脚本里面根本没有对tensorflow的使用

可能是我我段位不够吧，有跑通脚本的朋友可以在issues里分享一下经验。

**Comment by songyue1104** [comment]
你好，1和3麻烦指出一下具体的位置，2请提供具体的出错信息，4目前镜像里没有包含测试代码，你说的train.py具体是哪个目录下的

**Comment by githcx** [comment]
https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)

> 你好，1和3麻烦指出一下具体的位置，2请提供具体的出错信息，4目前镜像里没有包含测试代码，你说的train.py具体是哪个目录下的

问题1，请看下TDM页面:https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)

1) 之前说的WORKPATH在“准备工作目录”这部分应该是在docker宿主机上
2) 而在接下来的“进入docker”、"编译安装TDM"、“分隔数据集，生成原始样本csv”等接下来的部分中，仿佛是引用的进入镜像（registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-mxnet1.3）后镜像中的WORKPATH才在下文中能说通。

WORKPATH 在 1) 和 2)中分别是在宿主机和客户机镜像的运行容器中，此为1的不一致。

**Comment by githcx** [comment]
> 你好，1和3麻烦指出一下具体的位置，2请提供具体的出错信息，4目前镜像里没有包含测试代码，你说的train.py具体是哪个目录下的

问题3，请看下TDM页面:https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)

“训练”的部分，看以下这行
   vim train.py    # 修改train的代码中DataIO的参数 namenode="hdfs://your/namenode/hdfs/path:9000"

这个namenode的定义：namenode="hdfs://your/namenode/hdfs/path:9000"
让人无法参照来写，因为不清楚namenode hdfs path是什么概念。最终搜了网上hadoop的一些说法填成了http://localhost:9000和hdfs://localhost:9000这两种进行尝试，最终没有能跑通脚本，都有java的异常。

**Comment by githcx** [comment]
> 你好，1和3麻烦指出一下具体的位置，2请提供具体的出错信息，4目前镜像里没有包含测试代码，你说的train.py具体是哪个目录下的

问题2 应该是没有按照tdm页面的示例的mxnet版本的镜像，忽略了xdl文档和tdm的镜像差异造成的，应该也造成了问题4。

总之文档感觉叙述的并不是很符合一般人的操作顺序，特别是问题1让人做着做着就错乱了。

**Comment by songyue1104** [comment]
@githcx  TDM的训练流程比较复杂，再加上涉及到docker和hdfs的使用，用户使用起来有一定的门槛。我们会针对上面的问题再整理一下相关文档，谢谢反馈

**Comment by githcx** [comment]
> @githcx TDM的训练流程比较复杂，再加上涉及到docker和hdfs的使用，用户使用起来有一定的门槛。我们会针对上面的问题再整理一下相关文档，谢谢反馈

好的，docker没用过，所以学习花费了一定时间，镜像也是配置的过程查阅相关的hadoop、jdk安装等东西，分散了注意力，看看拿mxnet镜像重新配置一下，能不能开始训练。

**Comment by githcx** [comment]
> @githcx TDM的训练流程比较复杂，再加上涉及到docker和hdfs的使用，用户使用起来有一定的门槛。我们会针对上面的问题再整理一下相关文档，谢谢反馈

mxnet cpu版本的镜像已经下载并重新配置，TDM训练部分的train.py脚本仍然无法跑通，现象是以下这句会出现core dump：
data_io = xdl.DataIO("tdm", file_type=xdl.parsers.txt, fs_type=xdl.fs.hdfs, namenode="hdfs:/localhost:9000", enable_state=False)

**Comment by lovickie** [comment]
> > @githcx TDM的训练流程比较复杂，再加上涉及到docker和hdfs的使用，用户使用起来有一定的门槛。我们会针对上面的问题再整理一下相关文档，谢谢反馈
> 
> mxnet cpu版本的镜像已经下载并重新配置，TDM训练部分的train.py脚本仍然无法跑通，现象是以下这句会出现core dump：
> data_io = xdl.DataIO("tdm", file_type=xdl.parsers.txt, fs_type=xdl.fs.hdfs, namenode="hdfs:/localhost:9000", enable_state=False)

举个例子，如果UPLOAD_HDFSPATH='hdfs://aa.com:pp/aa/mock_upload'    # 指定样本及树的产出目录
那么namenode配置成hdfs://aa.com:pp

**Comment by lovickie** [comment]
> https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)
> 
> > 你好，1和3麻烦指出一下具体的位置，2请提供具体的出错信息，4目前镜像里没有包含测试代码，你说的train.py具体是哪个目录下的
> 
> 问题1，请看下TDM页面:https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)
> 
> 1. 之前说的WORKPATH在“准备工作目录”这部分应该是在docker宿主机上
> 2. 而在接下来的“进入docker”、"编译安装TDM"、“分隔数据集，生成原始样本csv”等接下来的部分中，仿佛是引用的进入镜像（registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-mxnet1.3）后镜像中的WORKPATH才在下文中能说通。
> 
> WORKPATH 在 1) 和 2)中分别是在宿主机和客户机镜像的运行容器中，此为1的不一致。

初次试验建议像wiki一样用--volumn参数，将路径挂载到docker中，使得docker内外路径一致，会更方便些。

**Comment by jlinleung** [comment]
@songyue1104 @lovickie 
运行 严格按照教程操作，执行python train.py --run_mode=local --config=config.train.json的过程一直报段错误，Load successfully, leaf node count:Segmentation fault。看了源码没什么问题，请问会是什么原因？

**Comment by ZWhangH** [comment]
> @songyue1104 @lovickie
> 运行 严格按照教程操作，执行python train.py --run_mode=local --config=config.train.json的过程一直报段错误，Load successfully, leaf node count:Segmentation fault。看了源码没什么问题，请问会是什么原因？
解决了吗，大哥，我也出现同样问题了？

**Comment by ZWhangH** [comment]
> 经

请问怎么避免core dump这个问题，不用hadoop

**Comment by jump2** [comment]
@lovickie @songyue1104  我hadoop安装在宿主机上，所以namenode配置成hdfs://172.17.0.1:9000，但是依然报如下错误

root@ubuntuyimi:/home/yimi/tdm_mock# python train.py --run_mode=local --config=config.train.json
config: {u'ps': {u'instance_num': 16, u'memory_m': 64000, u'gpu_cores': 0, u'cpu_cores': 16}, u'dependent_dirs': u'/home/yimi/tdm_mock', u'script': u'train.py', u'worker': {u'instance_num': 20, u'memory_m': 100000, u'gpu_cores': 2, u'cpu_cores': 46}, u'max_local_failover_times': 3, u'auto_rebalance': {u'enable': u'false'}, u'min_finish_worker_rate': 100, u'max_failover_times': 3, u'job_name': u'xdl_tdm', u'docker_image': u'registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-mxnet1.3', u'checkpoint': {u'output_dir': u'hdfs://172.17.0.1:9000/hdfs/path/tdm_mock_train/checkpoint'}}
mv data/ub_tree.pb data/ub_tree.pb.bak
hadoop fs -get hdfs://172.17.0.1:9000/dist_tree/upload/hdfs/path/tree_data/data/userbehavoir_tree.pb data/ub_tree.pb
2019-09-27 07:47:03,964 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
**Load successfully, leaf node count:Environment variable CLASSPATH not set!
getJNIEnv: getGlobalJNIEnv failed
2019-09-27 07:47:11.274831: F /home/yue.song/XDL-OpenSource-master/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hdfs://172.17.0.1:9000**
Aborted (core dumped)

**Comment by larsoncs** [comment]
@jump2 ,楼上描述的问题解决了么？我也遇到同样的问题，master/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hdfs://xxxx:port/

**Comment by luerer** [comment]
@songyue1104 请问

> > @githcx TDM的训练流程比较复杂，再加上涉及到docker和hdfs的使用，用户使用起来有一定的门槛。我们会针对上面的问题再整理一下相关文档，谢谢反馈
> 
> mxnet cpu版本的镜像已经下载并重新配置，TDM训练部分的train.py脚本仍然无法跑通，现象是以下这句会出现core dump：
> data_io = xdl.DataIO("tdm", file_type=xdl.parsers.txt, fs_type=xdl.fs.hdfs, namenode="hdfs:/localhost:9000", enable_state=False)

请问解决了吗 同样的问题

**Comment by woso** [comment]
> @jump2 ,楼上描述的问题解决了么？我也遇到同样的问题，master/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hdfs://xxxx:port/

libhdfs需要配置CLASSPATH等环境变量，可以排除一下是否是这个原因，导致libhdfs无法使用

**Comment by MrChengmo** [comment]
> @songyue1104 @lovickie
> 运行 严格按照教程操作，执行python train.py --run_mode=local --config=config.train.json的过程一直报段错误，Load successfully, leaf node count:Segmentation fault。看了源码没什么问题，请问会是什么原因？

请问这个问题您解决了吗？我也遇到了相同的问题。

**Comment by farseer002** [comment]
> > @songyue1104 @lovickie
> > 运行 严格按照教程操作，执行python train.py --run_mode=local --config=config.train.json的过程一直报段错误，Load successfully, leaf node count:Segmentation fault。看了源码没什么问题，请问会是什么原因？
> 
> 请问这个问题您解决了吗？我也遇到了相同的问题。

这个段错误是解决了，主要是java和hadoop的一堆库都要加到环境变量里，
下面的HADOOP_HOME名字要改一下，不然要跟原来的设置重复
export HADOOP_HOME=/your/hadoop/hadoop-2.7.0/share
export HADOOP_CLASSPATH=.
for f in $HADOOP_HOME/hadoop/common/hadoop-*.jar; do
        HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f
done
for f in $HADOOP_HOME/hadoop/common/lib/*.jar; do
        HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f
done

for f in $HADOOP_HOME/hadoop/mapreduce/hadoop-*.jar; do
        HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f
done
for f in $HADOOP_HOME/hadoop/hdfs/hadoop-*.jar; do
        HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:$f
done

export CLASSPATH=.:$HADOOP_CLASSPATH:$CLASSPATH

-----
然后就是java相关的lib路径都要在LD_LIBRARARY_PATH里

-----
这样操作后，能运行了，但结果不对，emb没生成（我把代码改到cpu的，不行）

sed -i 's/..//' data/item_emb
hadoop fs -put -f data/item_emb hdfs://xxxxxxx/emb/
finish put item_emb
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
