### ISSUE TITLE
问个问题：yarn是否可以支持大规模分布式ML训练

### ISSUE THREAD

**Issue by Ethan199111** [alibaba/x-deeplearning#37]
既然阿里妈妈是用yarn来调度xdl，是否说明yarn是可以处理高纬稀疏数据的模型训练，或者说yarn在阿里妈妈的这个体量上不会因为自身的缺陷有问题
（gpu那个补丁除外）

为什么会有这个问题？
现在很多框架已经转移到k8s并使用kubeflow或类似的调度框架，hadoop yarn不太是主流。

**Comment by kinglion811** [comment]
@songyue1104  现在大家都在跑k8s了，主流的开源框架，都可以轻松跑在k8s上，xdl一枝独秀，还这么深度支持yarn，深度学习框架至少在资源调度编排上，对于那家都可以轻松支持的，而不是将用户往yarn上引，不然只能增加使用成本对影响力有一定影响。

**Comment by songyue1104** [comment]
@kinglion811   XDL可以接入任意分布式调度系统，只是由于人力原因，目前只提供yarn的支持。后续会根据工作安排情况确定是否要支持k8s

**Comment by kinglion811** [comment]
@songyue1104  我们最近能在k8s上将xdl 跑起来，稳定后提个pr 大家讨论一下

**Comment by Esail** [comment]
@kinglion811 这可能说明阿里的调度框架是一个类yarn的东西，至少api一致。 再说yarn也不是一无是处，和hadoop生态更紧密，可以计算存储一体。相比于k8s,yarn部署使用更简单，但是app on yarn太复杂 不如k8s方便。yarn的生态不够完善，k8s有google背书用的人更多，坑都踩了。各有各的好，只要能支持业务就行

**Comment by backyes** [comment]
1. Parameter server 是否支持对稀疏化参数对应的权重，也做稀疏化通信更新？  否则，通信量是否还是很大？
