### ISSUE TITLE
怎么打开XDL_LOG(DEBUG) 这种日志？

### ISSUE THREAD

**Issue by anqin** [alibaba/x-deeplearning#374]
或者说，这些日志都输出在哪里？

**Comment by Jim59-Chen** [comment]
Tony Qin, 你好，我看到您发的多封邮件，在此需要声明。
我并不是这套系统的开发者和维护者，只是一年前为了完成数据挖掘课程的大作业才来关注这个开源代码。
怎么说呢，我当时放弃了使用阿里巴巴的开源代码，因为确实有太多坑，能力有限复现不了。后面发现百度的PaddleRec也有实现这个模型，转而使用PaddlePaddle的模型。那里的模型开箱即用，应该满足了需求，要跑完阿里巴巴论文完整数据需要较大的算力，我并没有走到这一步。
现在我完全不记得关于这个模型的任何内容了，这些问题我无法解答。



---原始邮件---
发件人: "Tony ***@***.***&gt;
发送时间: 2024年7月2日(周二) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [alibaba/x-deeplearning] 怎么打开XDL_LOG(DEBUG) 这种日志？ (Issue #374)




 
Closed #374 as completed.

**Comment by anqin** [comment]
感谢回复。




刚刚接触这个系统没多久，在试用所以还是不太熟悉。加问一句：这个5年前系统，是不是已经没人维护了？
















在 2024-07-02 11:37:59，"Jim59-Chen" ***@***.***> 写道：

Tony Qin, 你好，我看到您发的多封邮件，在此需要声明。
我并不是这套系统的开发者和维护者，只是一年前为了完成数据挖掘课程的大作业才来关注这个开源代码。
怎么说呢，我当时放弃了使用阿里巴巴的开源代码，因为确实有太多坑，能力有限复现不了。后面发现百度的PaddleRec也有实现这个模型，转而使用PaddlePaddle的模型。那里的模型开箱即用，应该满足了需求，要跑完阿里巴巴论文完整数据需要较大的算力，我并没有走到这一步。
现在我完全不记得关于这个模型的任何内容了，这些问题我无法解答。



---原始邮件---
发件人: "Tony ***@***.***&gt;
发送时间: 2024年7月2日(周二) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [alibaba/x-deeplearning] 怎么打开XDL_LOG(DEBUG) 这种日志？ (Issue #374)





Closed #374 as completed.
