### ISSUE TITLE
查看失败日志问题

### ISSUE THREAD

**Issue by niumeng07** [alibaba/x-deeplearning#39]
任务失败信息如下
18/12/30 23:16:50 INFO xdl.Client: AppMaster host N/A Start waiting application: application_1546112727033_3813 ends.
18/12/30 23:16:51 INFO xdl.Client: Application application_1546112727033_3813 finish with state FAILED
18/12/30 23:16:51 INFO xdl.Utils: ================================FINAL STATUS==================================
18/12/30 23:16:51 INFO xdl.Utils:   application_1546112727033_3813 : FAILED
18/12/30 23:16:51 INFO xdl.Utils: ================================FINAL STATUS==================================

但通过yarn logs看日志会报如下错误，看不到任何日志。
18/12/30 23:36:18 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm2

请问是什么原因。

**Comment by songyue1104** [comment]
提供一下AppMaster的日志
