### ISSUE TITLE
样本中的group id的具体含义？

### ISSUE THREAD

**Issue by LIO-H-ZEN** [alibaba/x-deeplearning#40]
sample id指的是每条样本的id，那么group id是为了给样本分组吗？指定之后有什么好处呢？

具体来说：比如，广告场景中，用户侧特征经常在多条样本中是不变的，通常的做法是数据shuffle之后，在embedding lookup的实现时，都会把key做unique，保证取embedding只取一次之类的。然后根据pull的结果还原出batch数据对应tensor，再进行下一步处理。

那么现在我们把group id指定成用户id，我猜测可能的好处有二：
1. 数据可以按照用户id shuffle，这样一个batch内unique之后的key个数会大幅减小，从而减少通信量。
2. 在还原batch数据对应的tensor时，可以不用完全重建，而是想办法保证用户侧特征只有一份，只计算一次。

综上，我的问题是：
1. group id是否是为了以上两点的效率优化而存在的？大概的工作原理是否类似上述？
2. 如果是会根据group id来shuffle数据，那么在online learning的场景下，这样会导致比如用户侧特征更新次数较少，有试过在online learning的场景下，auc和线上效果是否会吃亏呢？

**Comment by woso** [comment]
1. 你理解的完全正确，group id就是为了表示有一部分特征是一样的，只保留一份，具体见’结构化压缩‘
2. 实际上不会根据group id 来shuffle数据，数据需要提前排序好，group id一样的排在一起；offline我们对比把每天的用户样本打到一块，效果差别很小；online问题更小，实时过来的样本能被打到一块的很少；当然效果和具体数据相关，以上是阿里数据上的观察

另外大规模使用建议使用pb结构，效率比较高
