### ISSUE TITLE
期待XDL能够支持导出兼容tensorflow格式的模型

### ISSUE THREAD

**Issue by sydpz** [alibaba/x-deeplearning#49]
当前XDL导出的模型貌似与tensorflow格式的模型不一致，且当前尚未看到该模型如何方便的加载到线上用于预估的示例（如C++版本的SDK）， 建议

- XDL 能够提供一个方便将模型转为tensorflow模型格式的工具
- 或者 XDL 能够提供一个对外的C++ 版本的模型加载接口
如此，方便开发者将模型快速部署用于在线预估

**Comment by lovickie** [comment]
目前有计划将模型导出为明文或numpy格式，稍后会将代码同步上来。

**Comment by shamomanba** [comment]
> 当前XDL导出的模型貌似与tensorflow格式的模型不一致，且当前尚未看到该模型如何方便的加载到线上用于预估的示例（如C++版本的SDK）， 建议
> 
> * XDL 能够提供一个方便将模型转为tensorflow模型格式的工具
> * 或者 XDL 能够提供一个对外的C++ 版本的模型加载接口
>   如此，方便开发者将模型快速部署用于在线预估

现在XDL能够支持导出兼容tensoflow格式的模型吗？
