### ISSUE TITLE
CrossMedia能跑单机吗

### ISSUE THREAD

**Issue by zhuiyuan616124** [alibaba/x-deeplearning#55]
使用CrossMedia的Script目录下的randing.py和randtxt.py生成数据后，在本地启动python runner.py --run_mode=local --config config.json，报这样一个错误  /home/yue.song/x-deeplearning/xdl/xdl/data_io/packer/pack_feature.cc:294] Check failed: blk->ts_[Block::kValue]->Shape()[1] == val.vector_size() dense feature=ad0 vector_size=，请问怎么解决，CrossMedia也没有详细介绍数据格式，能否补充下文档

**Comment by songyue1104** [comment]
CrossMedia没有提供单机模式，数据格式参考XDL用户指南的数据准备部分

**Comment by bboy-yang** [comment]
应该是dense feature的dim没有配置对
