### ISSUE TITLE
ubuntu-gpu-tf1.12镜像中无法运行TDM单机试验小数据集

### ISSUE THREAD

**Issue by peipei-pig** [alibaba/x-deeplearning#59]
在registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12镜像中运行TDM目录下的script/tdm_ub_att_ubuntu，存在以下问题：
（1）执行：python train.py --run_mode=local --config=config.train.json报错No module named mxnet。ubuntu-gpu-tf1.12镜像中并没有安装mxnet。
（2）执行：ubuntu-gpu-tf1.12 报错ImportError: No module named sklearn.cluster
如果方便的话，麻烦补充下

**Comment by zhuiyuan616124** [comment]
你这用的镜像是tf版本，用mxnet版本的 registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-cpu-mxnet1.3

**Comment by peipei-pig** [comment]
@zhuiyuan616124 用mxnet版本我没有验证，按道理应该能解决该问题。只是在文档里面没有说清楚TDM目前给出的只能在mxnet运行，在tf运行还需要二次开发。

**Comment by drfilter** [comment]
@zhuiyuan616124 , 训练是遇到段错误，你有遇到吗？Load successfully, leaf node count:Segmentation fault

**Comment by zhuiyuan616124** [comment]
没有，里面很多配置要自己修改

**Comment by drfilter** [comment]
@zhuiyuan616124 , 你单机训练能跑出结果吗？我现在没有保存了，好像是cpu训练很慢，一直卡在第0步。

**Comment by githcx** [comment]
可以安装python的调试
sudo apt-get install gdb python-dbg

执行gdb python
run train.py --run_mode=local --config=config.train.json
然后出core后，输入bt回车

看看哪里出问题，有可能和我的问题类似，出在类似hadoop的问题上，反正我们已经绕过这个问题了，修改了训练脚本，不上传到hadoop hdfs，各步骤之间都是直接cp中间结果文件。

> 在registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-tf1.12镜像中运行TDM目录下的script/tdm_ub_att_ubuntu，存在以下问题：
> （1）执行：python train.py --run_mode=local --config=config.train.json报错No module named mxnet。ubuntu-gpu-tf1.12镜像中并没有安装mxnet。
> （2）执行：ubuntu-gpu-tf1.12 报错ImportError: No module named sklearn.cluster
> 如果方便的话，麻烦补充下

**Comment by jlinleung** [comment]
@drfilter 同遇到一样的段错误，最后有找到解决的方法了么

**Comment by jlinleung** [comment]
> 没有，里面很多配置要自己修改

@zhuiyuan616124 除了按照教程说明中需要修改的参数，请问还改了哪些参数？

**Comment by githcx** [comment]
我们改成了local，不用hdfs，绕过去。从core来看我自己看不明白的，好像是hadoop连接不上，我觉得最好有人做好了能回答一下你。

**Comment by better629** [comment]
> @peipei-pig 你的tf GPU 镜像找得到GPU吗？怎么我的找不到呢

Use docker image `nvidia/cuda:9.0-devel` to build a clean environment. The office images can't not detect cuda devices.
