### ISSUE TITLE
关于ps-plus更多的例子

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#62]
你好，我在文档中看到ps-plus这个使用的一个例子，问下能否提供更多的例子呢，比如一个完整的kv的简单例子。我这边server的参数想要使用adam更新参数，应该怎么配置呢

**Comment by songyue1104** [comment]
主要接口都在ps-plus/client/client.cc下面，其中DensePush和SparsePush负责更新参数，xdl里负责和ps-plus通信的op实现在xdl/core/ops/ps_ops下面，python接口在xdl/python/training/optimizer_impls.py里
