### ISSUE TITLE
关于ps-plus通信的问题

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#63]
我看了哈代码的，这个代码的client如果想要去server获得信息是不是都要通过访问scheduler,不好意思代码没有怎么看懂。只是想知道流程，以及海量的key是如何分配到各个server去保存的呢。如果一个server挂了，真个实验需要重启不，有没有备份的操作。

**Comment by shanshanpt** [comment]
需要访问scheduler，同时scheduler会通过placement操作将key放到不同的server上。

**Comment by songyue1104** [comment]
只访问一次，后面一直用worker缓存的值，key是通过placement策略分配到各个server的，目前有多种分配策略，对性能要求较高的建议采用rebalance策略，会动态统计每个参数的访问频率和密度。server挂了yarn会自动拉起并且恢复到上一个checkpoint

**Comment by songziqin** [comment]
这个我就有疑问了呀。如果一直用worker缓存的值，那么如果其他worker更新了参数呢。如果一台server挂了是不是所有的worker都要重新等着这台server重启呢，因为获取不到这台server的参数了

**Comment by Esail** [comment]
@songziqin  我没有看过源码，但是参数服务器会用replication+consistenHashing来做熔灾和数据一致性的 所以如果一个server挂了，应该不影响worker去push参数。但是看作者的意思是用checkpoint+增量学习的方式来做failRecovery, 就是如果server挂了，就初始化上一次checkpoint的模型 然后重新从上一个点开始训练，不知道我理解的对不对

**Comment by songziqin** [comment]
话虽这么说，不知道有没有实现呢。

**Comment by Esail** [comment]
@songziqin 如果你不打算做在线学习，其实就算整个任务挂了，重新再拉起来跑一次就行了。只有到在线学习的时候，才需要ps对HA和一致性做取舍，我们当然一般选择HA. 参数更新不及时不算太关键，只要最终一致性保证了就行。

**Comment by songziqin** [comment]
主要是为了训练跑得更快，任务挂了，重新load参数其实还是很耗时的，而且数据量大，机器多的情况，进程挂还是非常容易发生的

**Comment by songyue1104** [comment]
worker缓存的是参数分配的结果，简单说就是一个key应该到哪个server上获取weight。 
failover方面，如果worker发生failover，由yarn拉起后恢复到挂掉时读取的样本继续训练，如果ps发生failover，yarn拉起后，所有ps从上一个checkpoint恢复参数，所有worker也恢复到上一次checkpoint的样本进度，继续训练。

Failover主要有两种设计，一种是分布式一致性checkpoint，也就是XDL采用的方式，这种方式比较适合failover次数较少，且代价不高的场景。还有一种是多replica，适合于经常发生failover或者failover代价比较高的场景

**Comment by songziqin** [comment]
哦。好的，谢谢呢。如果有新的server加进来，那key的分配不会变末。如果key的分配变了，这个如何保证更新给client呢。还是一开始的时候server数是不能变的。多了，少了都不支持呢。

**Comment by songziqin** [comment]
> worker缓存的是参数分配的结果，简单说就是一个key应该到哪个server上获取weight。
> failover方面，如果worker发生failover，由yarn拉起后恢复到挂掉时读取的样本继续训练，如果ps发生failover，yarn拉起后，所有ps从上一个checkpoint恢复参数，所有worker也恢复到上一次checkpoint的样本进度，继续训练。
> 
> Failover主要有两种设计，一种是分布式一致性checkpoint，也就是XDL采用的方式，这种方式比较适合failover次数较少，且代价不高的场景。还有一种是多replica，适合于经常发生failover或者failover代价比较高的场景

**Comment by Esail** [comment]
@songyue1104  @songziqin 那也就是说，ps-plus不太适合在线推理。ps-plus没有多副本就意味着高可用是没有保障吧，主要是针对离线这种fail场景少的情况。
