### ISSUE TITLE
Ftrl优化器实现拼写有误

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#64]
在尝试使用Ftrl优化器的时候，发现一处拼写错误：
def sparse_update(self, var, grad, indices):
        return xdl.ps_sparse_apply_ftrl_op(
            learning_rate = self._lr,
            learning_rate_power = self._lr_power,
            initial_accumulator_value = self._init_acc,
            l1_reg = self._l1_reg,
            l2_reg = self._l2_reg,
            grad = grad,
            **ndices** = indices,
            var_name = var.name,
            var_type = var.vtype)

这里ndices应该是indices

**Comment by songyue1104** [comment]
谢谢提醒
