### ISSUE TITLE
TDM demo， 运行python train.py --run_mode=local --config=config.train.json 问题

### ISSUE THREAD

**Issue by zhengkai215** [alibaba/x-deeplearning#65]
![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)

错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
这部分能帮忙解释一下吗？谢谢

**Comment by lovickie** [comment]
ub_tree.pb的大小正确么？可否给栈信息看一下？

**Comment by chengenbao** [comment]
> ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> 
> 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> 这部分能帮忙解释一下吗？谢谢

有可能是pb版本的问题

**Comment by jlinleung** [comment]
> ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> 
> 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> 这部分能帮忙解释一下吗？谢谢

楼主解决这个问题了么

**Comment by jlinleung** [comment]
> > ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> > 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> > 这部分能帮忙解释一下吗？谢谢
> 
> 楼主解决这个问题了么

![image](https://user-images.githubusercontent.com/9393229/51527574-b77aeb00-1e6f-11e9-939a-82eb6fdc2047.png)

xdl依赖的是proto3， 为啥tdm用的是proto2，两者不一致？

**Comment by zhengkai215** [comment]
> ub_tree.pb的大小正确么？可否给栈信息看一下？

userbehavoir__tree.pb 的大小是524k

**Comment by zhengkai215** [comment]
> > ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> > 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> > 这部分能帮忙解释一下吗？谢谢
> 
> 楼主解决这个问题了么

还没有

**Comment by jlinleung** [comment]
> > > ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> > > 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> > > 这部分能帮忙解释一下吗？谢谢
> > 
> > 
> > 楼主解决这个问题了么
> 
> 还没有

试了下读本地文件没有问题

**Comment by CyanSong** [comment]
同出现问题

**Comment by ZWhangH** [comment]
> ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> 
> 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> 这部分能帮忙解释一下吗？谢谢
楼主，问题解决了吗

**Comment by qianghuang84** [comment]
出现类似的问题，这个软件也太多问题了吧，使用docker跑个实例也跑不通

**Comment by mengyiliu22** [comment]
也出现了一样的问题，定位到报错语句是init()方法里面的tree.load()
使用python解释器交互运行没问题
<img width="543" alt="image" src="https://user-images.githubusercontent.com/15141419/54662255-6e19e580-4b18-11e9-8d3d-e1b1d7965476.png">
脚本执行报同样的错误
请问现在有解决方案吗？

**Comment by MrChengmo** [comment]
> ![image](https://user-images.githubusercontent.com/18067399/51109735-12d62900-1831-11e9-9da1-8cf8b6c4ec4c.png)
> 
> 错误输出：Load successfully, leaf node count:Segmentation fault (core dumped)
> 这部分能帮忙解释一下吗？谢谢

请问这个问题您最后解决了吗？我也遇到了相同的问题。
