### ISSUE TITLE
AMS 里的 Dense 参数是如何同步或更新的？

### ISSUE THREAD

**Issue by shishaochen** [alibaba/x-deeplearning#66]
非常感谢你们开源的 XDL，给了业界很多启发。
查阅论文 [Image Matters: Visually modeling user behaviors using
Advanced Model Server](https://arxiv.org/pdf/1711.06505.pdf)，多个 AMS 之间存在参数同步/更新。

基于示例代码 [CrossMedia](https://github.com/alibaba/x-deeplearning/blob/master/xdl-algorithm-solution/CrossMedia/script/runner.py) 中 user_graph_model 部分，请问：
1. 每个负责 user_graph_train 的 AMS 都会持有完整的 Dense 参数（全连接层）吗？
2. 如果是，多个 AMS 如何彼此交换 Dense 参数，达到最终一致？
3. 如果不是，Dense 参数的放置策略和更新方式是如何？
4. 什么时候、由谁触发所有 AMS 的一次同步更新？

期待回复，非常感谢！

**Comment by songyue1104** [comment]
在AMS的设计里，一张完整的计算图会被分为一个主图和若干个子图（比如CrossMedia里的image graph），主图和每个子图都由一组ams负责执行，每组ams的数量都任意可配，一次graph执行由主图驱动，从所有子图ams里获取前向结果，进行前向和反向计算，再将梯度发往子图ams进行反向计算，最后所有ams进行梯度更新，所有参数都存放在PS-Plus里
