### ISSUE TITLE
ps-plus的设计考虑到在线的情况吗

### ISSUE THREAD

**Issue by Ethan199111** [alibaba/x-deeplearning#70]
我可以使用ps-plus做在线学习的梯度实时更新吗？像FTRL这类
ps-plus可以作为常驻服务吗？我在物理集群部署ps-plus
有没有考虑做配套的，如模型管理，模型从持久层如(hbase)这种拉入到ps-plus中。模型热更新这些

**Comment by songyue1104** [comment]
在设计ps-plus的时候，主要考虑离线训练的场景，因此ps-plus主要针对吞吐进行优化。
ps-plus目前仅支持从hdfs读取全量模型，不支持从消息队列做增量更新，你也可以利用ps-plus的client api自己实现一下增量更新的逻辑
