### ISSUE TITLE
请问下TDM模型有没有单独的python tensorflow版本？

### ISSUE THREAD

**Issue by guotong1988** [alibaba/x-deeplearning#72]
多谢多谢多谢！！

**Comment by jlinleung** [comment]
看了源码，目前只支持mxnet

**Comment by jlinleung** [comment]
> 多谢多谢多谢！！
看了源码，目前只支持mxnet

**Comment by guotong1988** [comment]
Thank you. I just find the pure python implementation.
https://github.com/alibaba/x-deeplearning/tree/master/xdl-algorithm-solution/TDM/script
