### ISSUE TITLE
变量(variable)是如何在分布式场景下分布, 如何工作的

### ISSUE THREAD

**Issue by yuandaxing** [alibaba/x-deeplearning#75]
HI,
  我对x-deeplearning很感兴趣, 有很多不懂, 下面几个疑问请帮忙解答一下.
   1. 各个运行节点的角色分为ps, worker, extend_role, xdl里面的variable和tf的input通过相互memcpy运行.
       a. 在分布式训练下.xdl里面定义的变量(variable)在ps, worker, extend_role里面是用的,怎么更新的.
       b. 在分布式训练下, tf里面的variable是怎么在ps, worker, extend_role里面用的.
       c. tf和xdl的参数分别怎么保存的.
   2. 分布式训练中:
     a. ps挂掉, 在自动重启之前是不是整个训练都会挂起?
     b. 能否详细解释 ps, worker, schedule, extend_role的具体含义, 期待更加详细的文档以及每个模块必要的注释

**Comment by songyue1104** [comment]
1. xdl和tf的variable统一都存放在ps-plus上，variable的更新一般发生在optimizer里，可以查看optimizer的python代码，variable通过CheckpointSaveHook保存
2. 是的， ps：存放参数， worker， extend_role：执行训练逻辑      schedule：协调ps

**Comment by songziqin** [comment]
> 1. xdl和tf的variable统一都存放在ps-plus上，variable的更新一般发生在optimizer里，可以查看optimizer的python代码，variable通过CheckpointSaveHook保存
> 2. 是的， ps：存放参数， worker， extend_role：执行训练逻辑      schedule：协调ps

我有一个疑问，variable具体代表什么意思呢。比如整体userid代表一个variable，还是一个userid就是一个variable呢，如果一个userid代表一个variable，那么所有的variable都要在schedule存一份数据，假设这些很大是海量的，那么scheduler会不会内存爆掉。还有对于userid这种类型的id特征应该选择VariableInfo::kHash,还是VariableInfo::kIndex，这些应该怎么选择呢。
