### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#76]
/home/songziqin/x-deeplearning/xdl/ps-plus/ps-plus/client/partitioner/hash.cc:42:24: error: ‘sqrt’ was not declared in this scope
     dims[0] = k + 10 * sqrt(k) + 10;
                        ^~~~
/home/songziqin/x-deeplearning/xdl/ps-plus/ps-plus/client/partitioner/hash.cc:42:24: note: suggested alternative: ‘qsort’
     dims[0] = k + 10 * sqrt(k) + 10;
                        ^~~~
                        qsort

问下是不是我的gcc版本没有设置对的原因呢。

**Comment by chengenbao** [comment]
你用的什么编译环境? 试试在hash.cc文件加入 #include <math.h>

**Comment by songziqin** [comment]
加上了，这个可以过了，但是又出现了
/bin/ld: cannot find -lps_network_static
/bin/ld: cannot find -lseastar
/bin/ld: cannot find -lunwind
/bin/ld: cannot find -lcares-seastar
/bin/ld: cannot find -ljemalloc
collect2: error: ld returned 1 exit status

**Comment by songziqin** [comment]
哦。我是在我的机器上面看的这个编译的。
https://github.com/alibaba/x-deeplearning/tree/master/xdl/ps-plus。

git clone --recursive https://github.com/alibaba/x-deeplearning.git
cd x-deeplearning/xdl
mkdir build && cd build
export CC=/usr/bin/gcc-5 && export CXX=/usr/bin/g++-5
cmake .. -DTF_BACKEND=1
make -j8

**Comment by lxl910915** [comment]
@chengenbao  
能否提供一个可用的编译环境的镜像？看起来有很多人像我们一样编译失败的。谢谢！

**Comment by chengenbao** [comment]
@zhuzhaoyuan @lxl910915 你们可以试试docker环境, 我这边测试是没有问题的, 你们编译的时候注意看下所用的gcc版本, cmake的时候一般会有显示, 这边编译要求是gcc-5.3及以上
 sudo docker pull ubuntu:16.04
sudo docker run --net=host -it ubuntu:16.04 /bin/bash

**Comment by songyue1104** [comment]
请参考编译安装部分的wiki，推荐使用docker进行编译，可以根据使用的深度学习后端选用对应build好的docker镜像

**Comment by lxl910915** [comment]
@chengenbao @songyue1104  多谢二位的指导。
我们这边已经编译成功，主要原因是编译机器不能git clone，所以先拷贝到了winds上。文件（x-deeplearning/xdl/third_party/seastar/service/build_script/build.sh）的文本模式变成dos，而不是unix （通过set ff查看），此外py文件（x-deeplearning/xdl/third_party/seastar/configure.py和x-deeplearning/xdl/third_party/seastar/json/json2code.py ）的可执行权限没了。

**Comment by lxl910915** [comment]
> 加上了，这个可以过了，但是又出现了
> /bin/ld: cannot find -lps_network_static
> /bin/ld: cannot find -lseastar
> /bin/ld: cannot find -lunwind
> /bin/ld: cannot find -lcares-seastar
> /bin/ld: cannot find -ljemalloc
> collect2: error: ld returned 1 exit status

在这个错误之前可能已经报错了，被日志覆盖了，可以再往前找一找错误。
另，卸载xdl是pip uninstall xdl

**Comment by songziqin** [comment]
> @chengenbao @songyue1104 多谢二位的指导。
> 我们这边已经编译成功，主要原因是编译机器不能git clone，所以先拷贝到了winds上。文件（x-deeplearning/xdl/third_party/seastar/service/build_script/build.sh）的文本模式变成dos，而不是unix （通过set ff查看），此外py文件（x-deeplearning/xdl/third_party/seastar/configure.py和x-deeplearning/xdl/third_party/seastar/json/json2code.py ）的可执行权限没了。

问下你们是用docker build，还是在linux机器上面build的。

**Comment by lxl910915** [comment]
> > @chengenbao @songyue1104 多谢二位的指导。
> > 我们这边已经编译成功，主要原因是编译机器不能git clone，所以先拷贝到了winds上。文件（x-deeplearning/xdl/third_party/seastar/service/build_script/build.sh）的文本模式变成dos，而不是unix （通过set ff查看），此外py文件（x-deeplearning/xdl/third_party/seastar/configure.py和x-deeplearning/xdl/third_party/seastar/json/json2code.py ）的可执行权限没了。
> 
> 问下你们是用docker build，还是在linux机器上面build的。

docker build的， gcc 5.4

**Comment by songziqin** [comment]
> 请参考编译安装部分的wiki，推荐使用docker进行编译，可以根据使用的深度学习后端选用对应build好的docker镜像

问下，那个后端一定要源代码安装末，pip 这种形式的不可以末。。

**Comment by chengenbao** [comment]
> > 请参考编译安装部分的wiki，推荐使用docker进行编译，可以根据使用的深度学习后端选用对应build好的docker镜像
> 
> 问下，那个后端一定要源代码安装末，pip 这种形式的不可以末。。
可以的, 我在Ubuntu 18.04上测试过
