### ISSUE TITLE
ps-plus支持hadoop 2.7.3吗

### ISSUE THREAD

**Issue by Ethan199111** [alibaba/x-deeplearning#78]
不做复杂深度模型，只做一些简单逻辑的运行。希望ps-plus可以和spark连通，支持一些基础模型的训练。
ps-plus可以满足这个需求吗？
谢谢

**Comment by Esail** [comment]
我想基于ps-plus编写一些简单的分布式机器学习算法，主要是让同样在yarn上运行的spark和 ps-plus交互，不知道有没有类似的指南。

**Comment by guoxinyang** [comment]
可以，本身ps-plus跟hadoop并没有直接的关系，只有读写checkpoint的时候可能会用到，一般hadoop版本都是可以兼容的。
