### ISSUE TITLE
分布式训练的问题

### ISSUE THREAD

**Issue by shengofsun** [alibaba/x-deeplearning#8]
1. 请问有分布式训练的sample代码吗？
2. 用户文档的分布式训练部分，看到起分布式任务需要传一些参数进去，比如
```
--task_name=scheduler --zk_addr=zfs://xxx --ps_num=2 --ps_cpu_cores=10 --ps_memory_m=4000 --ckpt_dir=hdfs://xxx/checkpoint
```
请问这些参数分别是传给哪些类进行处理的？
另外--zk_addr指的是zookeeper吗？后面的路径格式是什么？传给哪些模块进行处理？

**Comment by shengofsun** [comment]
另外求开个slack channel、或者qq群、或者微信群

**Comment by songyue1104** [comment]
1. 分布式训练和单机训练的代码是完全一致的，只是参数不同
2. 这些参数主要是传给PS-Plus用的， --zk_addr需要指定一个可用的zk地址，用于PS-Plus的协同

**Comment by zhyr** [comment]
> 另外求开个slack channel、或者qq群、或者微信群

https://x-deeplearning.slack.com/
建了一个slack

**Comment by pia-ai** [comment]
权限放开下，加不上

**Comment by lovetimil** [comment]
我先建个群: 335051295，大家加进来，=阿里相关人进来后群主给他

**Comment by weberxie** [comment]
技术相关问题建议开issue，方便其他检索及跟踪。
