### ISSUE TITLE
分布式训练checkpoint保存及其他几个问题

### ISSUE THREAD

**Issue by xiaobaoding** [alibaba/x-deeplearning#82]
参考文档跑了下mnist的分布式训练，同时也大概看了下流程，有一些问题想请教下：

1.scheduler和ps进程cpu一直占满的问题。即使不启动worker进程，scheduler和ps server也是会占满docker的cpu的。翻了下代码，scheduler启动后看起来是阻塞在op_cv上（SchedulerImpl::WaitForOp方法）的，是有其他线程在占用CPU？ps server服务在启动后，往scheduler完成Server的注册后，似乎也是阻塞的。但实际表现是CPU也一直占满。求解。
![image](https://user-images.githubusercontent.com/4554417/51523354-78946780-1e66-11e9-9c85-f191e1d6e8bd.png)

2.checkpoint保存流程问题。看逻辑流程，应该是worker上的checkpointhook触发了xdl.ps_save_op，会触发scheduler的循环中断(op_cv_.notify_all())，然后调用InternalSave，里面再会调用到ps server的kServerSave，最终是在ps server上完成了checkpoint的保存。
这里的问题是：
a. checkpoint的保存为何在PS上进行？而不是类似tf的chief worker？
b.多个ps server都会触发保存checkpoint么？每个ps server保存的是完整的模型参数(变量有shard的情况)，还是自身servers上的变量？
c. xdl的变量，会通过ps_regisiter_variable_op注册到一个map中（variable_info）。通过tf的api构造的变量，是如何存储的？也是存放在这个map中？另外，这个map如何处理变量分区的问题（这部分细节还没看到）？

3.worker任务的ckpt_dir参数不生效。实际的checkpoint路径是通过scheduler任务启动时指定的。不过如果worker启动是不指定这个参数，则不会触发checkpointhook的执行。

PS：我的运行环境是这样的：在一台20c/48G的物理机(centos7)上，启动多个docker容器，模拟分布式场景。启动1个scheduler、2个ps、2个worker进行分布式训练。

**Comment by songyue1104** [comment]
1. ps-plus采用seastar作为底层通信库，seastar为了效率采用run-to-completion模式，在ps比较空闲的时候会有一定的cpu浪费
2. 通过chief worker中转一次没有必要，尤其当模型较大时chief worker可能oom，tf也提供ps直接save的模式
3. 每个ps只序列化自己的参数
4. tf的变量和xdl变量是一样的处理过程，具体做法是monkey patch，可以查看xdl/python/backend/tf/tf_hook.py
5. worker的ckpt_dir需要和ps一样
