### ISSUE TITLE
ESMM项目中如何设置config.json文件中的checkpoint才能进入测试模式

### ISSUE THREAD

**Issue by zhiweige** [alibaba/x-deeplearning#83]
如题

此外，保存的权重如下图所示，文件名后面还跟了“^0”，这个会不会有影响？
![image](https://user-images.githubusercontent.com/26078984/51524969-3b31d900-1e6a-11e9-81ca-b45908c9b3cb.png)

多谢！

**Comment by sui-hs** [comment]
@zhiweige 
1. 训练保存的模型位于--ckpt=ckpt_dir选项指定的目录中，例如第1000轮保存在ckpt_dir/ckpt-................1000中，使用ckpt-................1000作为测试的ckpt配置
2. 不会影响, "^0"表示server 0保存的

**Comment by zhiweige** [comment]
@sui-hs 多谢回复。
我按照您的回复这样设置的config_test.json
![image](https://user-images.githubusercontent.com/26078984/51528456-adf28280-1e71-11e9-95e9-009306d83da9.png)

然后调用esmm.py
python esmm.py --run_mode=local --ckpt_dir=./ckpt --config=config_test.json

报错如下：
![image](https://user-images.githubusercontent.com/26078984/51528576-e72af280-1e71-11e9-8bea-74f7e0b977c8.png)

**Comment by sui-hs** [comment]
看起来是读文件过程中失败的，确认一下./ckpt是否在当前目录下，16000这个ckpt是否正确产出，换一个ckpt试一下？

**Comment by Daiquanjian** [comment]
> 多谢，可能是被我开始改文件名字时有些文件出错了。问题已解决，谢谢。

你好，想请问一下你的ESMM项目测试时config.json文件是怎么配置的？
