### ISSUE TITLE
ErrorCode [4]: UdfChain BuildFromDef input size error

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#84]
我用ps-plus下面的tool例子使用命令./tool -v push_test_one  -sn 1 -sp zfs://localhost:2181/scheduler -a push
我看到它报ErrorCode [4]: UdfChain BuildFromDef input size error。这个是什么情况呢。我看到client提供的接口，HashPush 与 SparsePush 使用场景有什么不同呢。谢谢。

**Comment by songyue1104** [comment]
tool是一个中间版本的测试工具，HashPush和SparsePush的接口后来有变更，导致出错。
HashPush 用于非id类sparse特征的更新， SparsePush用于id类sparse特征的更新

**Comment by songziqin** [comment]
> tool是一个中间版本的测试工具，HashPush和SparsePush的接口后来有变更，导致出错。
> HashPush 用于非id类sparse特征的更新， SparsePush用于id类sparse特征的更新

问下还可以写个简单的sparse push,sparse pull 的简单程序末。是不是在pull,push操作之前要调用client.RegisterVariable这个接口对variable进行register操作呀。
