### ISSUE TITLE
ps-plus中model_server

### ISSUE THREAD

**Issue by huangfish** [alibaba/x-deeplearning#87]
ps-plus中model_server这个角色是做什么的呢

**Comment by lxl910915** [comment]
同问

**Comment by codewdy** [comment]
https://github.com/alibaba/x-deeplearning/wiki/%E5%9B%BE%E5%83%8F%E8%81%94%E5%90%88%E8%AE%AD%E7%BB%83%E7%AE%97%E6%B3%95(CrossMedia)
