### ISSUE TITLE
问下代码的问题

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#88]
你们好呀，我最近在看ps-plus的代码，我对里面的实现比较感兴趣。有些地方看不懂。在LocalClient类里面，SparsePush本质就是把梯度传给server嘛。为什么有下面这么多的逻辑呢。特别是下面粗体的部分，看了半天，看得一脸懵逼。。。
void LocalClient::SparsePush(const std::string& variable_name, 
                             const Tensor& ids, 
                             const std::string& updater, 
                             const std::vector<Data*>& data, 
                             const LocalClient::Callback& cb) {
  std::vector<Data*> inputs = Args(ids, true);
  inputs.insert(inputs.end(), data.begin(), data.end());
  std::vector<std::unique_ptr<Data>>* outputs = 
    new std::vector<std::unique_ptr<Data>>;
  **std::vector<UdfData> updater_inputs = {
    UdfData("BuildSparseSlice", UdfData(0), UdfData(1))
  };
  for (size_t i = 2; i < inputs.size(); i++) {
    updater_inputs.push_back(UdfData(i));
  }**

  UdfData udf(updater, updater_inputs);
  Callback realcb = [cb, outputs](const Status& st) {
    std::unique_ptr<std::vector<std::unique_ptr<Data>>> deleter(outputs);
    cb(st);
  };

  Process(udf, variable_name, inputs, outputs, realcb);
}

**Comment by shanshanpt** [comment]
@songziqin 所有的操作都会被包成一个udf结构，这一段没有文档确定比较难以难懂。
@songyue1104 最好出个文档 :)

**Comment by songziqin** [comment]
> @songziqin 所有的操作都会被包成一个udf结构，这一段没有文档确定比较难以难懂。
> @songyue1104 最好出个文档 :)

如果有文档那简直太棒了。笔芯

**Comment by lxl910915** [comment]
同问，UdfData的作用是什么？
