### ISSUE TITLE
为什么要对sparse id 分片

### ISSUE THREAD

**Issue by songziqin** [alibaba/x-deeplearning#90]
我从接口ps-plus中的client.cc有个方法
`void Client::SparsePull(
        const std::string& variable_name,
        const Tensor& ids,
        Tensor* result,
        const Client::Callback& cb)
        {`
这个应该是获得ids的参数值的，我看到它最后会调用
RawClient::Process(
  const UdfChain& udf, 
  const std::string& var_name,
  const std::vector<Data*>& datas,
  const std::vector<Partitioner*>& splitter,
  const std::vector<Partitioner*>& combiner,
  std::vector<std::unique_ptr<Data>>* results,
  const Callback& cb_internal)。这个里面会调用SparseId::Init(PartitionerContext* ctx, Data* src)。
貌似有对数据分片。我想问哈为什么要进行分片呢。一个ID的特征如果是一个向量，把它单独存储就好了呀。感觉这样做会有点麻烦。是不是我理解错了呢。

**Comment by songyue1104** [comment]
sparse特征通常维度很高，单台server放不下，所以需要分片
