### ISSUE TITLE
TDM 里的paper里的实验数据，movie的category是如何处理一个item对应多个类别的呢？taobao的数据，网上下载的那个，筛选日期之后，数据量和paper里的对不上了

### ISSUE THREAD

**Issue by Qingsai** [alibaba/x-deeplearning#94]
TDM 里的paper里的实验数据，movie的category是如何处理一个item对应多个类别的呢？taobao的数据，网上下载的那个，筛选日期之后，数据量和paper里的对不上了

**Comment by Qingsai** [comment]
TDM 里的paper里的实验数据，movie的category是如何处理一个item对应多个类别的呢？taobao的数据，网上下载的那个，筛选日期之后，数据量和paper里的对不上了

**Comment by zhuhan1236** [comment]
一个movie对应多个category时，会随机挑选一个作为movie的category；天池上提供的UserBehavior数据集已经是完整的处理后的数据集了，不需要再进行日期过滤
